// Class: ReadBDT-0.4.6_fold4
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT-0.4.6_fold4
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.32/00       [401408]
Creator        : abennett
Date           : Thu Aug 22 15:59:55 2024
Host           : Linux 6772f6b99311 6.5.0-1022-azure #23~22.04.1-Ubuntu SMP Thu May 9 17:59:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /gluster/home/abennett/BDT_training
Training events: 19607
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "125" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "3%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "80" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e-01" [Learning rate for BoostType=Grad algorithm]
UseNvars: "2" [Size of the subset of variables used with RandomisedTree option]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "sdivsqrtsplusb" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 4
mjj                           mjj                           mjj                           m_{jj}                        GeV                               'D'    [500.083496094,7102.28710938]
JetGap                        JetGap                        JetGap                        #Delta y_{jj}                                                   'D'    [0.0204434599727,8.30311965942]
PtBalance                     PtBalance                     PtBalance                     pT_{balance}                                                    'D'    [1.2169821817e-09,0.149861991405]
centrality                    centrality                    centrality                    #xi(Z)                                                          'D'    [5.42057250641e-06,0.999970436096]
NSpec 1
eventNumber                   eventNumber                   eventNumber                   I                                                               'F'    [703,684984192]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new BDT-0.4.6_fold4Node

#ifndef BDT-0.4.6_fold4Node__def
#define BDT-0.4.6_fold4Node__def

class BDT-0.4.6_fold4Node {

public:

   // constructor of an essentially "empty" node floating in space
   BDT-0.4.6_fold4Node ( BDT-0.4.6_fold4Node* left,BDT-0.4.6_fold4Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT-0.4.6_fold4Node();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT-0.4.6_fold4Node* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT-0.4.6_fold4Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT-0.4.6_fold4Node*   fLeft;     // pointer to the left daughter node
   BDT-0.4.6_fold4Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   BDT-0.4.6_fold4Node::~BDT-0.4.6_fold4Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool BDT-0.4.6_fold4Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool BDT-0.4.6_fold4Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT-0.4.6_fold4 : public IClassifierReader {

 public:

   // constructor
   ReadBDT-0.4.6_fold4( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDT-0.4.6_fold4" ),
        fNvars( 4 )
   {
      // the training input variables
      const char* inputVars[] = { "mjj", "JetGap", "PtBalance", "centrality" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'D';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT-0.4.6_fold4() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[4];
   double fVmax[4];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[4];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT-0.4.6_fold4Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT-0.4.6_fold4::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT-0.4.6_fold4Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT-0.4.6_fold4Node*)current->GetRight();
         else current=(BDT-0.4.6_fold4Node*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
}

void ReadBDT-0.4.6_fold4::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.237716,-0.0524567) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.501521,0.000304253) , 
1, 3.14916, 1, 0, 0.34832,-0.15168) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.881915,0.076383) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.353715,-0.029257) , 
3, 0.442866, 1, 0, 0.821136,0.321136) , 
0, 1315.19, 1, 0, 0.492807,-0.00719302)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.245917,-0.0472205) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.479585,-0.00318524) , 
0, 890.853, 1, 0, 0.308437,-0.176845) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.15371,0.126858) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.736199,0.0431227) , 
2, 0.00553606, 1, 0, 0.791482,0.270132) , 
1, 3.61238, 1, 0, 0.502391,0.00262678)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.387328,-0.0154633) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.168594,-0.0583367) , 
2, 0.0166513, 1, 0, 0.252767,-0.207505) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.791658,0.0501808) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.278783,-0.0451186) , 
3, 0.412553, 1, 0, 0.740355,0.200644) , 
1, 3.25268, 1, 0, 0.51713,0.0137877)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.466573,-0.000916222) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.232895,-0.0469891) , 
2, 0.0185015, 1, 0, 0.330656,-0.136536) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601486,0.00943269) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.875295,0.059419) , 
0, 1494.23, 1, 0, 0.758435,0.184468) , 
1, 3.88932, 1, 0, 0.494212,-0.0138045)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.329273,-0.0233197) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0905774,-0.0682017) , 
3, 0.580162, 1, 0, 0.277677,-0.161365) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.868705,0.0572869) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.498556,-0.0124039) , 
2, 0.0498245, 1, 0, 0.796788,0.209644) , 
1, 3.60781, 1, 0, 0.489592,-0.00990917)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.146631,-0.0535858) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.44014,-0.00852884) , 
1, 2.52981, 1, 0, 0.331194,-0.121702) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.96681,0.0741626) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.43296,-0.0206358) , 
3, 0.333337, 1, 0, 0.869934,0.264484) , 
0, 1234.46, 1, 0, 0.503664,0.00193032)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.278523,-0.027409) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.846857,0.0546353) , 
1, 2.62799, 1, 0, 0.689976,0.147167) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.485555,-0.00676164) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.183462,-0.0514793) , 
3, 0.320749, 1, 0, 0.370532,-0.113112) , 
2, 0.0147926, 1, 0, 0.493948,-0.0125546)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.604171,0.0302636) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.25276,-0.0354387) , 
2, 0.00740059, 1, 0, 0.314563,-0.113339) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.845802,0.0422392) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.51671,-0.0174412) , 
3, 0.260181, 1, 0, 0.773759,0.128961) , 
1, 3.798, 1, 0, 0.481473,-0.0252671)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.336517,-0.0186123) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.920358,0.0624459) , 
1, 2.93617, 1, 0, 0.711869,0.144355) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.193658,-0.0409464) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.518302,-0.00566128) , 
0, 714.648, 1, 0, 0.403581,-0.0838868) , 
2, 0.00925074, 1, 0, 0.483523,-0.0247021)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.134331,-0.0483992) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.36727,-0.0140379) , 
1, 2.22067, 1, 0, 0.309049,-0.104425) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.879578,0.0464578) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.366575,-0.0378415) , 
3, 0.334411, 1, 0, 0.810043,0.147288) , 
1, 3.87809, 1, 0, 0.483502,-0.016775)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.443922,-0.00232937) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.157475,-0.0438437) , 
3, 0.469136, 1, 0, 0.363091,-0.0626993) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.03476,0.0800483) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.681361,0.0129064) , 
3, 0.148041, 1, 0, 0.851236,0.184809) , 
0, 1315.21, 1, 0, 0.499002,0.0062127)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.179104,-0.0391247) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.525369,0.00342897) , 
0, 683.184, 1, 0, 0.386665,-0.0601782) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.954222,0.0586215) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.0679,0.0938796) , 
2, 0.0236756, 1, 0, 0.979368,0.260785) , 
0, 1641.25, 1, 0, 0.502137,0.0023525)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.248484,-0.0233948) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.75183,0.0275168) , 
1, 2.9456, 1, 0, 0.595784,0.0483341) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.173179,-0.0336349) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.163038,-0.0594673) , 
1, 3.2744, 1, 0, 0.170157,-0.185918) , 
3, 0.431888, 1, 0, 0.487511,-0.0112563)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
2, 0.00245225, 1, -99, 1.07277,0.116877) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.180299,-0.0314978) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.654866,0.0135786) , 
1, 2.88359, 1, 0, 0.485217,-0.0100024) , 
2, 0.00369077, 1, 0, 0.52542,0.0226724)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.401656,-0.00523421) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.18644,-0.0388915) , 
2, 0.0332833, 1, 0, 0.321379,-0.0771652) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.03909,0.084007) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.739628,0.0158144) , 
2, 0.00546361, 1, 0, 0.793513,0.10233) , 
0, 1143.76, 1, 0, 0.49126,-0.01258)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.612654,0.0390313) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.343707,-0.0148953) , 
3, 0.0370529, 1, 0, 0.362475,-0.0485324) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.955397,0.0560232) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.692639,0.00147239) , 
2, 0.0238589, 1, 0, 0.861457,0.122479) , 
0, 1315.17, 1, 0, 0.516907,0.0043946)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.480728,-0.00400908) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958607,0.0510951) , 
0, 1641.22, 1, 0, 0.591317,0.0228074) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.160186,-0.0290603) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.18392,-0.0480971) , 
1, 2.97316, 1, 0, 0.1704,-0.160378) , 
3, 0.44451, 1, 0, 0.492045,-0.0203964)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543984,0.00450783) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.06885,0.0865969) , 
0, 2593.6, 1, 0, 0.574255,0.0315134) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.14955,-0.0272947) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.138994,-0.048842) , 
1, 2.9588, 1, 0, 0.145139,-0.148802) , 
3, 0.53089, 1, 0, 0.510818,0.00485707)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.771713,0.0306076) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.481805,-0.0156842) , 
2, 0.0314525, 1, 0, 0.682683,0.0590248) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0514648,-0.0562719) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.405208,-0.0166695) , 
1, 1.60765, 1, 0, 0.366256,-0.0860691) , 
3, 0.148198, 1, 0, 0.489512,-0.0295513)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.759994,0.0503268) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.386112,-0.0120852) , 
2, 0.00555045, 1, 0, 0.422524,-0.0252242) , 
NN(
0, 
0, 
2, 0.0165177, 1, -99, 0.987546,0.0608844) , 
0, 1885.75, 1, 0, 0.494707,-0.000323472)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0452453,-0.0516982) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0170502,-0.0659114) , 
0, 656.283, 1, 0, 0.0319207,-0.211124) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.60429,0.013288) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335017,-0.0185456) , 
2, 0.0424431, 1, 0, 0.53702,0.0190409) , 
1, 1.45202, 1, 0, 0.504572,0.00425488)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.612888,0.00591722) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.379012,-0.0167115) , 
2, 0.0129435, 1, 0, 0.467361,-0.0333562) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.0946,0.101112) , 
0, 2835.11, 1, 0, 0.492754,-0.0226864)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.622653,0.015237) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.25647,-0.0378977) , 
2, 0.0756607, 1, 0, 0.586933,0.0383826) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0750588,-0.0561864) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.172567,-0.0243258) , 
3, 0.605929, 1, 0, 0.139818,-0.134829) , 
3, 0.53059, 1, 0, 0.511409,0.00912473)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0643135,-0.0513327) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.211443,-0.0207374) , 
1, 1.57145, 1, 0, 0.17099,-0.108006) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.20491,0.150891) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.584622,0.00375277) , 
2, 0.00367652, 1, 0, 0.619389,0.0356699) , 
1, 2.58438, 1, 0, 0.492594,-0.00495777)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.632647,0.0140876) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.322871,-0.0162274) , 
3, 0.222236, 1, 0, 0.479306,-0.00424838) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.65301,-0.0781817) , 
1, 5.64119, 1, 0, 0.49159,-0.0175467)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.63023,0.00574872) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.22713,0.195887) , 
1, 4.55379, 1, 0, 0.76772,0.0909945) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.607666,0.00886659) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.235244,-0.0263992) , 
3, 0.234528, 1, 0, 0.426945,-0.0326953) , 
2, 0.0073963, 1, 0, 0.496117,-0.00758833)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.664996,0.0134627) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.378454,-0.0103335) , 
2, 0.0312504, 1, 0, 0.566481,0.0187995) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.142797,-0.0155084) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0857423,-0.0500055) , 
1, 2.51057, 1, 0, 0.109767,-0.129404) , 
3, 0.58021, 1, 0, 0.506574,-0.000640511)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.405598,-0.00399797) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.559272,-0.0565263) , 
1, 4.92158, 1, 0, 0.415495,-0.027563) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.798681,-0.0368135) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.07733,0.0989045) , 
3, 0.0592038, 1, 0, 0.981012,0.13059) , 
0, 1885.73, 1, 0, 0.490888,-0.00647845)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.222056,-0.019469) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.318434,0.0370937) , 
2, 0.0758561, 1, 0, 0.229029,-0.0604139) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.680395,0.0551281) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.78004,0.0216808) , 
1, 3.34688, 1, 0, 0.770478,0.0922639) , 
1, 3.11449, 1, 0, 0.52163,0.0220936)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.61293,0.00743791) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.45719,0.451528) , 
1, 4.5937, 1, 0, 0.788882,0.130978) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.431333,-0.0109306) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.204443,-0.0519099) , 
2, 0.0950928, 1, 0, 0.416318,-0.0528903) , 
2, 0.00738141, 1, 0, 0.483392,-0.0197882)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.290587,0.0147011) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.465742,-0.0134994) , 
0, 631.091, 1, 0, 0.436019,-0.036081) , 
NN(
0, 
0, 
2, 0.00586001, 1, -99, 0.983231,0.0550296) , 
0, 2016.19, 1, 0, 0.505737,-0.0168518)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.641816,0.0185313) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.669934,-0.110446) , 
1, 5.87246, 1, 0, 0.644259,0.0450853) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.215093,-0.0568035) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.240765,-0.013727) , 
3, 0.346241, 1, 0, 0.23733,-0.0734719) , 
3, 0.321093, 1, 0, 0.506897,0.00506549)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.29906,-0.0114268) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.379421,-0.0368535) , 
0, 1009.43, 1, 0, 0.310765,-0.0609938) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.862052,0.0242057) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.396418,-0.0182857) , 
3, 0.345625, 1, 0, 0.781695,0.0428928) , 
0, 1145.05, 1, 0, 0.487326,-0.0220447)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.270781,-0.0145723) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.844307,0.0291524) , 
1, 2.70645, 1, 0, 0.671606,0.04297) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.360686,-0.00892037) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.603119,-0.0781389) , 
1, 5.44002, 1, 0, 0.384739,-0.0528263) , 
2, 0.0129175, 1, 0, 0.485797,-0.0190791)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.3292,0.240687) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.649996,0.0138966) , 
2, 0.00546361, 1, 0, 0.727951,0.103773) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.151815,-0.0358016) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.469643,0.00282707) , 
0, 646.98, 1, 0, 0.38349,-0.0280581) , 
3, 0.148185, 1, 0, 0.506551,0.0190393)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.780056,0.0236001) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.379583,-0.0158046) , 
2, 0.00555045, 1, 0, 0.420384,-0.0479373) , 
NN(
0, 
0, 
1, 5.71317, 1, -99, 1.02105,0.077015) , 
0, 2456.29, 1, 0, 0.456217,-0.0378344)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
3, 0.15962, 1, -99, 0.868772,0.0566189) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523936,-0.00404117) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.123336,-0.0274886) , 
3, 0.456792, 1, 0, 0.421897,-0.0336012) , 
2, 0.00555045, 1, 0, 0.473504,-0.0107966)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.6857,0.0090179) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.499787,-0.0478294) , 
3, 0.0252007, 1, 0, 0.569968,-0.0862963) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.133427,-0.0297732) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.545188,0.0137597) , 
1, 2.06565, 1, 0, 0.483231,0.0288191) , 
3, 0.0618088, 1, 0, 0.499505,0.00722123)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.105843,-0.0312683) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436815,0.0150933) , 
1, 1.81187, 1, 0, 0.370279,0.0295297) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.531309,-0.0279144) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.935829,0.0294999) , 
0, 1655.7, 1, 0, 0.697917,-0.0407514) , 
1, 3.74143, 1, 0, 0.51152,-0.000767682)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72447,-0.00390495) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.61705,0.0272848) , 
2, 0.0166513, 1, 0, 0.673924,0.0440492) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.360717,-0.0121439) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.077182,-0.0398706) , 
3, 0.581664, 1, 0, 0.273264,-0.0685368) , 
3, 0.246926, 1, 0, 0.48732,-0.00838666)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.338256,-0.030283) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.230999,-0.000752926) , 
2, 0.0073963, 1, 0, 0.251902,-0.0264692) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.65963,0.0286531) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.806483,-0.0159719) , 
0, 1466.41, 1, 0, 0.722512,0.0532171) , 
1, 3.0881, 1, 0, 0.524908,0.0197577)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.272079,-0.0276593) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.198082,0.000624362) , 
3, 0.30884, 1, 0, 0.241979,-0.0685745) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.742548,0.0193311) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.148081,-0.0306795) , 
3, 0.529824, 1, 0, 0.676419,0.0477701) , 
0, 793.833, 1, 0, 0.492266,-0.00154675)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0646902,-0.0567087) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0238954,-0.0494572) , 
3, 0.321166, 1, 0, 0.0399787,-0.148632) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.750823,0.0223445) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.446139,-0.00299364) , 
3, 0.148261, 1, 0, 0.563721,0.021761) , 
1, 1.65663, 1, 0, 0.518682,0.00710802)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.141837,-0.0308731) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.207631,0.0182584) , 
2, 0.0506658, 1, 0, 0.153506,-0.0789632) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.506843,0.0285792) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.70247,-0.000936941) , 
0, 786.835, 1, 0, 0.659838,0.0238099) , 
1, 2.58709, 1, 0, 0.509949,-0.00661408)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.615326,0.00819919) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.717627,-0.072635) , 
1, 5.8991, 1, 0, 0.623501,0.0150553) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.171992,-0.0166946) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.223693,-0.061976) , 
1, 3.90866, 1, 0, 0.179567,-0.0849466) , 
3, 0.370415, 1, 0, 0.487393,-0.0156048)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.307347,-0.0080244) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.38514,-0.0531153) , 
1, 4.03601, 1, 0, 0.317539,-0.0556343) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.760127,0.0191053) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.81061,-0.0407445) , 
0, 2254.11, 1, 0, 0.773437,0.025614) , 
0, 1152.2, 1, 0, 0.490202,-0.024863)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.691956,0.0382438) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.369974,-0.00782929) , 
3, 0.0495049, 1, 0, 0.39982,-0.0116275) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.766257,-0.0367746) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.00373,0.0756805) , 
3, 0.0638787, 1, 0, 0.918869,0.0833123) , 
1, 4.48459, 1, 0, 0.510363,0.00859205)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0686323,-0.0496164) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0305812,-0.0368278) , 
3, 0.407319, 1, 0, 0.0495083,-0.110851) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.576294,0.00196816) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.267579,-0.0251502) , 
2, 0.0811955, 1, 0, 0.546506,-0.00286593) , 
1, 1.67394, 1, 0, 0.505385,-0.0118006)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.176557,-0.0034686) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.252935,-0.0385921) , 
1, 2.67855, 1, 0, 0.213137,-0.0878297) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.604391,0.0103542) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.661653,-0.0683992) , 
1, 5.97849, 1, 0, 0.608468,0.0203087) , 
0, 661.118, 1, 0, 0.506847,-0.00748869)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.455074,-0.00336189) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.618165,-0.070658) , 
1, 5.31885, 1, 0, 0.471383,-0.0296551) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.07228,0.110966) , 
0, 2835.11, 1, 0, 0.497201,-0.0215093)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.292224,-0.00311697) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.359986,-0.0662679) , 
0, 1490.31, 1, 0, 0.296256,-0.0259574) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.860206,0.0250017) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.891938,0.0763354) , 
3, 0.2898, 1, 0, 0.864958,0.105859) , 
1, 3.52175, 1, 0, 0.53435,0.0292293)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.586226,-0.00980382) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.259569,-0.0576852) , 
3, 0.319956, 1, 0, 0.564882,-0.0459949) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.275522,0.0231737) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.413216,-0.0424572) , 
0, 1510.91, 1, 0, 0.294654,0.0348551) , 
3, 0.345672, 1, 0, 0.493758,-0.024715)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.940037,0.0638256) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.512179,-0.0102537) , 
2, 0.018353, 1, 0, 0.748051,0.0761786) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.508767,-0.0584549) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.42142,-0.00560117) , 
3, 0.0969348, 1, 0, 0.429039,-0.0338752) , 
3, 0.0740668, 1, 0, 0.486467,-0.0140635)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.279277,0.00375226) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.347355,-0.0487796) , 
1, 3.72781, 1, 0, 0.290558,-0.0240936) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.797561,-0.0153248) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.727307,0.0253541) , 
2, 0.0091913, 1, 0, 0.754197,0.0426342) , 
0, 933.251, 1, 0, 0.522524,0.00929141)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0942881,-0.0516331) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.258591,-0.0102501) , 
0, 528.251, 1, 0, 0.235017,-0.0580863) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.747758,-0.0144744) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.702358,0.0201946) , 
3, 0.0617233, 1, 0, 0.713485,0.0397199) , 
0, 826.118, 1, 0, 0.495498,-0.00484007)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.852077,0.00512283) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.758388,0.039243) , 
2, 0.0106228, 1, 0, 0.796655,0.0947976) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560248,-0.0443568) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.446419,-0.00550726) , 
3, 0.0727256, 1, 0, 0.461571,-0.0345245) , 
3, 0.0370529, 1, 0, 0.490566,-0.0233342)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.453136,-0.00286466) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.56197,-0.107202) , 
0, 2257.68, 1, 0, 0.457944,-0.0214722) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.0559,0.107932) , 
0, 2593.75, 1, 0, 0.492917,-0.0116168)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
0, 1234.69, 1, -99, 0.956623,0.0850549) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.363918,-0.0113099) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.899103,0.0314054) , 
0, 1655.2, 1, 0, 0.456724,-0.0229504) , 
2, 0.00555045, 1, 0, 0.513685,0.00587223)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528586,0.00119961) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.08354,0.149441) , 
0, 2449.34, 1, 0, 0.570662,0.0142079) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.193932,-0.00812028) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.441983,-0.0367037) , 
1, 3.64435, 1, 0, 0.296578,-0.0772565) , 
2, 0.0332169, 1, 0, 0.480258,-0.0159606)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.345196,0.0100813) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421559,-0.0689485) , 
0, 1670.87, 1, 0, 0.34931,0.0203624) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.85943,0.00346406) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.489645,-0.0365843) , 
2, 0.0163906, 1, 0, 0.671873,-0.0691698) , 
1, 3.70163, 1, 0, 0.494955,-0.0200635)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
0, 1305.49, 1, -99, 0.956185,0.072498) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.327891,0.00902737) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.719517,-0.0102481) , 
1, 3.65253, 1, 0, 0.492352,0.00467111) , 
2, 0.0037003, 1, 0, 0.525903,0.0148756)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.586071,0.0140505) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.817647,-0.0654211) , 
0, 2130.31, 1, 0, 0.626078,0.0279215) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.200412,-0.0128373) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.338655,-0.0743848) , 
0, 1436.95, 1, 0, 0.213163,-0.062094) , 
3, 0.320938, 1, 0, 0.478161,-0.00432449)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661709,-0.0766843) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454602,-0.00332976) , 
2, 0.00369815, 1, 0, 0.471133,-0.0231364) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.03945,0.0935699) , 
1, 5.90151, 1, 0, 0.496941,-0.0134081)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.289886,-0.00574907) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.453662,-0.0277857) , 
1, 3.85085, 1, 0, 0.322164,-0.0397083) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.801096,0.0261156) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.833571,-0.0535354) , 
0, 2370.48, 1, 0, 0.809586,0.0402737) , 
0, 1224.76, 1, 0, 0.488819,-0.0123617)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.608274,0.00308412) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.558992,0.0688237) , 
2, 0.0258953, 1, 0, 0.604341,0.0268686) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.202539,0.00900395) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.341121,-0.023696) , 
1, 3.01092, 1, 0, 0.294038,-0.0565303) , 
2, 0.0333027, 1, 0, 0.494672,-0.00260673)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.123155,-0.0264828) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.542825,0.00385341) , 
1, 2.19576, 1, 0, 0.467041,-0.00207576) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.25134,0.289874) , 
0, 2805.91, 1, 0, 0.494666,0.00945155)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.356621,-0.0531174) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.922644,-0.053183) , 
1, 3.23774, 1, 0, 0.651732,-0.125117) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.597092,-0.0159417) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438543,0.00708655) , 
3, 0.086556, 1, 0, 0.480474,0.0031306) , 
2, 0.00369815, 1, 0, 0.495864,-0.00839416)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.245235,-0.0240737) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.893234,0.0396199) , 
1, 2.9607, 1, 0, 0.719851,0.0540197) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.255283,0.00647088) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.557363,-0.0139825) , 
1, 3.29411, 1, 0, 0.408195,-0.0146644) , 
3, 0.111131, 1, 0, 0.494376,0.00432851)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.301237,-0.0251582) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.05691,0.106131) , 
1, 2.53297, 1, 0, 0.861707,0.0985653) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528584,-0.0300208) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.411624,-0.00362687) , 
3, 0.0619493, 1, 0, 0.433751,-0.0299806) , 
2, 0.00554722, 1, 0, 0.486278,-0.014203)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.495504,-0.00899392) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.39121,0.0259079) , 
2, 0.0592047, 1, 0, 0.480956,-0.0131937) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.61369,-0.0937699) , 
1, 5.81449, 1, 0, 0.488625,-0.0253395)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.627263,0.00913327) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.624405,0.0518825) , 
2, 0.0234133, 1, 0, 0.626904,0.0468069) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.262347,-0.0374039) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34354,-0.00189898) , 
2, 0.0390581, 1, 0, 0.329156,-0.0306155) , 
2, 0.0332833, 1, 0, 0.526203,0.0206218)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
2, 0.00419618, 1, -99, 0.856607,0.0632585) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482506,0.010226) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.266164,-0.0311221) , 
2, 0.0970425, 1, 0, 0.468808,0.0254654) , 
2, 0.0073963, 1, 0, 0.540495,0.0492975)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.623125,0.00599671) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.24636,-0.0145794) , 
3, 0.320996, 1, 0, 0.488792,-0.00318047) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.626985,-0.107696) , 
1, 5.9936, 1, 0, 0.496965,-0.0167091)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.311176,-0.0248335) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.797933,-0.0027627) , 
1, 3.36391, 1, 0, 0.623716,-0.0396483) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.37081,0.00503437) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.998964,0.0775904) , 
1, 4.58379, 1, 0, 0.441372,0.0366511) , 
3, 0.160611, 1, 0, 0.519226,0.00407412)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.695687,-0.0367307) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.493147,0.00101816) , 
2, 0.00465739, 1, 0, 0.522728,-0.00878357) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.197595,-0.0399914) , 
2, 0.0943576, 1, 0, 0.502195,-0.0167183)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.930594,0.0802695) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.385559,0.00095919) , 
2, 0.00369077, 1, 0, 0.416493,0.0161248) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.577463,-0.0585578) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.932713,0.0245378) , 
0, 1718.97, 1, 0, 0.773942,-0.0611558) , 
1, 4.41748, 1, 0, 0.51078,-0.00426014)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.413617,-0.0051654) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.25167,0.298587) , 
1, 3.19366, 1, 0, 0.826089,0.136871) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.447185,0.00861694) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.669305,-0.0580079) , 
1, 5.54965, 1, 0, 0.464814,0.0162148) , 
2, 0.00922692, 1, 0, 0.548136,0.0440425)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.703808,0.0144215) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.435936,-0.0110369) , 
3, 0.0370178, 1, 0, 0.460237,-0.0287637) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.94384,0.0540764) , 
1, 5.84529, 1, 0, 0.482898,-0.0227277)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.83854,0.00604677) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.68871,0.0382792) , 
2, 0.0146824, 1, 0, 0.763412,0.0781678) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.571176,-0.0617005) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.366441,-0.00392611) , 
2, 0.00553615, 1, 0, 0.396983,-0.0342895) , 
3, 0.111087, 1, 0, 0.496638,-0.00370544)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532462,0.00369396) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.227028,-0.0240534) , 
2, 0.0554722, 1, 0, 0.467457,-0.00881029) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.18541,0.189615) , 
1, 5.83841, 1, 0, 0.49331,0.00204023)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.169145,-0.0298517) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.15519,0.000613234) , 
3, 0.345733, 1, 0, 0.162043,-0.0518112) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.446414,0.025452) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.681961,-0.00262572) , 
0, 742.048, 1, 0, 0.640115,0.0110001) , 
1, 2.69898, 1, 0, 0.491041,-0.00858595)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0952986,-0.0438375) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.514951,-2.46066e-05) , 
0, 556.677, 1, 0, 0.463516,-0.0177009) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.21693,0.409637) , 
0, 2792.92, 1, 0, 0.492979,-0.00718766)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.442161,-0.00322279) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.594085,-0.0561976) , 
1, 5.27095, 1, 0, 0.452949,-0.0220426) , 
NN(
0, 
0, 
1, 5.81692, 1, -99, 1.09288,0.247507) , 
0, 2521.53, 1, 0, 0.492624,-0.0126951)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0549879,-0.0329814) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.333188,0.0138792) , 
1, 1.47473, 1, 0, 0.292659,0.031718) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558018,-0.0207555) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.949013,0.0448209) , 
1, 4.8392, 1, 0, 0.660732,-0.0338885) , 
1, 3.29269, 1, 0, 0.490073,-0.00346972)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.213012,-0.0260368) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.630032,-0.00746379) , 
0, 744.61, 1, 0, 0.495426,-0.0448878) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.359724,0.0626844) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.387187,-0.0117907) , 
1, 3.32073, 1, 0, 0.374773,0.054806) , 
2, 0.0608976, 1, 0, 0.478794,-0.031145)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
0, 1868.97, 1, -99, 0.899148,0.0700777) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.26141,0.0653439) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.476025,-0.00839204) , 
0, 571.795, 1, 0, 0.455812,-0.0103184) , 
2, 0.00555045, 1, 0, 0.510363,0.00705236)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504618,-0.058785) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.10713,0.46023) , 
1, 4.35948, 1, 0, 0.681146,-0.086283) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.392467,0.00179419) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.714936,-0.0542402) , 
1, 5.07974, 1, 0, 0.433496,-0.00990921) , 
2, 0.00740059, 1, 0, 0.482966,-0.0251655)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.671267,-0.208206) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.641509,-0.0293784) , 
3, 0.0616839, 1, 0, 0.649458,-0.113861) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.131985,-0.0231682) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.535332,0.0154131) , 
0, 581.592, 1, 0, 0.475988,0.0361728) , 
2, 0.00925074, 1, 0, 0.524311,-0.00562189)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.852813,0.0428893) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.477552,-0.00186391) , 
2, 0.00604648, 1, 0, 0.532476,0.00756043) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.176052,-0.0453544) , 
2, 0.0980009, 1, 0, 0.505823,-0.00616898)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.712871,-0.000298564) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.448346,-0.0796625) , 
3, 0.0457265, 1, 0, 0.582592,-0.116965) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.432049,0.00479507) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.17454,0.325446) , 
0, 2513.04, 1, 0, 0.463518,0.0241534) , 
3, 0.0740962, 1, 0, 0.491902,-0.00948569)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
1, 3.2666, 1, -99, 0.92921,0.0799711) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.526374,0.00246432) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0902244,-0.0332318) , 
3, 0.580342, 1, 0, 0.459156,-0.00453639) , 
2, 0.00555045, 1, 0, 0.513499,0.0132206)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.428615,-0.00847714) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.671404,-0.0785438) , 
1, 5.22927, 1, 0, 0.445705,-0.0373527) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.0882,0.141716) , 
1, 5.87946, 1, 0, 0.47004,-0.0287533)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.36526,-0.00670755) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.78101,0.0154169) , 
1, 4.1862, 1, 0, 0.439346,-0.0112275) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.574997,-0.0748578) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.974608,0.0245338) , 
0, 2144.81, 1, 0, 0.78993,-0.0842886) , 
1, 5.13321, 1, 0, 0.487427,-0.0212474)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.39402,0.0421894) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.715557,0.00197696) , 
0, 640.203, 1, 0, 0.677174,0.0234534) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435157,-0.0248345) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.254183,-0.0053447) , 
3, 0.307535, 1, 0, 0.315998,-0.0396145) , 
3, 0.209998, 1, 0, 0.490747,-0.00910023)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.449076,-0.0014439) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.55604,-0.0814361) , 
1, 5.24506, 1, 0, 0.459988,-0.0274964) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.28368,2.13244) , 
0, 2792.91, 1, 0, 0.488692,-0.0164073)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.52778,-0.00532492) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.66875,-0.0870895) , 
1, 4.58022, 1, 0, 0.585033,-0.084427) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.08633,0.128942) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.422566,0.000217431) , 
3, 0.108976, 1, 0, 0.451684,0.0128586) , 
3, 0.0864026, 1, 0, 0.486308,-0.0124017)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.379596,-0.00480864) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.890156,0.0399002) , 
0, 1541.44, 1, 0, 0.457422,0.000458634) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.958297,-0.00668724) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.673291,-0.289903) , 
3, 0.18348, 1, 0, 0.856233,-0.0956876) , 
0, 2374.82, 1, 0, 0.494324,-0.00843795)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.33556,-0.0076508) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.803212,0.0190718) , 
0, 1170.75, 1, 0, 0.491157,-0.00164423) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.61206,-0.113493) , 
1, 5.84899, 1, 0, 0.498709,-0.0160853)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.681076,0.00411716) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.808936,0.0530637) , 
3, 0.0749884, 1, 0, 0.733769,0.0727518) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.361027,0.000884959) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.664032,-0.115813) , 
0, 2232.77, 1, 0, 0.382321,-0.0109793) , 
3, 0.148133, 1, 0, 0.501371,0.0173839)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.567561,-0.039678) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.978351,0.0347846) , 
1, 4.65094, 1, 0, 0.671911,-0.0738281) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.118711,-0.0222628) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.523929,0.015234) , 
0, 570.157, 1, 0, 0.449442,0.0320116) , 
2, 0.00922692, 1, 0, 0.510417,0.00300258)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.612128,0.0439939) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.842535,0.00502979) , 
1, 3.97073, 1, 0, 0.747344,0.0762786) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.28322,0.0188749) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.573011,-0.0157374) , 
1, 3.14728, 1, 0, 0.450234,-0.00475322) , 
3, 0.111131, 1, 0, 0.532173,0.0175944)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.589877,-0.00356996) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.229297,-0.0455019) , 
3, 0.360906, 1, 0, 0.54028,-0.0327908) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.192064,0.0285757) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.228411,-0.00952261) , 
1, 2.58231, 1, 0, 0.208887,0.0190297) , 
3, 0.45678, 1, 0, 0.47,-0.021801)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.922031,0.0691629) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.473732,0.00508672) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.694972,-0.0707232) , 
1, 5.74674, 1, 0, 0.487919,0.00622583) , 
3, 0.0246877, 1, 0, 0.508468,0.0157429)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.884658,0.0248889) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.596344,-0.0827454) , 
2, 0.00315123, 1, 0, 0.700008,-0.101207) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.180377,-0.0177963) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.601637,0.00725475) , 
0, 709.818, 1, 0, 0.451866,-0.0049316) , 
2, 0.00555045, 1, 0, 0.487218,-0.0186477)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.433318,0.00600885) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.910389,0.0463094) , 
1, 4.55592, 1, 0, 0.518555,0.0378759) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.881932,-4.68395) , 
0, 2754.58, 1, 0, 0.542078,0.027873)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.445939,0.00029267) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.602157,-0.0576496) , 
1, 5.14917, 1, 0, 0.462497,-0.0168614) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.09815,0.183643) , 
0, 2674.04, 1, 0, 0.492539,0.00731017)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.329953,0.00383624) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.626231,-0.0206265) , 
0, 990.898, 1, 0, 0.464499,-0.0206828) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.982787,0.119884) , 
0, 2593.53, 1, 0, 0.495778,-0.00291745)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.412432,-0.004064) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.457897,-0.0783196) , 
1, 4.97356, 1, 0, 0.415419,-0.0303503) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.967418,0.0436073) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.873659,0.0585376) , 
2, 0.00917652, 1, 0, 0.915342,0.129766) , 
0, 1885.73, 1, 0, 0.493058,-0.00548372)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.589364,-0.0287504) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.412431,0.00231156) , 
2, 0.00925074, 1, 0, 0.460914,-0.0153338) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.834215,0.0180513) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.03215,0.113558) , 
3, 0.104613, 1, 0, 0.913255,0.140739) , 
1, 5.50545, 1, 0, 0.499859,-0.00189622)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.455696,-0.00241195) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.623239,-0.0578344) , 
1, 5.41863, 1, 0, 0.46618,-0.0170051) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.30592,0.209148) , 
0, 2721.53, 1, 0, 0.495584,0.00416243)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.332697,-0.0559298) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.247341,0.000984786) , 
2, 0.0037003, 1, 0, 0.254452,-0.0152677) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.637963,0.100442) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.750192,0.0177024) , 
1, 3.33042, 1, 0, 0.74271,0.0755118) , 
1, 3.20449, 1, 0, 0.537972,0.0374458)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.123372,-0.0415822) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.507649,-0.000293436) , 
0, 527.881, 1, 0, 0.48408,-0.00907371) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.00128,0.114847) , 
0, 2754.56, 1, 0, 0.508555,0.00214277)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.157407,-0.0442458) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.718731,0.00251247) , 
0, 647.03, 1, 0, 0.586815,-0.0334266) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.690408,0.0612115) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.234314,0.000288596) , 
3, 0.316236, 1, 0, 0.292578,0.0295105) , 
3, 0.271302, 1, 0, 0.469728,-0.00838165)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.241416,0.0814228) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.50767,-0.00150301) , 
0, 554.807, 1, 0, 0.489142,0.00881124) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.99748,0.1156) , 
0, 2721.51, 1, 0, 0.513822,0.0201419)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.314399,0.00157028) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.643736,-0.0242757) , 
0, 1050.76, 1, 0, 0.449605,-0.02497) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.05671,0.105804) , 
1, 5.64925, 1, 0, 0.480879,-0.0110536)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.565939,-0.0560018) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.458336,-0.000136826) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.956051,0.0648269) , 
1, 5.38498, 1, 0, 0.500602,0.0114436) , 
3, 0.0124176, 1, 0, 0.503103,0.004839)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.515746,-0.0329673) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.36953,-0.00292869) , 
2, 0.012951, 1, 0, 0.425074,-0.04366) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.07822,0.113373) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.837263,-0.0106566) , 
0, 2082.4, 1, 0, 0.92036,0.0920216) , 
1, 5.03095, 1, 0, 0.481895,-0.028094)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.812879,0.0459537) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.469011,-3.45874e-05) , 
3, 0.0371153, 1, 0, 0.496498,0.0123878) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.08209,0.153152) , 
0, 2700.82, 1, 0, 0.52365,0.0232622)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.13623,0.175404) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.606362,0.00150993) , 
2, 0.00267031, 1, 0, 0.647124,0.0306145) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.345608,-0.0197225) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.322465,-0.000376539) , 
2, 0.0446002, 1, 0, 0.335739,-0.0409653) , 
2, 0.0166417, 1, 0, 0.467708,-0.0106289)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.592077,-0.0693598) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.408797,-0.00265266) , 
2, 0.00553606, 1, 0, 0.433443,-0.0273857) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.48324,0.390745) , 
0, 2619.31, 1, 0, 0.471026,-0.00328105)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.308919,-0.00638449) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.828117,0.0214154) , 
1, 3.7674, 1, 0, 0.487417,0.00559725) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.670326,-0.0686264) , 
1, 5.97256, 1, 0, 0.497767,-0.00386908)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.355887,0.0130097) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.649267,-0.0148907) , 
1, 3.64823, 1, 0, 0.477156,0.0078331) , 
NN(
0, 
0, 
3, 0.127124, 1, -99, 1.01686,0.0829561) , 
1, 5.35285, 1, 0, 0.525632,0.0207217)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.369429,-0.0166776) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.854686,0.0132226) , 
1, 3.81596, 1, 0, 0.605085,-0.0192167) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72857,0.0516626) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289474,0.00940101) , 
3, 0.316588, 1, 0, 0.36182,0.0516743) , 
3, 0.271624, 1, 0, 0.515031,0.00702641)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.456781,0.00553712) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.740764,-0.0349975) , 
1, 5.1589, 1, 0, 0.481723,0.00924117) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.11545,0.202948) , 
0, 2506.57, 1, 0, 0.516947,0.0199186)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.472813,-0.00286134) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.690521,-0.0489674) , 
1, 3.97432, 1, 0, 0.598889,-0.0753291) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.392341,-0.00532953) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.24528,0.31508) , 
1, 5.43997, 1, 0, 0.431498,-0.00192926) , 
3, 0.0741091, 1, 0, 0.469606,-0.0186394)    );
   return;
};

// Clean up
inline void ReadBDT-0.4.6_fold4::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadBDT-0.4.6_fold4::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
