// Class: ReadBDT-0.4.6_fold10
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT-0.4.6_fold10
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.32/00       [401408]
Creator        : abennett
Date           : Thu Aug 22 16:00:10 2024
Host           : Linux 6772f6b99311 6.5.0-1022-azure #23~22.04.1-Ubuntu SMP Thu May 9 17:59:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /gluster/home/abennett/BDT_training
Training events: 19611
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "125" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "3%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "80" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e-01" [Learning rate for BoostType=Grad algorithm]
UseNvars: "2" [Size of the subset of variables used with RandomisedTree option]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "sdivsqrtsplusb" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 4
mjj                           mjj                           mjj                           m_{jj}                        GeV                               'D'    [500.083496094,7102.28710938]
JetGap                        JetGap                        JetGap                        #Delta y_{jj}                                                   'D'    [0.0204434599727,8.30311965942]
PtBalance                     PtBalance                     PtBalance                     pT_{balance}                                                    'D'    [1.2169821817e-09,0.149861991405]
centrality                    centrality                    centrality                    #xi(Z)                                                          'D'    [5.42057250641e-06,0.999970436096]
NSpec 1
eventNumber                   eventNumber                   eventNumber                   I                                                               'F'    [703,684984192]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new BDT-0.4.6_fold10Node

#ifndef BDT-0.4.6_fold10Node__def
#define BDT-0.4.6_fold10Node__def

class BDT-0.4.6_fold10Node {

public:

   // constructor of an essentially "empty" node floating in space
   BDT-0.4.6_fold10Node ( BDT-0.4.6_fold10Node* left,BDT-0.4.6_fold10Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT-0.4.6_fold10Node();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT-0.4.6_fold10Node* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT-0.4.6_fold10Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT-0.4.6_fold10Node*   fLeft;     // pointer to the left daughter node
   BDT-0.4.6_fold10Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   BDT-0.4.6_fold10Node::~BDT-0.4.6_fold10Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool BDT-0.4.6_fold10Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool BDT-0.4.6_fold10Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT-0.4.6_fold10 : public IClassifierReader {

 public:

   // constructor
   ReadBDT-0.4.6_fold10( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDT-0.4.6_fold10" ),
        fNvars( 4 )
   {
      // the training input variables
      const char* inputVars[] = { "mjj", "JetGap", "PtBalance", "centrality" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'D';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT-0.4.6_fold10() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[4];
   double fVmax[4];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[4];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT-0.4.6_fold10Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT-0.4.6_fold10::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT-0.4.6_fold10Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT-0.4.6_fold10Node*)current->GetRight();
         else current=(BDT-0.4.6_fold10Node*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
}

void ReadBDT-0.4.6_fold10::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.371401,-0.0257198) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.120977,-0.0758047) , 
3, 0.432003, 1, 0, 0.286651,-0.213349) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.666493,0.0332987) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.11274,0.122549) , 
0, 1901.92, 1, 0, 0.774166,0.274166) , 
0, 907.648, 1, 0, 0.524477,0.0244772)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.195541,-0.0565314) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.401678,-0.0223258) , 
0, 872.797, 1, 0, 0.245861,-0.2403) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.897829,0.0745926) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.567671,0.0106773) , 
2, 0.0147631, 1, 0, 0.715119,0.194891) , 
1, 3.19952, 1, 0, 0.500321,-0.00431357)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.181506,-0.0558136) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.481811,-0.00398475) , 
1, 2.83718, 1, 0, 0.354122,-0.128997) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.466223,-0.0107321) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.89628,0.0685464) , 
1, 3.30557, 1, 0, 0.850123,0.2949) , 
0, 1294.26, 1, 0, 0.502686,-0.00203041)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.464459,-0.0034697) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.22785,-0.0464245) , 
3, 0.283866, 1, 0, 0.347229,-0.121764) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.25231,0.136576) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.738268,0.0348554) , 
2, 0.00551478, 1, 0, 0.80096,0.22879) , 
1, 3.84036, 1, 0, 0.514098,0.00715964)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.619593,0.0255061) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304892,-0.0318131) , 
3, 0.111116, 1, 0, 0.361108,-0.105333) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.938232,0.0703487) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.526298,-0.0145997) , 
3, 0.317842, 1, 0, 0.886012,0.282029) , 
1, 4.09505, 1, 0, 0.515086,0.00829783)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.43696,7.54776e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.197522,-0.0472231) , 
2, 0.00909973, 1, 0, 0.255905,-0.173085) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601675,0.0126396) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.883781,0.0539386) , 
0, 1237.4, 1, 0, 0.77194,0.173554) , 
1, 3.457, 1, 0, 0.496981,-0.0111456)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.218263,-0.0399685) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.466461,0.00407728) , 
0, 753.584, 1, 0, 0.249377,-0.164706) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.799018,0.0423742) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.384568,-0.0249185) , 
3, 0.320994, 1, 0, 0.703117,0.123312) , 
0, 826.118, 1, 0, 0.502162,-0.00424729)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.232589,-0.0403248) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.822761,0.0446605) , 
1, 3.03072, 1, 0, 0.663112,0.0953272) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.443325,-0.00691795) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.259055,-0.0416165) , 
2, 0.0164234, 1, 0, 0.336621,-0.127446) , 
3, 0.185189, 1, 0, 0.476668,-0.0318887)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.347795,-0.00819987) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.181566,-0.0419212) , 
2, 0.0112929, 1, 0, 0.223103,-0.155311) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.723314,0.0313247) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.4656,-0.0156518) , 
2, 0.025887, 1, 0, 0.635898,0.0692415) , 
0, 720.447, 1, 0, 0.488793,-0.0107805)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0761683,-0.0617798) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.234944,-0.0294258) , 
1, 1.53882, 1, 0, 0.200435,-0.166784) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.932412,0.0643168) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.537599,-0.00201344) , 
2, 0.00922692, 1, 0, 0.637586,0.0629129) , 
1, 2.7966, 1, 0, 0.497653,-0.0106134)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.94008,0.075176) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.563495,0.00685193) , 
2, 0.00555045, 1, 0, 0.619794,0.0729319) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.290829,-0.0237014) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.145747,-0.0480643) , 
3, 0.581819, 1, 0, 0.216144,-0.162069) , 
3, 0.394976, 1, 0, 0.51407,0.0113804)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58934,0.0194589) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.293119,-0.0281986) , 
2, 0.00925074, 1, 0, 0.348596,-0.0887977) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.963017,0.0633383) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.422009,-0.0278264) , 
3, 0.332205, 1, 0, 0.873261,0.189977) , 
0, 1315.19, 1, 0, 0.497791,-0.00952458)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.320718,-0.0152844) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.737314,0.0207666) , 
1, 3.16289, 1, 0, 0.588083,0.0314074) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.181613,-0.0310646) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.197011,-0.067299) , 
1, 3.69157, 1, 0, 0.184665,-0.170792) , 
3, 0.407275, 1, 0, 0.486343,-0.019586)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48579,0.0040512) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.22242,-0.0282825) , 
2, 0.00727978, 1, 0, 0.263207,-0.102321) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636849,0.00652755) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.913096,0.0442669) , 
0, 1562.52, 1, 0, 0.760999,0.0881443) , 
1, 3.42449, 1, 0, 0.496084,-0.0132174)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527392,0.000784108) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.292698,-0.02989) , 
2, 0.0314525, 1, 0, 0.446613,-0.0428803) , 
NN(
0, 
0, 
0, 3237.05, 1, -99, 1.08695,0.0924677) , 
0, 2513.05, 1, 0, 0.490514,-0.0183939)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.340662,-0.00968672) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.327151,-0.0562592) , 
0, 1079.66, 1, 0, 0.33938,-0.0631118) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.901086,0.0461132) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.459427,-0.0156197) , 
3, 0.308595, 1, 0, 0.811741,0.122811) , 
0, 1152.15, 1, 0, 0.513542,0.00543879)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.431614,-0.00596323) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.878485,0.0351694) , 
0, 1315.22, 1, 0, 0.593968,0.0270101) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.14148,-0.0445154) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.261007,-0.00540019) , 
3, 0.796871, 1, 0, 0.157509,-0.164176) , 
3, 0.432101, 1, 0, 0.498293,-0.0148991)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.234034,-0.02104) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.692771,0.0180053) , 
0, 661.14, 1, 0, 0.58839,0.0361908) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.344277,-0.0121085) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0971776,-0.0462187) , 
2, 0.00956474, 1, 0, 0.148401,-0.154302) , 
3, 0.530599, 1, 0, 0.518192,0.0057984)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0963986,-0.0469066) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436919,-0.00582811) , 
1, 1.8724, 1, 0, 0.391168,-0.0465828) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556853,-0.0237007) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.02151,0.0685535) , 
1, 4.29316, 1, 0, 0.905757,0.125445) , 
0, 1646.53, 1, 0, 0.489324,-0.0137694)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.13663,-0.0434425) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.74583,0.029673) , 
1, 2.03563, 1, 0, 0.668392,0.0767958) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.26276,-0.0237448) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.808752,0.0207433) , 
0, 1396.7, 1, 0, 0.361868,-0.0691224) , 
2, 0.0166417, 1, 0, 0.495431,-0.00554062)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.780859,0.0378509) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.599815,-0.0118281) , 
2, 0.00643426, 1, 0, 0.744627,0.10076) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.425577,-0.00523182) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.551004,-0.0894276) , 
1, 5.75808, 1, 0, 0.435561,-0.0404954) , 
2, 0.00734121, 1, 0, 0.494516,-0.0135505)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.17609,-0.0298246) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.573102,-0.00220448) , 
1, 2.74171, 1, 0, 0.444775,-0.0444653) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.19446,0.141988) , 
0, 2593.56, 1, 0, 0.478021,-0.027261)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.13348,-0.0414691) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.67588,0.0206589) , 
1, 1.66844, 1, 0, 0.646004,0.0662571) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.192816,-0.019536) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.232402,-0.0604567) , 
1, 3.94188, 1, 0, 0.199634,-0.110672) , 
3, 0.357936, 1, 0, 0.504322,0.0100979)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.205169,-0.0212172) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.651582,0.00860113) , 
1, 3.03129, 1, 0, 0.453249,-0.0172298) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.14209,0.122978) , 
1, 5.56421, 1, 0, 0.495799,0.000889471)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.298387,-0.0200752) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.09696,0.104811) , 
1, 2.80857, 1, 0, 0.829948,0.176143) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.537402,0.00403646) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.309194,-0.029431) , 
2, 0.0373002, 1, 0, 0.458658,-0.0288563) , 
2, 0.00740059, 1, 0, 0.524587,0.00754499)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.688689,0.0142032) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.412021,-0.00891503) , 
2, 0.0117907, 1, 0, 0.517807,-0.00256959) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.226638,-0.0440397) , 
2, 0.0869065, 1, 0, 0.495122,-0.0166859)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.590589,0.0071162) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.140062,-0.0328758) , 
3, 0.530817, 1, 0, 0.523037,0.00526098) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.228205,-0.0427986) , 
2, 0.0808834, 1, 0, 0.496046,-0.0113455)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.428258,-0.00543286) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.592824,-0.0696024) , 
1, 5.12285, 1, 0, 0.443385,-0.0386889) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.1238,0.133153) , 
0, 2537.8, 1, 0, 0.477063,-0.0253847)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.142032,-0.0280074) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.342637,0.00614732) , 
0, 677.418, 1, 0, 0.231154,-0.0417805) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.77214,0.0257272) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.367574,-0.0067077) , 
3, 0.368782, 1, 0, 0.700373,0.0717761) , 
1, 2.87458, 1, 0, 0.534584,0.0316532)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533033,0.00968033) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.763211,-0.0623535) , 
0, 2304.95, 1, 0, 0.560788,0.0190861) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.227932,-0.043365) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.306143,-0.013712) , 
2, 0.0606979, 1, 0, 0.279705,-0.092316) , 
2, 0.04964, 1, 0, 0.498755,-0.00549938)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.776942,0.0784959) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.865225,0.013399) , 
0, 983.437, 1, 0, 0.835557,0.132631) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.690154,0.0145626) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.360677,-0.0152562) , 
3, 0.111286, 1, 0, 0.447799,-0.0290407) , 
2, 0.0073963, 1, 0, 0.518024,0.00023878)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.210972,-0.0280816) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.865883,0.044992) , 
1, 2.46641, 1, 0, 0.715709,0.0836963) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.359882,-0.00521245) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.50587,-0.0886178) , 
1, 5.13326, 1, 0, 0.377422,-0.050972) , 
2, 0.0129177, 1, 0, 0.491895,-0.00540139)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.732926,-0.00440088) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.92373,0.0839281) , 
2, 0.0022826, 1, 0, 0.831236,0.135707) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0786462,-0.0406202) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.522729,-0.00647395) , 
1, 1.90538, 1, 0, 0.465835,-0.0376384) , 
2, 0.0037003, 1, 0, 0.49084,-0.0257763)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.416705,-0.00398907) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.854391,0.025008) , 
0, 1072.24, 1, 0, 0.639475,0.0300682) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.270358,-0.00997955) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.441862,-0.047414) , 
1, 4.42302, 1, 0, 0.294288,-0.0573979) , 
3, 0.246949, 1, 0, 0.487439,-0.00845569)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.710618,0.0299526) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.728505,-0.0473425) , 
1, 5.14197, 1, 0, 0.714829,0.0582331) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.305179,-0.0187324) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.881649,0.0365088) , 
1, 5.07974, 1, 0, 0.34288,-0.058315) , 
3, 0.160572, 1, 0, 0.48348,-0.0142587)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.751474,0.0437609) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380906,-0.00830077) , 
3, 0.0371725, 1, 0, 0.407787,-0.0180725) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.892688,0.0215627) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.04888,0.0934787) , 
3, 0.202595, 1, 0, 0.925905,0.111463) , 
1, 4.6106, 1, 0, 0.503902,0.00595721)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0227169,-0.0567195) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.265895,-0.0115683) , 
1, 1.54154, 1, 0, 0.230727,-0.0613482) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.25035,0.198109) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.63183,0.00211542) , 
2, 0.00553615, 1, 0, 0.700554,0.0466352) , 
1, 3.16371, 1, 0, 0.489776,-0.00180913)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491098,-0.0214099) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.377526,0.00278232) , 
2, 0.0258602, 1, 0, 0.447794,-0.0437513) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.06097,0.092339) , 
1, 5.89572, 1, 0, 0.474735,-0.0341102)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.673065,0.0149411) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.261855,-0.0135012) , 
3, 0.308637, 1, 0, 0.540469,0.0201218) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.190469,-0.0511424) , 
2, 0.0978994, 1, 0, 0.519047,0.00746235)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
1, 3.84401, 1, -99, 0.852059,0.0626589) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.387713,-0.00561585) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.00827,0.0698918) , 
0, 1871.8, 1, 0, 0.457743,-0.000624065) , 
2, 0.00555045, 1, 0, 0.506627,0.0204449)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.176876,-0.00982044) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.187266,-0.0381576) , 
0, 872.157, 1, 0, 0.179616,-0.0643702) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.521966,0.0192543) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.761726,-0.0086429) , 
0, 1216.78, 1, 0, 0.632797,0.0319293) , 
1, 2.57682, 1, 0, 0.514744,0.00684333)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.290228,-0.0238859) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.201201,-0.00504113) , 
3, 0.345686, 1, 0, 0.253194,-0.0646157) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.87838,0.0353049) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.553863,-0.00620626) , 
2, 0.0146059, 1, 0, 0.697525,0.0248166) , 
0, 867.27, 1, 0, 0.483001,-0.0183615)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.485555,-0.000881723) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.196689,-0.045102) , 
2, 0.0904238, 1, 0, 0.462435,-0.016628) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.1857,0.203846) , 
0, 2619.31, 1, 0, 0.495046,-0.00370438)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.375552,0.0157867) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.651576,-0.0263071) , 
0, 637.972, 1, 0, 0.61443,-0.0549796) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.688654,0.0439206) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421537,0.000238189) , 
2, 0.0145327, 1, 0, 0.450497,0.0170812) , 
2, 0.0111009, 1, 0, 0.508389,-0.00836689)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.612537,-0.00352678) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.292192,-0.0177583) , 
3, 0.222284, 1, 0, 0.445771,-0.0387924) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.739573,-0.0802736) , 
1, 5.86178, 1, 0, 0.462549,-0.0449014)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.289672,-0.00398945) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.452427,-0.0329083) , 
1, 3.73033, 1, 0, 0.331361,-0.047103) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.960717,0.051766) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.586606,-0.0175596) , 
2, 0.0254968, 1, 0, 0.840507,0.0507042) , 
0, 1315.19, 1, 0, 0.479283,-0.018687)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.183573,-0.00378634) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.195201,-0.0207993) , 
1, 2.08476, 1, 0, 0.187921,-0.0354587) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.00312,0.0806054) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.569226,0.0107121) , 
2, 0.00550591, 1, 0, 0.625868,0.0548637) , 
1, 2.44399, 1, 0, 0.523754,0.0338037)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0974662,-0.0236924) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.580972,0.118167) , 
1, 1.87791, 1, 0, 0.318237,0.172611) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560139,0.00565085) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.267293,-0.0292481) , 
2, 0.0942051, 1, 0, 0.542016,0.0108845) , 
0, 571.779, 1, 0, 0.525955,0.0224915)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.226155,-0.0104698) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304071,-0.0388824) , 
1, 3.18611, 1, 0, 0.259283,-0.0915284) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.766502,-0.00567007) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.605348,0.052428) , 
3, 0.295902, 1, 0, 0.733992,0.0336139) , 
0, 940.707, 1, 0, 0.478582,-0.033717)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.412451,-0.0115713) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.942872,0.0415538) , 
1, 4.92581, 1, 0, 0.468438,-0.0273834) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.64867,-0.110025) , 
1, 5.95125, 1, 0, 0.479087,-0.0390478)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.405552,-0.0349688) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.321755,-0.00690294) , 
3, 0.0616701, 1, 0, 0.334044,-0.0425218) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.842154,0.0327281) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.836277,-0.0304463) , 
0, 2030.34, 1, 0, 0.839528,0.0337702) , 
0, 1315.17, 1, 0, 0.480962,-0.0203477)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0590604,-0.0408357) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.57092,0.00724667) , 
1, 1.56244, 1, 0, 0.527835,0.0146476) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.511976,-0.169948) , 
1, 5.97259, 1, 0, 0.526861,-0.00830601)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.350362,0.00133628) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.442969,-0.0315977) , 
0, 1068.7, 1, 0, 0.365847,-0.0172004) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.924211,0.0386573) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.281832,-0.0593726) , 
3, 0.382656, 1, 0, 0.841673,0.0489522) , 
0, 1294.22, 1, 0, 0.50594,0.00227634)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561843,-0.044551) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.00161,0.0554692) , 
1, 4.69508, 1, 0, 0.664216,-0.0952094) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.400745,0.0108425) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.751428,-0.0213936) , 
0, 1503.31, 1, 0, 0.48861,0.0161849) , 
2, 0.00555045, 1, 0, 0.515121,-0.000632035)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.128349,-0.0425824) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.283711,-0.00631599) , 
0, 549.911, 1, 0, 0.254515,-0.0452285) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.797652,0.0752341) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.759853,0.0100159) , 
1, 3.52959, 1, 0, 0.762506,0.0498942) , 
1, 3.35924, 1, 0, 0.511616,0.00291436)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.59031,-0.0258945) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.418271,0.00233311) , 
2, 0.00740059, 1, 0, 0.455569,-0.0103835) , 
NN(
0, 
0, 
3, 0.160534, 1, -99, 0.991014,0.0616977) , 
1, 5.13321, 1, 0, 0.514485,0.00492488)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.640179,0.0496481) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336436,0.00332607) , 
3, 0.0370185, 1, 0, 0.353328,0.0222824) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.91084,0.0140795) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.567066,-0.025478) , 
2, 0.011083, 1, 0, 0.673674,-0.0570117) , 
1, 3.72415, 1, 0, 0.495048,-0.0127968)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
0, 822.273, 1, -99, 0.950362,0.0934325) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.409954,-0.00414946) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.00747,0.068038) , 
0, 2016.17, 1, 0, 0.468491,-0.00136026) , 
2, 0.00555045, 1, 0, 0.521072,0.0236411)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.861021,0.0613225) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.585769,-0.0299954) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.459574,0.00270725) , 
3, 0.0729111, 1, 0, 0.479796,-0.00744762) , 
3, 0.0247163, 1, 0, 0.500807,0.00307497)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.833142,0.0396327) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.482987,0.00200241) , 
3, 0.16044, 1, 0, 0.623981,0.0493829) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.377678,-0.0435383) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.360073,-0.0018055) , 
3, 0.0617948, 1, 0, 0.363277,-0.0390323) , 
2, 0.0314525, 1, 0, 0.534236,0.0189467)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.635726,-0.00145529) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.462318,0.0293233) , 
3, 0.288079, 1, 0, 0.594105,0.02087) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.137058,-0.0019618) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.134021,-0.0506064) , 
1, 2.86242, 1, 0, 0.135879,-0.0774972) , 
3, 0.555578, 1, 0, 0.527673,0.00660915)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.727511,0.0146398) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.854554,0.0791847) , 
3, 0.115647, 1, 0, 0.741594,0.0707913) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.203221,-0.00052861) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.446754,-0.021214) , 
1, 2.70879, 1, 0, 0.361996,-0.0510814) , 
3, 0.135785, 1, 0, 0.486063,-0.0112488)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.844188,0.0395987) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.537398,-0.0497676) , 
3, 0.0192784, 1, 0, 0.607287,-0.0930109) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.149825,-0.0295581) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.518606,0.00506381) , 
0, 581.615, 1, 0, 0.463956,-0.000212006) , 
3, 0.0742032, 1, 0, 0.494171,-0.0197744)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.62923,-0.0649744) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.596451,-0.0112519) , 
2, 0.00219276, 1, 0, 0.599608,-0.0460534) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.230134,-0.00710133) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.72832,0.0253605) , 
1, 3.59938, 1, 0, 0.421402,0.0225112) , 
2, 0.0148012, 1, 0, 0.499378,-0.00749013)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.238303,0.00103583) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.315528,-0.0308782) , 
1, 3.33277, 1, 0, 0.256241,-0.0296651) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.765186,0.0250873) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.175064,-0.0275622) , 
3, 0.530226, 1, 0, 0.690791,0.0571303) , 
0, 779.553, 1, 0, 0.533751,0.0257637)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.627292,0.00520047) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.37384,0.878652) , 
1, 4.21881, 1, 0, 0.840989,0.126611) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.278855,0.015566) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.58012,-0.00664768) , 
0, 786.741, 1, 0, 0.473313,0.00222331) , 
2, 0.00555045, 1, 0, 0.518206,0.0174108)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.741284,0.0294603) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.443798,-0.00727426) , 
3, 0.0494645, 1, 0, 0.476657,-0.0115666) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.14299,0.163938) , 
1, 5.85339, 1, 0, 0.498731,-0.00278444)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.964883,0.101627) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.588042,-0.0515382) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.44685,0.00284856) , 
2, 0.0073103, 1, 0, 0.467751,-0.0117379) , 
2, 0.0037003, 1, 0, 0.496449,0.00176462)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
2, 0.0027402, 1, -99, 0.855421,0.0511941) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.377067,0.00350863) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.674305,-0.0521034) , 
1, 4.44828, 1, 0, 0.45154,-0.0245264) , 
2, 0.00555045, 1, 0, 0.501141,-0.00740727)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491825,0.080358) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.77737,0.0144675) , 
0, 643.377, 1, 0, 0.748698,0.0727096) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.444118,-0.0254661) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.253506,0.00351427) , 
3, 0.378219, 1, 0, 0.362425,-0.047881) , 
3, 0.160541, 1, 0, 0.508844,-0.00217054)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.220739,-0.012496) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.695822,0.0204314) , 
1, 3.05292, 1, 0, 0.467476,0.0172441) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57446,-0.0653184) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.903084,-0.01353) , 
0, 1950.22, 1, 0, 0.777132,-0.0866871) , 
1, 5.02273, 1, 0, 0.51805,0.000269728)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.151098,-0.0383764) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.398894,0.0184504) , 
0, 554.333, 1, 0, 0.350389,0.0291884) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.410519,-0.0233501) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.761877,-0.00600178) , 
0, 1140.17, 1, 0, 0.688011,-0.0315539) , 
0, 989.136, 1, 0, 0.520327,-0.0013855)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
3, 0.0196443, 1, -99, 0.988525,0.0906411) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.548795,-0.0455791) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.462902,-3.8273e-05) , 
3, 0.072734, 1, 0, 0.475026,-0.0195925) , 
3, 0.0370412, 1, 0, 0.50996,-0.000703307)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436417,0.00322258) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.00321,0.0842354) , 
1, 4.65938, 1, 0, 0.468111,0.0206731) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.17306,0.473648) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.678294,-0.0694564) , 
2, 0.00728481, 1, 0, 0.791232,-0.0799857) , 
1, 5.031, 1, 0, 0.51096,0.00732479)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.619161,-0.0303052) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.683678,0.0225973) , 
3, 0.0519188, 1, 0, 0.664551,0.0245373) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.386508,-0.058737) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.285332,-0.00928348) , 
2, 0.00365131, 1, 0, 0.293384,-0.0447886) , 
3, 0.246945, 1, 0, 0.496609,-0.0068307)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.996587,0.10291) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.405978,-0.000497009) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.676462,-0.0493286) , 
1, 4.59775, 1, 0, 0.467509,-0.0301909) , 
2, 0.0037003, 1, 0, 0.498376,-0.0159111)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.291563,-0.0128714) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.854985,0.0383066) , 
1, 3.09211, 1, 0, 0.625451,0.044637) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.296219,-0.0282657) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.390954,0.0127548) , 
2, 0.0634285, 1, 0, 0.333483,-0.0468934) , 
2, 0.0332489, 1, 0, 0.525863,0.0134168)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.350126,-0.00926983) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.849369,0.0242373) , 
1, 4.01667, 1, 0, 0.482303,-0.00697134) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.605433,-0.0825357) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.05145,0.125404) , 
0, 2627.42, 1, 0, 0.76615,-0.106621) , 
1, 5.49141, 1, 0, 0.511464,-0.0172088)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.680542,-0.0731533) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.551437,-0.00433796) , 
2, 0.00444667, 1, 0, 0.573812,-0.0360571) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.237553,0.000515998) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.815886,0.0555144) , 
1, 3.60781, 1, 0, 0.43726,0.075766) , 
2, 0.0257393, 1, 0, 0.52315,0.00543008)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.451302,-0.00259795) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.578897,-0.0840819) , 
1, 5.15887, 1, 0, 0.461894,-0.0275195) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.29231,0.372497) , 
0, 2432.57, 1, 0, 0.503568,-0.00859807)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.852553,0.0721676) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.360831,-0.00865042) , 
3, 0.0247129, 1, 0, 0.380285,-0.0186548) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.27455,0.809538) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.764096,0.00520635) , 
2, 0.00735304, 1, 0, 0.861724,0.0687345) , 
1, 4.33015, 1, 0, 0.491897,0.00160455)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.819824,0.0333194) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436262,-0.00400593) , 
3, 0.111094, 1, 0, 0.53724,0.0160736) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.187338,-0.0453739) , 
2, 0.094934, 1, 0, 0.510896,0.00298242)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.141958,-0.0184235) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.606618,0.00687583) , 
1, 2.23262, 1, 0, 0.506991,0.00670242) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.788171,-0.0979717) , 
1, 5.9936, 1, 0, 0.521196,0.000112188)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535098,-0.0211922) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.989453,0.0566505) , 
0, 1788.45, 1, 0, 0.651017,-0.0385329) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514324,0.022774) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.149894,-0.0158349) , 
3, 0.524411, 1, 0, 0.390296,0.0368439) , 
3, 0.197503, 1, 0, 0.516051,0.000487093)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.381953,-0.00986774) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.964686,0.0599319) , 
1, 4.53627, 1, 0, 0.447194,-0.0146103) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.630281,-0.135207) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.97598,-0.0319687) , 
0, 2769.44, 1, 0, 0.807419,-0.125211) , 
0, 2293.27, 1, 0, 0.480654,-0.0248836)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
3, 0.270059, 1, -99, 0.980942,0.112069) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.337095,-0.00184146) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.685191,-0.0340447) , 
1, 4.21297, 1, 0, 0.439926,-0.0313082) , 
2, 0.00554722, 1, 0, 0.495291,-0.00325399)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.271965,-0.0124943) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.725395,0.0095756) , 
0, 933.357, 1, 0, 0.473698,-0.0112841) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.08049,0.142089) , 
1, 5.64448, 1, 0, 0.512289,4.25051e-06)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.05859,0.132214) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.570144,-0.0286172) , 
2, 0.00554148, 1, 0, 0.629538,-0.0608845) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.653276,-0.0441928) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.480503,0.013617) , 
2, 0.00369815, 1, 0, 0.493872,0.0323654) , 
3, 0.0987273, 1, 0, 0.53603,0.0033884)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.680786,0.0524412) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350174,0.0113764) , 
3, 0.0496666, 1, 0, 0.37348,0.0526139) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.727165,-0.0313536) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.231433,-0.0549882) , 
3, 0.364929, 1, 0, 0.651407,-0.103132) , 
1, 3.71626, 1, 0, 0.507141,-0.0222872)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.723195,-0.00827254) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.390359,-0.0996367) , 
3, 0.0449846, 1, 0, 0.599043,-0.130218) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.115485,-0.0279282) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.542987,0.010697) , 
0, 571.795, 1, 0, 0.478002,0.017104) , 
3, 0.0617512, 1, 0, 0.50217,-0.0123117)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.432363,0.00278512) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.728163,-0.0500897) , 
0, 940.707, 1, 0, 0.609183,-0.0566373) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564837,-0.0419359) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.415134,0.0109967) , 
3, 0.0370131, 1, 0, 0.431858,0.0168068) , 
2, 0.0148012, 1, 0, 0.511624,-0.0162306)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.378452,-0.00878974) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.482345,-0.0829445) , 
1, 4.40479, 1, 0, 0.385581,-0.0457449) , 
NN(
0, 
0, 
3, 0.147404, 1, -99, 0.969328,0.054391) , 
1, 4.63215, 1, 0, 0.491011,-0.0183419)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.628983,-0.0577118) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.43652,-0.00157944) , 
2, 0.00555045, 1, 0, 0.462363,-0.0229582) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.745753,-0.119713) , 
1, 5.79929, 1, 0, 0.480641,-0.0320532)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4113,0.00288438) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.990244,0.080259) , 
1, 4.61037, 1, 0, 0.461512,0.0307459) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.877222,-0.0563598) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.600113,-0.0977418) , 
3, 0.256041, 1, 0, 0.818768,-0.0915105) , 
0, 1949.39, 1, 0, 0.513327,0.0130144)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.864431,0.0358194) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.583723,-0.0394757) , 
2, 0.00308263, 1, 0, 0.631177,-0.0783627) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57263,-0.029234) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454739,0.00858474) , 
3, 0.0371119, 1, 0, 0.466627,0.0166505) , 
2, 0.00925074, 1, 0, 0.51416,-0.0107955)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.6747,-0.0423842) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.551244,0.0213903) , 
2, 0.035096, 1, 0, 0.642491,-0.059248) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.949774,0.0962314) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.407172,-0.00811829) , 
3, 0.108976, 1, 0, 0.438048,-0.00992499) , 
3, 0.0864026, 1, 0, 0.487284,-0.0218034)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.217831,0.00620107) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.649299,0.11275) , 
1, 2.98802, 1, 0, 0.296132,0.0958718) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.614097,-0.00413352) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.394816,0.0760491) , 
3, 0.678953, 1, 0, 0.603283,-0.00158309) , 
0, 663.207, 1, 0, 0.542096,0.0178307)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.687249,-0.0864568) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.502427,-0.00509633) , 
2, 0.0030148, 1, 0, 0.515885,-0.0261999) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601148,0.0443139) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.133502,-0.0128932) , 
3, 0.356621, 1, 0, 0.431891,0.0934713) , 
2, 0.0610549, 1, 0, 0.504928,-0.0105891)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.604254,0.0284868) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.282554,0.00491668) , 
2, 0.00924537, 1, 0, 0.353065,0.0365465) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.793053,-0.00281553) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.451987,-0.0416371) , 
3, 0.222905, 1, 0, 0.675756,-0.0578256) , 
1, 3.66865, 1, 0, 0.506142,-0.00822134)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
2, 0.00300408, 1, -99, 0.904953,0.06741) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.388403,0.00560009) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.717397,-0.0296747) , 
1, 4.38273, 1, 0, 0.476211,-0.00624393) , 
2, 0.00553615, 1, 0, 0.529147,0.012526)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0117107,-0.0664292) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0564837,-0.0292116) , 
3, 0.272116, 1, 0, 0.0392387,-0.115423) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.726101,0.0155469) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.429957,-0.00221394) , 
2, 0.0147631, 1, 0, 0.554934,0.0134916) , 
1, 1.58759, 1, 0, 0.511491,0.00263167)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.307134,-0.0764449) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.944564,-0.381118) , 
1, 3.26216, 1, 0, 0.631653,-0.166111) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.347956,-0.00908393) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.819787,0.0103732) , 
1, 4.26249, 1, 0, 0.466309,-0.0178668) , 
2, 0.00369815, 1, 0, 0.47698,-0.0274346)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.283783,-0.00832038) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.77675,0.0187941) , 
1, 3.45502, 1, 0, 0.501462,0.00952425) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.690966,-0.0900915) , 
1, 5.70134, 1, 0, 0.517015,-0.00526136)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.125767,-0.0220102) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.23924,-0.0477207) , 
1, 2.80979, 1, 0, 0.174009,-0.122332) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.516757,-0.00218341) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.982036,0.063752) , 
1, 4.54598, 1, 0, 0.645386,0.0285323) , 
0, 715.058, 1, 0, 0.484255,-0.0230378)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.663462,-0.0250487) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.722183,0.024043) , 
3, 0.0357986, 1, 0, 0.710413,0.0433034) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.235833,0.00353974) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.464866,-0.0372783) , 
1, 3.5001, 1, 0, 0.314792,-0.0400244) , 
3, 0.222329, 1, 0, 0.51598,0.00235072)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.55069,-0.0450437) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.995203,-0.116338) , 
1, 4.81609, 1, 0, 0.64744,-0.102093) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.593531,0.0063999) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.171538,-0.0171921) , 
3, 0.345893, 1, 0, 0.450568,-0.00289959) , 
2, 0.00740059, 1, 0, 0.490972,-0.023257)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.316012,-0.00360223) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.404084,-0.0415685) , 
0, 1009.87, 1, 0, 0.338124,-0.0501158) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.11425,0.131204) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.845964,0.00700783) , 
0, 1482.67, 1, 0, 0.881604,0.0815807) , 
0, 1294.22, 1, 0, 0.489116,-0.0135273)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.131813,-0.0219595) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.744123,0.030408) , 
1, 2.17536, 1, 0, 0.648767,0.0684274) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.253225,-0.00747911) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.518955,-0.0552736) , 
1, 4.45352, 1, 0, 0.310945,-0.061533) , 
2, 0.0332489, 1, 0, 0.531054,0.023143)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.571334,0.00633878) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.636632,-0.101638) , 
1, 4.14616, 1, 0, 0.606751,-0.10587) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.484223,-0.00276371) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.211046,-0.0347269) , 
2, 0.0795102, 1, 0, 0.456302,-0.0199932) , 
3, 0.0493797, 1, 0, 0.479326,-0.0331353)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.744691,0.0160812) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.548619,-0.0210142) , 
3, 0.0468836, 1, 0, 0.582331,-0.0477377) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72016,0.0663046) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.255359,-0.00331453) , 
2, 0.00554722, 1, 0, 0.301227,0.013991) , 
3, 0.271244, 1, 0, 0.472805,-0.0236864)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.390378,-0.0114303) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.924525,0.0245885) , 
0, 1722.75, 1, 0, 0.474487,-0.0262067) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.640167,-0.0847368) , 
1, 5.85578, 1, 0, 0.485231,-0.0369879)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45193,-0.00157795) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.791907,-0.183477) , 
0, 2377.14, 1, 0, 0.469899,-0.0128661) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.0479,0.101623) , 
1, 5.8055, 1, 0, 0.495344,-0.00517443)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.378974,-0.0442453) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.246623,0.00406697) , 
2, 0.00730261, 1, 0, 0.271704,-0.0220545) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.808463,0.00573038) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.651727,0.0473967) , 
3, 0.236448, 1, 0, 0.76481,0.0585561) , 
1, 3.39487, 1, 0, 0.513522,0.0174767)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.280104,-0.00817948) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.66462,0.00910329) , 
1, 3.46003, 1, 0, 0.41455,-0.00623267) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.00634,0.0686869) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.594729,-0.0548589) , 
2, 0.0128471, 1, 0, 0.763548,-0.0737604) , 
1, 4.73408, 1, 0, 0.480153,-0.0189262)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.454557,0.0067519) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.675687,-0.0570984) , 
1, 4.93986, 1, 0, 0.476748,0.00764253) , 
NN(
0, 
0, 
0, 2711.01, 1, -99, 1.01048,0.0784102) , 
1, 5.55259, 1, 0, 0.518067,0.0157989)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.705806,0.00301209) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.914615,0.0901491) , 
3, 0.124354, 1, 0, 0.73173,0.0585971) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.26153,0.0116497) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.541797,-0.0223825) , 
1, 3.30743, 1, 0, 0.3906,-0.0157045) , 
3, 0.148166, 1, 0, 0.516117,0.0116345)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.575767,-0.0626848) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.623657,-0.0311403) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.416163,-0.00305526) , 
2, 0.00912869, 1, 0, 0.469136,-0.0287146) , 
3, 0.0247107, 1, 0, 0.477171,-0.0401816)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.240236,-0.00827809) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.775865,0.0216721) , 
1, 2.81308, 1, 0, 0.635244,0.0425643) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.133836,-0.00797749) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.251368,-0.0316482) , 
1, 3.26418, 1, 0, 0.168313,-0.0478894) , 
3, 0.444434, 1, 0, 0.520549,0.0203455)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.613909,-0.0478671) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.431865,0.00176106) , 
2, 0.00369815, 1, 0, 0.448005,-0.00547431) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.592063,-0.065274) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.995623,0.0443811) , 
0, 2540.42, 1, 0, 0.743083,-0.10851) , 
1, 5.24096, 1, 0, 0.48538,-0.0185251)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.250715,0.00899092) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.972219,0.155971) , 
1, 3.15291, 1, 0, 0.300159,0.0624955) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.66028,-0.0576473) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.688433,-0.00106718) , 
3, 0.0473558, 1, 0, 0.682453,-0.0344166) , 
1, 3.35836, 1, 0, 0.508815,0.00960079)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.386601,-0.0441614) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.777497,-0.014612) , 
1, 3.77357, 1, 0, 0.607605,-0.0915383) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.496146,0.00303155) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.142745,-0.0451281) , 
2, 0.0943028, 1, 0, 0.468009,-0.00249757) , 
3, 0.0493995, 1, 0, 0.488037,-0.0152723)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.678399,0.00855206) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.376601,-0.00962296) , 
3, 0.111116, 1, 0, 0.455218,-0.0160598) , 
NN(
0, 
0, 
3, 0.101071, 1, -99, 1.09051,0.143095) , 
1, 5.38498, 1, 0, 0.506027,0.0010641)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.249822,0.0603391) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.502627,0.00358919) , 
0, 545.811, 1, 0, 0.482507,0.0249819) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.951698,-0.0175316) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.472828,-0.18991) , 
3, 0.160929, 1, 0, 0.741504,-0.17081) , 
0, 2351.99, 1, 0, 0.507145,0.00635607)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.978268,0.0950107) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.655335,0.00903426) , 
3, 0.0198085, 1, 0, 0.675021,0.04115) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.3035,-0.0491656) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.23207,-0.00519077) , 
3, 0.346067, 1, 0, 0.241698,-0.0391067) , 
3, 0.320909, 1, 0, 0.526088,0.0135658)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.07247,0.139928) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.595442,-0.0289123) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.451399,0.00661342) , 
3, 0.0616701, 1, 0, 0.476622,0.00194483) , 
2, 0.00369432, 1, 0, 0.509921,0.0261623)    );
   return;
};

// Clean up
inline void ReadBDT-0.4.6_fold10::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadBDT-0.4.6_fold10::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
