// Class: ReadBDT-0.4.6_fold1
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT-0.4.6_fold1
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.32/00       [401408]
Creator        : abennett
Date           : Thu Aug 22 15:59:46 2024
Host           : Linux 6772f6b99311 6.5.0-1022-azure #23~22.04.1-Ubuntu SMP Thu May 9 17:59:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /gluster/home/abennett/BDT_training
Training events: 17852
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "125" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "3%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "80" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e-01" [Learning rate for BoostType=Grad algorithm]
UseNvars: "2" [Size of the subset of variables used with RandomisedTree option]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "sdivsqrtsplusb" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 4
mjj                           mjj                           mjj                           m_{jj}                        GeV                               'D'    [500.083496094,7102.28710938]
JetGap                        JetGap                        JetGap                        #Delta y_{jj}                                                   'D'    [0.0204434599727,8.30311965942]
PtBalance                     PtBalance                     PtBalance                     pT_{balance}                                                    'D'    [1.2169821817e-09,0.149861991405]
centrality                    centrality                    centrality                    #xi(Z)                                                          'D'    [5.42057250641e-06,0.999970436096]
NSpec 1
eventNumber                   eventNumber                   eventNumber                   I                                                               'F'    [703,684984192]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new BDT-0.4.6_fold1Node

#ifndef BDT-0.4.6_fold1Node__def
#define BDT-0.4.6_fold1Node__def

class BDT-0.4.6_fold1Node {

public:

   // constructor of an essentially "empty" node floating in space
   BDT-0.4.6_fold1Node ( BDT-0.4.6_fold1Node* left,BDT-0.4.6_fold1Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT-0.4.6_fold1Node();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT-0.4.6_fold1Node* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT-0.4.6_fold1Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT-0.4.6_fold1Node*   fLeft;     // pointer to the left daughter node
   BDT-0.4.6_fold1Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   BDT-0.4.6_fold1Node::~BDT-0.4.6_fold1Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool BDT-0.4.6_fold1Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool BDT-0.4.6_fold1Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT-0.4.6_fold1 : public IClassifierReader {

 public:

   // constructor
   ReadBDT-0.4.6_fold1( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDT-0.4.6_fold1" ),
        fNvars( 4 )
   {
      // the training input variables
      const char* inputVars[] = { "mjj", "JetGap", "PtBalance", "centrality" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'D';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT-0.4.6_fold1() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[4];
   double fVmax[4];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[4];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT-0.4.6_fold1Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT-0.4.6_fold1::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT-0.4.6_fold1Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT-0.4.6_fold1Node*)current->GetRight();
         else current=(BDT-0.4.6_fold1Node*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
}

void ReadBDT-0.4.6_fold1::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.118107,-0.0763786) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.315995,-0.0368009) , 
1, 2.29295, 1, 0, 0.227391,-0.272609) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.980981,0.0961963) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564696,0.0129392) , 
2, 0.011083, 1, 0, 0.695551,0.195551) , 
1, 3.19498, 1, 0, 0.495334,-0.00466626)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.595917,0.0181488) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.285582,-0.0410191) , 
2, 0.0092358, 1, 0, 0.346903,-0.146398) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.46396,0.186884) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.808968,0.0590014) , 
2, 0.00550591, 1, 0, 0.89309,0.375338) , 
0, 1307.89, 1, 0, 0.4927,-0.00712763)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561551,0.0143603) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.206146,-0.0511744) , 
2, 0.00555045, 1, 0, 0.240896,-0.222098) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.765082,0.0456412) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.290269,-0.0420881) , 
2, 0.070192, 1, 0, 0.69661,0.162034) , 
1, 3.20851, 1, 0, 0.49737,-0.00591021)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.179053,-0.0526817) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454801,-0.00969676) , 
1, 2.66117, 1, 0, 0.348577,-0.129031) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.961324,0.0814287) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.387703,-0.0349955) , 
3, 0.328957, 1, 0, 0.869884,0.306517) , 
1, 4.04629, 1, 0, 0.506655,0.00304172)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.450549,-0.00563108) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.188562,-0.0524142) , 
3, 0.370423, 1, 0, 0.35892,-0.107441) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.803689,0.0441745) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.13335,0.110272) , 
0, 2434.49, 1, 0, 0.88535,0.286247) , 
0, 1305.25, 1, 0, 0.50653,0.00294823)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.175427,-0.0472284) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354081,-0.0158442) , 
1, 2.52508, 1, 0, 0.241885,-0.170434) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.48204,0.183453) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.652602,0.0183688) , 
2, 0.00367652, 1, 0, 0.702079,0.129757) , 
1, 3.09578, 1, 0, 0.527293,0.0157418)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.325787,-0.0203442) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.820573,0.0447486) , 
1, 3.26083, 1, 0, 0.661361,0.108618) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.402992,-0.0195978) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0926533,-0.0666258) , 
3, 0.617644, 1, 0, 0.348849,-0.13205) , 
3, 0.18522, 1, 0, 0.481457,-0.0299275)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.226078,-0.0380148) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.46969,-0.00253848) , 
0, 819.402, 1, 0, 0.321271,-0.114624) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.880073,0.0528088) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.418772,-0.0330555) , 
3, 0.315182, 1, 0, 0.814126,0.1801) , 
1, 3.90621, 1, 0, 0.499461,-0.00806734)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.406065,-0.00864944) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.188824,-0.0453253) , 
2, 0.0332169, 1, 0, 0.313194,-0.114391) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.815788,0.0365764) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.379788,-0.0303008) , 
3, 0.418262, 1, 0, 0.763573,0.122573) , 
0, 1152.17, 1, 0, 0.474423,-0.0295615)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.280918,-0.0255076) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.705213,0.0235661) , 
0, 715.082, 1, 0, 0.593114,0.0459802) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.204982,-0.0319182) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.215255,-0.0537636) , 
0, 975.462, 1, 0, 0.208105,-0.178083) , 
3, 0.419792, 1, 0, 0.509079,-0.00292577)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.265551,-0.0226635) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.844596,0.0489831) , 
1, 2.85951, 1, 0, 0.698444,0.133737) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611157,0.0234255) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.268129,-0.0328791) , 
2, 0.00721334, 1, 0, 0.317422,-0.114667) , 
3, 0.222344, 1, 0, 0.50541,0.00789054)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.292855,-0.0161375) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.761295,0.0282254) , 
1, 2.9678, 1, 0, 0.636676,0.0700863) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.114857,-0.0508158) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.340877,-0.0152862) , 
0, 933.251, 1, 0, 0.165868,-0.187871) , 
3, 0.370279, 1, 0, 0.49907,-0.00530875)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.344177,-0.0104038) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.08894,0.098512) , 
1, 2.87004, 1, 0, 0.825545,0.218972) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483088,-0.00193112) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.264191,-0.0361099) , 
2, 0.0565078, 1, 0, 0.429283,-0.0462601) , 
2, 0.00738154, 1, 0, 0.500787,0.00159987)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.113343,-0.0454334) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.476317,-0.00409643) , 
1, 2.03829, 1, 0, 0.405963,-0.0513767) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.093,0.0995151) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.860663,0.0305545) , 
1, 5.28409, 1, 0, 0.952015,0.223424) , 
1, 4.66453, 1, 0, 0.504037,-0.00202088)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.627168,0.0362092) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.23512,-0.0304976) , 
2, 0.00553615, 1, 0, 0.271012,-0.10692) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.921357,0.05356) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45482,-0.0162564) , 
3, 0.318003, 1, 0, 0.845459,0.161958) , 
1, 3.79018, 1, 0, 0.491084,-0.0039119)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.423543,-0.00224869) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.218321,-0.0313329) , 
2, 0.037003, 1, 0, 0.350293,-0.0547177) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.870314,0.039529) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.219106,-0.0452099) , 
3, 0.444374, 1, 0, 0.806047,0.10912) , 
0, 1224.74, 1, 0, 0.494525,-0.00286841)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.206493,-0.0261397) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.752967,0.0238218) , 
1, 2.59437, 1, 0, 0.640781,0.0523971) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.221248,-0.0517639) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.245598,-0.0173345) , 
3, 0.38267, 1, 0, 0.239245,-0.114737) , 
3, 0.333229, 1, 0, 0.504057,-0.00451235)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.444333,-9.89184e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.246884,-0.0279504) , 
2, 0.0310375, 1, 0, 0.37069,-0.0442271) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.960087,0.0604108) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.717081,0.00768588) , 
2, 0.0238589, 1, 0, 0.879239,0.140625) , 
0, 1305.27, 1, 0, 0.524087,0.0115309)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.37048,-0.00957382) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.167365,-0.039851) , 
2, 0.0517205, 1, 0, 0.3225,-0.0708234) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.815969,0.0267285) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.550148,-0.0206583) , 
2, 0.0550591, 1, 0, 0.782523,0.0697269) , 
0, 1152.15, 1, 0, 0.503164,-0.0156253)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.322686,-0.0125708) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.359063,-0.0464214) , 
1, 4.14768, 1, 0, 0.328955,-0.0791309) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.680993,0.000988961) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.999575,0.063704) , 
1, 4.5939, 1, 0, 0.859337,0.105976) , 
0, 1305.27, 1, 0, 0.473899,-0.0285445)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.403827,0.00307759) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.199143,-0.0258917) , 
2, 0.0147082, 1, 0, 0.270292,-0.0625907) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.835095,0.0270418) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.441278,-0.0105471) , 
3, 0.270476, 1, 0, 0.701406,0.0438453) , 
0, 907.648, 1, 0, 0.475812,-0.0118506)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.895898,0.102771) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.939001,0.0447079) , 
1, 3.92581, 1, 0, 0.922446,0.247489) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.36333,-0.0110528) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.877096,0.0349215) , 
0, 1583.02, 1, 0, 0.463602,-0.0152107) , 
3, 0.0370412, 1, 0, 0.504319,0.00810104)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0860724,-0.0427249) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.305143,-0.0119553) , 
1, 1.83881, 1, 0, 0.267503,-0.0680244) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.874102,0.0309978) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.597069,-0.00378661) , 
3, 0.151491, 1, 0, 0.728114,0.0382847) , 
1, 3.43292, 1, 0, 0.489851,-0.0167065)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.637474,0.0180128) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.41571,0.385243) , 
1, 4.36591, 1, 0, 0.838645,0.178101) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.39771,-0.00707652) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.924806,0.0437306) , 
0, 1799.6, 1, 0, 0.478975,-0.00482848) , 
2, 0.00554148, 1, 0, 0.523801,0.0179698)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.578617,-0.00145688) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.622121,0.0436059) , 
2, 0.0262657, 1, 0, 0.58615,0.0247552) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504055,-0.00109255) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.105982,-0.0420816) , 
3, 0.308365, 1, 0, 0.313601,-0.0755685) , 
2, 0.0462537, 1, 0, 0.522313,0.00125695)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.105037,-0.0504732) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.132856,-0.0240209) , 
2, 0.00938183, 1, 0, 0.126411,-0.109237) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.495878,0.0105518) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.747907,-0.0286987) , 
1, 4.44314, 1, 0, 0.573829,0.00749258) , 
1, 2.20298, 1, 0, 0.496193,-0.0127624)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.610804,-0.00145693) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.282548,-0.0226424) , 
3, 0.234549, 1, 0, 0.447534,-0.0473417) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.1374,0.121189) , 
0, 2782.34, 1, 0, 0.48083,-0.032028)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.642684,0.0188054) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.38289,0.441354) , 
1, 4.67988, 1, 0, 0.81625,0.156007) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0494695,-0.0483624) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.497451,0.00084019) , 
1, 1.61624, 1, 0, 0.460859,-0.00918197) , 
2, 0.00738864, 1, 0, 0.528196,0.0221167)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.635213,0.0107539) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.155895,-0.0328834) , 
3, 0.5549, 1, 0, 0.573386,0.0177856) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.301467,-0.0393375) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.307176,-0.0154317) , 
2, 0.0481502, 1, 0, 0.305536,-0.0841467) , 
2, 0.0386089, 1, 0, 0.50112,-0.00971579)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.455436,-0.000410225) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.647221,-0.0829269) , 
1, 5.32465, 1, 0, 0.468439,-0.0146624) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.17954,0.162281) , 
0, 2537.85, 1, 0, 0.509041,0.00287048)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0699587,-0.0440366) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.19011,-0.0171181) , 
1, 1.54834, 1, 0, 0.164901,-0.0790768) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.981975,0.0734138) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.588364,-0.000505822) , 
2, 0.00553615, 1, 0, 0.637753,0.0220605) , 
1, 2.59978, 1, 0, 0.508195,-0.00565028)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.756398,0.0649524) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.947125,0.0292969) , 
0, 1234.57, 1, 0, 0.862094,0.137265) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.284664,-0.0184578) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.797764,0.00478669) , 
0, 1294.22, 1, 0, 0.422666,-0.0505063) , 
2, 0.00554148, 1, 0, 0.468939,-0.0307335)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
2, 0.00251168, 1, -99, 0.887182,0.0625761) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611623,0.00202227) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.263211,-0.0205066) , 
3, 0.259258, 1, 0, 0.468272,-0.0263103) , 
2, 0.0037003, 1, 0, 0.497266,-0.013821)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.481857,0.00412031) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.772974,-0.0548121) , 
1, 5.15092, 1, 0, 0.521436,-0.0010914) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.153056,-0.0503297) , 
2, 0.0978994, 1, 0, 0.496174,-0.0138856)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.603677,0.00389394) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.200759,-0.0282758) , 
3, 0.308633, 1, 0, 0.444803,-0.032024) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.2865,0.24798) , 
0, 2833.74, 1, 0, 0.470048,-0.0197715)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.370808,-0.00442672) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.803552,0.0199516) , 
0, 907.677, 1, 0, 0.623835,0.0278484) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.193498,-0.0118585) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.273042,-0.0435878) , 
0, 1245.22, 1, 0, 0.20894,-0.0657517) , 
3, 0.369948, 1, 0, 0.495165,-0.00117939)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
0, 1627.43, 1, -99, 0.92165,0.0797883) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.555615,0.00728883) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0773163,-0.0381999) , 
3, 0.567887, 1, 0, 0.483422,0.00554519) , 
2, 0.00555045, 1, 0, 0.536886,0.034109)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.407096,0.00321584) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.701966,-0.0380788) , 
1, 4.54515, 1, 0, 0.468382,-0.0117106) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.40582,0.3509) , 
0, 2850.11, 1, 0, 0.498586,0.00465144)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.962082,0.104459) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534692,-0.0467787) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.463882,0.00593426) , 
3, 0.0728793, 1, 0, 0.476165,-0.00865767) , 
3, 0.0247163, 1, 0, 0.49995,0.00826686)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.299339,-0.0651112) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.954349,0.00573973) , 
1, 3.39897, 1, 0, 0.61418,-0.142379) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.210925,-0.0148345) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.626833,0.0105462) , 
0, 715.06, 1, 0, 0.494411,0.00898712) , 
2, 0.0036907, 1, 0, 0.503968,-0.00309065)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.682792,0.0134113) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.31846,-0.0105173) , 
3, 0.222244, 1, 0, 0.490186,0.00201537) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.687872,-0.106742) , 
1, 6.05961, 1, 0, 0.498627,-0.00611444)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.703537,0.0180635) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.214003,-0.0192751) , 
3, 0.517907, 1, 0, 0.624559,0.0394115) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.364878,-0.0319654) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.230766,0.0055176) , 
3, 0.271304, 1, 0, 0.311498,-0.0689646) , 
2, 0.0333027, 1, 0, 0.515756,0.00174578)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.236458,-0.0190299) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.190493,0.00183573) , 
2, 0.0461258, 1, 0, 0.227579,-0.0569657) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.739815,0.0174672) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.749472,-0.0691824) , 
1, 5.96771, 1, 0, 0.740815,0.0403864) , 
1, 3.19044, 1, 0, 0.510768,-0.00324953)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448116,-0.00432117) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.585674,-0.0786246) , 
1, 5.1589, 1, 0, 0.460614,-0.0346179) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.09291,0.151027) , 
0, 2432.51, 1, 0, 0.499193,-0.0216348)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.155112,-0.042216) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.122758,-0.014702) , 
2, 0.00760788, 1, 0, 0.130449,-0.0704373) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.429086,0.0248992) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.6607,-0.00653872) , 
1, 3.28731, 1, 0, 0.58463,0.0170298) , 
1, 2.20298, 1, 0, 0.51251,0.00314065)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.15293,0.163234) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.651439,0.00575935) , 
2, 0.00555045, 1, 0, 0.709342,0.0560775) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477923,-0.0199264) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.290321,0.00220989) , 
3, 0.336329, 1, 0, 0.385026,-0.0344368) , 
3, 0.172907, 1, 0, 0.526146,0.00494881)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.450211,-0.00226655) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.99819,0.0689662) , 
1, 5.3338, 1, 0, 0.474972,0.00155196) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.939217,-0.0232996) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.574894,-0.102911) , 
3, 0.181673, 1, 0, 0.791772,-0.108088) , 
0, 2374.78, 1, 0, 0.501598,-0.00766287)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0335679,-0.0540232) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.506714,-0.000172934) , 
1, 1.34659, 1, 0, 0.484182,-0.00737223) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.28294,0.325685) , 
1, 5.93735, 1, 0, 0.509011,0.00371235)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.610499,0.0101628) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.343388,-0.00917823) , 
2, 0.0424847, 1, 0, 0.5431,0.017324) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0626445,-0.0483938) , 
3, 0.765237, 1, 0, 0.519909,0.0105004)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.420192,-0.00237609) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.947074,0.0546331) , 
1, 4.63972, 1, 0, 0.488493,0.00999147) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.705309,-0.128689) , 
1, 5.87339, 1, 0, 0.500554,-0.00149466)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.13646,0.160703) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.675398,0.0276673) , 
2, 0.00296053, 1, 0, 0.711538,0.109685) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.330445,-0.010641) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.07578,0.116339) , 
1, 5.17899, 1, 0, 0.383458,-0.0177438) , 
2, 0.0184535, 1, 0, 0.537869,0.0422308)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.223838,-0.0230833) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.841379,0.0199013) , 
1, 2.93541, 1, 0, 0.654162,0.0103146) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.274,-0.000599124) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454242,-0.0300775) , 
1, 3.50131, 1, 0, 0.349296,-0.0471208) , 
3, 0.172798, 1, 0, 0.474817,-0.0234733)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.417405,-0.00432307) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.367756,0.0505753) , 
2, 0.086733, 1, 0, 0.413961,-0.00424174) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502592,-0.0641761) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.919028,0.00645209) , 
0, 1760.48, 1, 0, 0.736133,-0.0801596) , 
1, 4.52646, 1, 0, 0.495703,-0.0235038)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.700499,-0.0900144) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.656928,0.00977935) , 
2, 0.00224515, 1, 0, 0.660399,0.0137999) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.319814,-0.00935492) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.643075,-0.0634459) , 
1, 5.21801, 1, 0, 0.351984,-0.0471838) , 
2, 0.0165443, 1, 0, 0.490962,-0.0197034)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.603479,0.00715789) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.2514,0.411815) , 
1, 5.09182, 1, 0, 0.686329,0.0592353) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.383008,-0.00214549) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.572007,-0.0929721) , 
1, 5.42415, 1, 0, 0.400488,-0.0298583) , 
2, 0.0147773, 1, 0, 0.509764,0.00420186)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.513032,0.00819524) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.66325,-0.0714403) , 
1, 5.50554, 1, 0, 0.524151,0.0134341) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.28025,0.984867) , 
0, 2835.12, 1, 0, 0.554568,0.0247944)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.32114,0.0309184) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.265337,-0.0188641) , 
0, 544.825, 1, 0, 0.271226,-0.0525982) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.635518,0.043054) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.735308,-0.0044305) , 
0, 1053.81, 1, 0, 0.720255,0.0171154) , 
0, 902.719, 1, 0, 0.505306,-0.0162564)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.354561,-0.00398187) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.404493,-0.0356598) , 
1, 4.02917, 1, 0, 0.359827,-0.0266813) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.900389,0.0175463) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.18541,0.179176) , 
3, 0.229415, 1, 0, 0.941031,0.103399) , 
1, 4.23577, 1, 0, 0.497947,0.00423163)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.640457,-0.0110017) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.682935,0.0465828) , 
3, 0.188779, 1, 0, 0.648787,0.0046545) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.217642,-0.00807335) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.36592,-0.0521923) , 
0, 1157.67, 1, 0, 0.252563,-0.0645775) , 
3, 0.259371, 1, 0, 0.476435,-0.0254604)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514664,-0.00183211) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.702968,-0.0714325) , 
1, 4.10541, 1, 0, 0.610027,-0.0819224) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.183717,-0.0168626) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.644991,0.0136701) , 
0, 715.06, 1, 0, 0.470765,0.00731204) , 
3, 0.0738557, 1, 0, 0.501664,-0.0124869)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.276362,-0.0138162) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.686384,0.00985372) , 
0, 915.785, 1, 0, 0.462336,-0.0126026) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.940763,-0.0424708) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.543561,-0.217207) , 
3, 0.181896, 1, 0, 0.754957,-0.168839) , 
0, 2374.78, 1, 0, 0.488346,-0.0264897)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.387114,-0.009996) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.944099,0.0461532) , 
0, 1777.31, 1, 0, 0.433724,-0.0263597) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.1274,0.60449) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.523829,-0.0819454) , 
2, 0.0127484, 1, 0, 0.712111,-0.126871) , 
1, 5.34303, 1, 0, 0.46434,-0.0374133)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.391171,0.00483952) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.680434,-0.0274559) , 
1, 4.16831, 1, 0, 0.457131,-0.00464211) , 
NN(
0, 
0, 
2, 0.0128471, 1, -99, 1.04397,0.106248) , 
1, 5.18699, 1, 0, 0.518539,0.0109565)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.637313,-0.00988941) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.777356,0.0391338) , 
3, 0.0695095, 1, 0, 0.704201,0.0404697) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.370018,-0.00997592) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.598736,-0.152727) , 
0, 2374.78, 1, 0, 0.38756,-0.0510305) , 
3, 0.148146, 1, 0, 0.503963,-0.0173935)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.55361,-0.00347142) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.135493,-0.0260933) , 
3, 0.469168, 1, 0, 0.463558,-0.026348) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.14192,0.301302) , 
1, 5.83678, 1, 0, 0.493625,-0.0169664)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.862076,0.0904093) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.903484,0.0174162) , 
0, 1119.93, 1, 0, 0.887741,0.174961) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.255378,-0.0132257) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.74091,0.0126122) , 
1, 3.42017, 1, 0, 0.464594,-0.00935334) , 
3, 0.0493864, 1, 0, 0.517318,0.0136124)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.312527,-0.00994168) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.484032,-0.0361414) , 
1, 4.25408, 1, 0, 0.328218,-0.0455806) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.00068,0.0667367) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.753333,-0.0126381) , 
3, 0.098828, 1, 0, 0.842071,0.0223257) , 
0, 1305.27, 1, 0, 0.468202,-0.0270815)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.593787,-0.000635033) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.19634,0.643149) , 
1, 4.28511, 1, 0, 0.794367,0.0707454) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.307886,8.33446e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.652534,-0.0317902) , 
1, 4.00847, 1, 0, 0.422885,-0.0306394) , 
2, 0.00738141, 1, 0, 0.492042,-0.0117652)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.371547,-0.00482816) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.347184,0.0715065) , 
2, 0.0851068, 1, 0, 0.370321,-0.00737638) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.976577,0.0570555) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.388607,-0.0359905) , 
3, 0.313145, 1, 0, 0.853638,0.0624509) , 
1, 4.19129, 1, 0, 0.502683,0.0117466)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.55708,-0.011153) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.633354,-0.235366) , 
1, 4.62189, 1, 0, 0.585499,-0.132429) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.404425,-0.00500588) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.11926,0.217318) , 
0, 2456.31, 1, 0, 0.433408,-0.00848209) , 
3, 0.0864104, 1, 0, 0.471123,-0.0392186)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.236506,-0.0033826) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.223101,-0.0443328) , 
1, 3.17966, 1, 0, 0.234547,-0.0371274) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.803614,0.00718378) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.664818,0.0632544) , 
3, 0.291182, 1, 0, 0.776283,0.0707781) , 
1, 3.30159, 1, 0, 0.498383,0.0154246)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
2, 0.00573828, 1, -99, 0.800223,0.0472417) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.353222,-0.00818612) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.05771,0.11332) , 
0, 1861.6, 1, 0, 0.427536,-0.00503402) , 
2, 0.00738864, 1, 0, 0.490656,0.0171498)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.146382,-0.0186044) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.619784,0.0110266) , 
1, 2.30456, 1, 0, 0.524736,0.0175564) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.20086,-0.0390393) , 
2, 0.0942051, 1, 0, 0.500423,0.00610829)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.422199,0.00217318) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.08516,0.106874) , 
1, 4.61428, 1, 0, 0.46935,0.0343086) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.946426,-0.259677) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.414601,-0.159329) , 
2, 0.0146824, 1, 0, 0.640897,-0.251943) , 
1, 5.11763, 1, 0, 0.496081,-0.0102966)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.683184,-0.0421567) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.451792,0.00131877) , 
2, 0.00553606, 1, 0, 0.486768,-0.0106939) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.620325,-0.102871) , 
1, 5.84244, 1, 0, 0.49765,-0.0277033)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.394143,-0.00827562) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.901525,0.0378695) , 
1, 4.69664, 1, 0, 0.460877,-0.0138229) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.11086,0.15193) , 
1, 5.84903, 1, 0, 0.487659,-0.00312008)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.955089,0.0895434) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.433381,0.00149665) , 
3, 0.0247858, 1, 0, 0.457371,0.0187989) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.10141,0.529491) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.518278,-0.107131) , 
2, 0.0127484, 1, 0, 0.728305,-0.138838) , 
1, 5.13326, 1, 0, 0.495186,-0.00320242)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.439256,0.0229891) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.652883,-0.0673285) , 
0, 783.209, 1, 0, 0.601183,-0.101082) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.414007,0.00132542) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.25431,0.236888) , 
1, 5.14181, 1, 0, 0.469064,0.0316878) , 
3, 0.0862618, 1, 0, 0.502559,-0.00197249)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.599899,-0.0403099) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0350494,-0.0479006) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.537296,0.00677854) , 
1, 1.55438, 1, 0, 0.498734,0.0117627) , 
3, 0.0247107, 1, 0, 0.506297,0.00176877)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.427442,0.00563986) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.15626,0.152073) , 
1, 4.57176, 1, 0, 0.480088,0.0407689) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.572718,-0.11799) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.13647,1.43418) , 
0, 2735.83, 1, 0, 0.711234,-0.163403) , 
1, 5.13889, 1, 0, 0.515674,0.00933514)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.270279,0.00145544) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.617256,-0.0302199) , 
1, 3.32288, 1, 0, 0.44809,-0.0453153) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.21955,0.355696) , 
1, 5.79114, 1, 0, 0.476029,-0.0335552)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.438711,5.01048e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.651105,-0.232474) , 
0, 2233.62, 1, 0, 0.447815,-0.0110981) , 
NN(
0, 
0, 
0, 2608.86, 1, -99, 1.02722,0.0990265) , 
1, 5.13374, 1, 0, 0.5037,0.0013823)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679146,0.0131815) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.405,5.11785) , 
1, 4.32825, 1, 0, 0.857102,0.133769) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.330229,0.00209182) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.693693,-0.0386144) , 
1, 4.12204, 1, 0, 0.449051,-0.0263921) , 
2, 0.00553606, 1, 0, 0.500549,-0.00617871)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.70482,-0.138135) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.633623,-0.0194563) , 
3, 0.061637, 1, 0, 0.648466,-0.0821103) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.434267,0.00171474) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.843971,-0.50201) , 
0, 2645.5, 1, 0, 0.453424,-0.000840699) , 
2, 0.00738864, 1, 0, 0.492751,-0.0172275)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.225946,0.00264826) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.609323,0.0368964) , 
1, 3.07208, 1, 0, 0.361397,0.0617679) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.833798,0.0116159) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.344438,-0.0325442) , 
3, 0.282829, 1, 0, 0.680501,-0.0170883) , 
0, 989.136, 1, 0, 0.527564,0.0207049)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9043,0.061874) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543213,-0.0291071) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.406495,0.00903948) , 
2, 0.0166513, 1, 0, 0.473561,-0.0263009) , 
3, 0.0246903, 1, 0, 0.497828,-0.0144399)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471447,0.000340823) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.208512,-0.0325614) , 
2, 0.0811969, 1, 0, 0.445025,-0.0107307) , 
NN(
0, 
0, 
0, 2669.72, 1, -99, 1.13221,0.215729) , 
0, 2190.97, 1, 0, 0.503384,0.00777805)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.559672,-0.0197045) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.70748,-0.130417) , 
1, 5.31535, 1, 0, 0.585489,-0.0871611) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583348,0.0126704) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.187347,-0.0165329) , 
3, 0.451316, 1, 0, 0.475173,0.0155083) , 
3, 0.0740962, 1, 0, 0.501454,-0.00895079)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.31868,0.298309) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.62305,-0.0166947) , 
3, 0.147846, 1, 0, 0.843011,0.101277) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.423763,0.00207489) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.804201,-0.116163) , 
0, 2148.24, 1, 0, 0.465253,-0.00706134) , 
2, 0.00553615, 1, 0, 0.512072,0.00636598)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601431,-0.00687973) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.569432,-0.148451) , 
1, 5.16636, 1, 0, 0.593422,-0.0886275) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.01532,0.121559) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436465,-0.00178927) , 
3, 0.109107, 1, 0, 0.463179,0.00989869) , 
3, 0.0864972, 1, 0, 0.497006,-0.0156905)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.617608,-0.00446258) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.457971,0.0280769) , 
3, 0.274963, 1, 0, 0.575623,0.0145089) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0906724,-0.016662) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.127512,-0.0398965) , 
1, 2.87345, 1, 0, 0.10696,-0.0796822) , 
3, 0.530851, 1, 0, 0.503256,-3.52649e-05)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
1, 3.53865, 1, -99, 0.855137,0.0519237) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.35379,-0.00303764) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.749241,-0.0456678) , 
1, 4.52485, 1, 0, 0.437227,-0.0286121) , 
2, 0.00553615, 1, 0, 0.486915,-0.0108339)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.130115,-0.0393684) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.480358,-0.00393173) , 
0, 548.377, 1, 0, 0.446611,-0.024616) , 
NN(
0, 
0, 
2, 0.0118182, 1, -99, 1.10249,0.287235) , 
0, 2456.29, 1, 0, 0.484907,-0.0151247)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.311865,-0.0214284) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.772631,-0.00487615) , 
0, 1073.31, 1, 0, 0.513958,-0.0525641) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.233198,0.0535008) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.280557,-0.0321772) , 
0, 1005.45, 1, 0, 0.248433,0.0453228) , 
3, 0.48147, 1, 0, 0.475936,-0.0385471)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503583,-0.0397031) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.16506,11.9647) , 
1, 4.81153, 1, 0, 0.606159,-0.0734345) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492827,0.0103406) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.205331,-0.0331481) , 
2, 0.0971036, 1, 0, 0.473201,0.0240709) , 
2, 0.00740059, 1, 0, 0.503238,0.0020429)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.293975,-0.00808841) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.298603,0.0349646) , 
2, 0.0758561, 1, 0, 0.294352,-0.017355) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.916365,0.0427062) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.597079,-0.00776366) , 
3, 0.176671, 1, 0, 0.774478,0.0447347) , 
1, 3.59945, 1, 0, 0.502077,0.00950794)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.385056,-0.00925414) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.914912,0.0274112) , 
0, 1655.21, 1, 0, 0.472839,-0.0191247) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.784999,-0.170685) , 
1, 6.00954, 1, 0, 0.487469,-0.0255815)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.415856,-0.00597711) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.630215,-0.0680881) , 
1, 4.91259, 1, 0, 0.433954,-0.0313145) , 
NN(
0, 
0, 
1, 5.90731, 1, -99, 1.01994,0.101177) , 
1, 5.37739, 1, 0, 0.481148,-0.0194228)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
3, 0.147724, 1, -99, 0.912758,0.0795437) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.501429,-0.0428501) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.468984,0.00685866) , 
2, 0.0108977, 1, 0, 0.476743,-0.012129) , 
2, 0.00555045, 1, 0, 0.522455,0.00893921)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.668722,-0.0743928) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.473857,0.0066656) , 
2, 0.00362285, 1, 0, 0.490289,0.00682063) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.178516,-0.0461945) , 
2, 0.0978994, 1, 0, 0.467366,-0.00510371)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.761517,-0.00126257) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.498327,-0.0234032) , 
2, 0.0165443, 1, 0, 0.634765,-0.0424049) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.584976,0.0399552) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.282467,-0.00197444) , 
3, 0.319571, 1, 0, 0.36081,0.0337174) , 
3, 0.234512, 1, 0, 0.519411,-0.0103522)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.629354,-0.0288894) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.495452,0.00210271) , 
3, 0.0864855, 1, 0, 0.531644,-0.016591) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.539144,0.0550876) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.245139,-0.00752375) , 
2, 0.0959106, 1, 0, 0.410693,0.0933898) , 
2, 0.0608976, 1, 0, 0.515231,-0.00166668)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.288135,0.00279069) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.655683,0.0407791) , 
1, 3.29218, 1, 0, 0.349295,0.0348618) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.433778,-0.03158) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.84968,0.00798213) , 
0, 1097.77, 1, 0, 0.721975,-0.0283037) , 
1, 3.7017, 1, 0, 0.511893,0.00730301)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
1, 3.57371, 1, -99, 0.902692,0.0704077) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.343003,-0.0035815) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.896475,0.0340968) , 
0, 1315.17, 1, 0, 0.482803,0.00764383) , 
2, 0.00369077, 1, 0, 0.511087,0.0184694)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.397123,-0.00322486) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.970462,0.0686906) , 
1, 4.52046, 1, 0, 0.470877,0.0136609) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.962083,-0.0256877) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.624695,-0.31992) , 
3, 0.166238, 1, 0, 0.834412,-0.119698) , 
0, 2293.29, 1, 0, 0.506394,0.000631851)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507271,-0.056319) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.01416,153.793) , 
1, 4.31587, 1, 0, 0.638191,-0.1193) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.733449,0.0257955) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.340524,-0.00801054) , 
3, 0.135772, 1, 0, 0.46098,0.0054) , 
2, 0.00551478, 1, 0, 0.485781,-0.0120523)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.231658,-0.0109955) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.697141,0.0136264) , 
0, 744.667, 1, 0, 0.53293,0.0125517) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.204378,-0.0332721) , 
2, 0.0906573, 1, 0, 0.502171,0.00109052)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583875,0.100742) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.227621,0.00760186) , 
3, 0.123628, 1, 0, 0.282712,0.102301) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.678507,-0.0225461) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.468657,0.0117381) , 
3, 0.197576, 1, 0, 0.582626,-0.0154307) , 
0, 663.101, 1, 0, 0.520269,0.00904754)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.304901,0.0210325) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.569846,-0.00414631) , 
0, 740.747, 1, 0, 0.483293,0.0129944) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.24216,0.546462) , 
0, 2449.37, 1, 0, 0.525925,0.027762)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58189,0.0105139) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.689929,-0.0739364) , 
1, 4.05173, 1, 0, 0.642954,-0.072183) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.428332,0.0212665) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.829988,-0.0142418) , 
0, 1396.68, 1, 0, 0.540173,0.047376) , 
3, 0.049536, 1, 0, 0.556171,0.0287664)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.330617,-0.000971477) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.353445,-0.0749372) , 
1, 4.27376, 1, 0, 0.332738,-0.0289269) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.877612,-0.000343862) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.681919,0.0397787) , 
3, 0.25922, 1, 0, 0.832777,0.0305037) , 
0, 1224.8, 1, 0, 0.494045,-0.00975517)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.664576,0.0355594) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.880734,-0.0746396) , 
0, 1466.4, 1, 0, 0.753825,0.0501685) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.36808,-0.0058314) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.707901,-0.234951) , 
0, 2374.78, 1, 0, 0.389633,-0.0330923) , 
2, 0.00925074, 1, 0, 0.479989,-0.0124353)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.229473,0.0311093) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.479345,-0.00501013) , 
0, 553.345, 1, 0, 0.4585,-0.00643805) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.03676,0.571622) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.588986,-0.0806347) , 
2, 0.0127484, 1, 0, 0.763454,-0.111408) , 
1, 5.11484, 1, 0, 0.495981,-0.0193394)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.687826,0.0190154) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380508,-0.00896965) , 
3, 0.111076, 1, 0, 0.455202,-0.00681084) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596908,-0.0932815) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.03602,48.5671) , 
0, 2869.76, 1, 0, 0.701241,-0.146672) , 
1, 5.27819, 1, 0, 0.490542,-0.0268994)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.460683,-0.00483573) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.10723,0.139242) , 
1, 5.2663, 1, 0, 0.490314,-0.00279421) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.991731,0.0596223) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.547227,-0.144314) , 
2, 0.0106228, 1, 0, 0.751508,-0.135876) , 
0, 2351.99, 1, 0, 0.521939,-0.0189073)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.775612,0.0452394) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.365363,-0.00694885) , 
3, 0.0247163, 1, 0, 0.384221,-0.0140048) , 
NN(
0, 
0, 
0, 2818.82, 1, -99, 0.96827,0.0628596) , 
0, 1583, 1, 0, 0.495159,0.00764577)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54334,-0.00892307) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.276361,0.010522) , 
3, 0.345686, 1, 0, 0.466951,-0.0126215) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.723168,-0.0855395) , 
1, 5.74446, 1, 0, 0.485418,-0.0221116)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.687998,0.0148086) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.369554,-0.01142) , 
2, 0.011083, 1, 0, 0.461285,-0.017127) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.693162,-0.152704) , 
1, 5.97641, 1, 0, 0.473087,-0.0269774)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.883918,-0.0312201) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.531754,-0.0919894) , 
2, 0.0025693, 1, 0, 0.694025,-0.136498) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.576911,0.00891688) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.291213,-0.0135515) , 
2, 0.0392654, 1, 0, 0.491731,0.00643152) , 
2, 0.00365148, 1, 0, 0.505489,-0.00328882)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.36458,-0.00917101) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.938037,0.0506374) , 
1, 4.47985, 1, 0, 0.443489,-0.0124066) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.956505,-0.0425718) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438053,-0.113905) , 
3, 0.166238, 1, 0, 0.704957,-0.150994) , 
0, 2351.98, 1, 0, 0.469167,-0.0260167)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.361916,0.0106492) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.677701,-0.0108164) , 
1, 3.6697, 1, 0, 0.497065,0.00700147) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.17819,1.32032) , 
0, 2850.1, 1, 0, 0.519686,0.0129548)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.417401,-0.0289218) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.900628,0.0150195) , 
0, 1187.27, 1, 0, 0.644879,-0.0470519) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.354736,0.000214858) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.976219,0.0606258) , 
1, 4.28619, 1, 0, 0.484648,0.02225) , 
3, 0.0740601, 1, 0, 0.516232,0.00858965)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.749263,0.0301014) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.423977,-0.0110096) , 
3, 0.0497123, 1, 0, 0.464164,-0.0198688) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.13307,0.26188) , 
1, 5.84903, 1, 0, 0.491041,-0.0116702)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529075,-0.0539777) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.341379,-0.00430001) , 
2, 0.00367704, 1, 0, 0.357705,-0.0286522) , 
NN(
0, 
0, 
1, 4.58638, 1, -99, 0.943307,0.0544725) , 
1, 4.26072, 1, 0, 0.499155,0.00462464)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475854,0.00487972) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.11765,0.295952) , 
0, 2363.36, 1, 0, 0.498872,0.0224111) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.760518,-0.129977) , 
1, 5.87339, 1, 0, 0.516125,0.0105422)    );
   return;
};

// Clean up
inline void ReadBDT-0.4.6_fold1::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadBDT-0.4.6_fold1::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
