// Class: ReadBDT-0.4.6_fold9
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT-0.4.6_fold9
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.32/00       [401408]
Creator        : abennett
Date           : Thu Aug 22 16:00:08 2024
Host           : Linux 6772f6b99311 6.5.0-1022-azure #23~22.04.1-Ubuntu SMP Thu May 9 17:59:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /gluster/home/abennett/BDT_training
Training events: 17709
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "125" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "3%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "80" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e-01" [Learning rate for BoostType=Grad algorithm]
UseNvars: "2" [Size of the subset of variables used with RandomisedTree option]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "sdivsqrtsplusb" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 4
mjj                           mjj                           mjj                           m_{jj}                        GeV                               'D'    [500.083496094,7102.28710938]
JetGap                        JetGap                        JetGap                        #Delta y_{jj}                                                   'D'    [0.0204434599727,8.30311965942]
PtBalance                     PtBalance                     PtBalance                     pT_{balance}                                                    'D'    [1.2169821817e-09,0.149861991405]
centrality                    centrality                    centrality                    #xi(Z)                                                          'D'    [5.42057250641e-06,0.999970436096]
NSpec 1
eventNumber                   eventNumber                   eventNumber                   I                                                               'F'    [703,684984192]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new BDT-0.4.6_fold9Node

#ifndef BDT-0.4.6_fold9Node__def
#define BDT-0.4.6_fold9Node__def

class BDT-0.4.6_fold9Node {

public:

   // constructor of an essentially "empty" node floating in space
   BDT-0.4.6_fold9Node ( BDT-0.4.6_fold9Node* left,BDT-0.4.6_fold9Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT-0.4.6_fold9Node();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT-0.4.6_fold9Node* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT-0.4.6_fold9Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT-0.4.6_fold9Node*   fLeft;     // pointer to the left daughter node
   BDT-0.4.6_fold9Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   BDT-0.4.6_fold9Node::~BDT-0.4.6_fold9Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool BDT-0.4.6_fold9Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool BDT-0.4.6_fold9Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT-0.4.6_fold9 : public IClassifierReader {

 public:

   // constructor
   ReadBDT-0.4.6_fold9( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDT-0.4.6_fold9" ),
        fNvars( 4 )
   {
      // the training input variables
      const char* inputVars[] = { "mjj", "JetGap", "PtBalance", "centrality" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'D';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT-0.4.6_fold9() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[4];
   double fVmax[4];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[4];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT-0.4.6_fold9Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT-0.4.6_fold9::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT-0.4.6_fold9Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT-0.4.6_fold9Node*)current->GetRight();
         else current=(BDT-0.4.6_fold9Node*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
}

void ReadBDT-0.4.6_fold9::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.11904,-0.0761919) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.358462,-0.0283076) , 
1, 2.17335, 1, 0, 0.275704,-0.224296) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.816664,0.0633329) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.191028,-0.0617944) , 
3, 0.461035, 1, 0, 0.752842,0.252842) , 
1, 3.3029, 1, 0, 0.516381,0.0163814)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.246147,-0.0474513) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.510417,0.00393824) , 
0, 890.853, 1, 0, 0.314082,-0.170743) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.880787,0.070113) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.42836,-0.0164438) , 
3, 0.320212, 1, 0, 0.787805,0.260572) , 
1, 3.59996, 1, 0, 0.511285,0.00880663)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.213808,-0.0508381) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.506452,0.000351838) , 
0, 715.805, 1, 0, 0.367544,-0.118688) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601138,0.0178865) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.953097,0.0795144) , 
1, 3.8892, 1, 0, 0.875214,0.324125) , 
0, 1294.27, 1, 0, 0.518488,0.0129715)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.464636,-0.00589214) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.159602,-0.057907) , 
3, 0.456638, 1, 0, 0.383444,-0.0973418) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.863469,0.0567362) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.331048,-0.0329481) , 
3, 0.431437, 1, 0, 0.803658,0.224072) , 
0, 1315.17, 1, 0, 0.51226,0.00118791)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.137454,-0.0583254) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.366381,-0.0186177) , 
1, 2.36671, 1, 0, 0.290456,-0.155358) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.885068,0.0608384) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.503007,-0.0132741) , 
2, 0.0495532, 1, 0, 0.810499,0.22096) , 
1, 3.59996, 1, 0, 0.505096,-3.8185e-05)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.413774,-0.00368209) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.186335,-0.0486967) , 
2, 0.0145596, 1, 0, 0.26674,-0.159081) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.987412,0.0796724) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.719896,0.024264) , 
2, 0.00738153, 1, 0, 0.784989,0.176892) , 
1, 3.48021, 1, 0, 0.501922,-0.00661622)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558628,0.0269076) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.248917,-0.0359103) , 
2, 0.00555045, 1, 0, 0.279066,-0.14236) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.828394,0.0455658) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.35181,-0.0291012) , 
3, 0.333337, 1, 0, 0.732433,0.13937) , 
0, 907.627, 1, 0, 0.505772,-0.00148091)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.641494,0.0291712) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.357378,-0.0242691) , 
2, 0.00740059, 1, 0, 0.403349,-0.0740885) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.00149,0.0764435) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.774086,0.0270522) , 
2, 0.0165177, 1, 0, 0.917165,0.252289) , 
0, 1675.08, 1, 0, 0.492498,-0.0174607)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.314248,-0.0171849) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.169744,-0.0458609) , 
3, 0.22277, 1, 0, 0.223731,-0.163786) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.722448,0.0294768) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.425251,-0.0224001) , 
2, 0.0277361, 1, 0, 0.622934,0.0536553) , 
0, 720.447, 1, 0, 0.48097,-0.0236708)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.177226,-0.0420376) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.365892,-0.00886806) , 
1, 2.66117, 1, 0, 0.236137,-0.146201) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.819387,0.0413266) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.417644,-0.016078) , 
3, 0.289691, 1, 0, 0.713502,0.114406) , 
1, 3.1173, 1, 0, 0.510112,0.00336996)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.69571,0.0439708) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326479,-0.020955) , 
2, 0.00555045, 1, 0, 0.366599,-0.0635436) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.91009,0.0507963) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.400248,-0.0226619) , 
3, 0.393753, 1, 0, 0.854236,0.171928) , 
0, 1315.22, 1, 0, 0.505432,0.00349673)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.642931,0.0265438) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.340947,-0.0221164) , 
2, 0.00925074, 1, 0, 0.399878,-0.0575129) , 
NN(
0, 
0, 
1, 6.05014, 1, -99, 0.988935,0.0683627) , 
0, 1641.22, 1, 0, 0.505826,-3.04921e-05)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.792513,0.0372645) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.526949,-0.00248652) , 
2, 0.011083, 1, 0, 0.621253,0.0476329) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.480554,-0.000594015) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.187887,-0.0397728) , 
2, 0.00912414, 1, 0, 0.236639,-0.147565) , 
3, 0.320889, 1, 0, 0.488833,-0.0195724)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.18738,-0.0328516) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.355983,-0.00828718) , 
1, 2.54445, 1, 0, 0.276881,-0.0868797) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.694682,0.0103574) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.03133,0.0732739) , 
0, 2540.12, 1, 0, 0.737742,0.0690037) , 
1, 3.37317, 1, 0, 0.499849,-0.0114622)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.30976,-0.0123935) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.170663,-0.0373946) , 
3, 0.160326, 1, 0, 0.208129,-0.132413) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.813818,0.0322963) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.512785,-0.0100104) , 
2, 0.0184538, 1, 0, 0.666277,0.0429992) , 
1, 2.97873, 1, 0, 0.495131,-0.0225281)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.195879,-0.0323812) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.449328,-0.00470222) , 
0, 685.227, 1, 0, 0.323035,-0.0798058) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.16666,0.118654) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.749025,0.018556) , 
2, 0.00550591, 1, 0, 0.805406,0.113857) , 
0, 1152.15, 1, 0, 0.498277,-0.00944957)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.270655,-0.0190976) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.746256,0.0221904) , 
1, 2.96819, 1, 0, 0.600628,0.0354994) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.135804,-0.0451903) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.194628,-0.0227386) , 
3, 0.803875, 1, 0, 0.144094,-0.17582) , 
3, 0.432101, 1, 0, 0.498536,-0.0117569)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.299226,-0.0115227) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.829013,0.03691) , 
1, 2.87484, 1, 0, 0.703899,0.0966709) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.481694,-0.000703146) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.229737,-0.0299627) , 
2, 0.0163795, 1, 0, 0.340644,-0.0705553) , 
3, 0.222127, 1, 0, 0.522999,0.0133925)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.462353,-0.00315031) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.246824,-0.0299794) , 
2, 0.0333027, 1, 0, 0.386072,-0.0532715) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.607512,-0.0160299) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.983211,0.0551936) , 
1, 4.26516, 1, 0, 0.900388,0.11052) , 
0, 1646.54, 1, 0, 0.482238,-0.0226458)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.153534,-0.0385059) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.757932,0.0286057) , 
1, 2.15088, 1, 0, 0.670184,0.0698374) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.295731,-0.023329) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.03253,0.0768022) , 
0, 1967.26, 1, 0, 0.339868,-0.0762561) , 
2, 0.0184907, 1, 0, 0.489551,-0.0100537)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.121714,-0.0395562) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30029,-0.00124923) , 
0, 587.082, 1, 0, 0.207598,-0.0802658) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.77078,0.0224285) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.370967,-0.0120101) , 
3, 0.320315, 1, 0, 0.660015,0.045342) , 
0, 720.395, 1, 0, 0.50814,0.00317584)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.426143,-0.00857273) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.597242,-0.0678732) , 
1, 5.12282, 1, 0, 0.441917,-0.0503639) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.06933,0.0915839) , 
0, 2513.05, 1, 0, 0.477921,-0.0353277)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.119865,-0.0435999) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.700419,0.0237389) , 
1, 1.61959, 1, 0, 0.671336,0.0763658) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.211102,-0.0194981) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.229871,-0.051576) , 
1, 4.0577, 1, 0, 0.214778,-0.104709) , 
3, 0.320909, 1, 0, 0.506248,0.0108905)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596833,0.00652209) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.248645,-0.0222928) , 
3, 0.246916, 1, 0, 0.424704,-0.0298288) , 
NN(
0, 
0, 
2, 0.0201883, 1, -99, 1.04581,0.0838874) , 
1, 5.07793, 1, 0, 0.493876,-0.00251608)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.934453,0.0847468) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.933289,0.029683) , 
0, 1528.6, 1, 0, 0.933899,0.220155) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.653224,0.010477) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.284008,-0.0221724) , 
3, 0.209827, 1, 0, 0.470842,-0.0221247) , 
2, 0.00555045, 1, 0, 0.5197,0.00343884)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.147483,-0.0306023) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.686556,0.0147696) , 
1, 1.64984, 1, 0, 0.64252,0.0394869) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.329468,-0.0116927) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.540893,-0.0988913) , 
0, 2211.78, 1, 0, 0.3462,-0.0646851) , 
2, 0.0203398, 1, 0, 0.492496,-0.0132544)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.65271,0.0136487) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335945,-0.0188442) , 
2, 0.031371, 1, 0, 0.541231,0.00530859) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.101117,-0.0551784) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0938332,-0.0349337) , 
2, 0.0148169, 1, 0, 0.0966485,-0.158515) , 
3, 0.580188, 1, 0, 0.486562,-0.0148362)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.385991,-0.00317325) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.517446,-0.0527051) , 
1, 4.45482, 1, 0, 0.406172,-0.0405328) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.09637,0.10433) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.885481,0.0153968) , 
0, 2196.71, 1, 0, 0.95272,0.109404) , 
0, 1804.22, 1, 0, 0.483953,-0.0191947)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0777751,-0.0429377) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.263134,-0.00887128) , 
1, 1.58097, 1, 0, 0.228297,-0.0536426) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.946082,0.0515911) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.616872,0.00921327) , 
2, 0.00738864, 1, 0, 0.684288,0.0582187) , 
1, 2.87458, 1, 0, 0.526564,0.0195267)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492622,0.00572685) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.717809,-0.0578394) , 
1, 5.27819, 1, 0, 0.520913,0.00230652) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.163969,-0.0511357) , 
2, 0.0937645, 1, 0, 0.492414,-0.0136108)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.886782,0.0909321) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.873103,0.017453) , 
0, 983.437, 1, 0, 0.877537,0.152866) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.479766,-0.00198131) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.174538,-0.0492808) , 
2, 0.0935314, 1, 0, 0.451603,-0.0235221) , 
2, 0.0073963, 1, 0, 0.529677,0.00880987)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.08268,0.108717) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.592317,0.00235228) , 
2, 0.00553615, 1, 0, 0.648879,0.0372771) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.256268,-0.0123353) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.353947,-0.058218) , 
1, 4.49115, 1, 0, 0.269201,-0.067778) , 
3, 0.271579, 1, 0, 0.487245,-0.00744608)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.411175,-0.00766208) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.525067,-0.0614985) , 
1, 4.99937, 1, 0, 0.418787,-0.0415063) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.694636,-0.0251237) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.996193,0.0585308) , 
1, 4.52642, 1, 0, 0.927281,0.0740267) , 
0, 1933.12, 1, 0, 0.490997,-0.0250995)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.158588,-0.0529341) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.108459,-0.0273717) , 
2, 0.00758759, 1, 0, 0.118005,-0.112628) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626361,0.00665919) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.215854,-0.020074) , 
3, 0.430618, 1, 0, 0.553601,0.00645834) , 
1, 2.20298, 1, 0, 0.485662,-0.0121152)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.249948,-0.01653) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.806212,0.0283762) , 
1, 2.88012, 1, 0, 0.613885,0.0386815) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.196139,-0.0619553) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.300674,-0.0110462) , 
2, 0.0389804, 1, 0, 0.277962,-0.0807291) , 
2, 0.0332163, 1, 0, 0.489681,-0.00546924)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.810026,0.0447142) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.365746,-0.00970589) , 
2, 0.00554148, 1, 0, 0.409171,-0.0182905) , 
NN(
0, 
0, 
0, 2863.46, 1, -99, 0.98259,0.0626959) , 
1, 4.77431, 1, 0, 0.493863,0.00643292)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.402295,-0.0209337) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.234235,-0.00458087) , 
3, 0.283821, 1, 0, 0.327303,-0.0552101) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.969334,0.0596153) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.611588,-0.019484) , 
2, 0.0146824, 1, 0, 0.798446,0.0353238) , 
0, 1224.78, 1, 0, 0.472714,-0.0272682)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545573,-0.0114827) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.383603,0.00661262) , 
2, 0.0258602, 1, 0, 0.48013,-0.0139115) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.0772,0.100186) , 
1, 5.93705, 1, 0, 0.503222,-0.00617425)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.6755,0.0131238) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.257134,-0.0136527) , 
3, 0.308637, 1, 0, 0.542113,0.0150649) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.187137,-0.0457492) , 
2, 0.0978994, 1, 0, 0.520822,0.00429912)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.834765,0.0736359) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45707,-0.00205668) , 
3, 0.0370562, 1, 0, 0.48465,0.0109078) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.28807,0.318584) , 
1, 5.89742, 1, 0, 0.509886,0.0214626)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.177954,-0.0109746) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.220019,-0.0282192) , 
0, 779.144, 1, 0, 0.192673,-0.0621529) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545922,0.0181626) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.770197,-0.0174461) , 
0, 1288.44, 1, 0, 0.643566,0.0233002) , 
1, 2.69889, 1, 0, 0.515476,-0.000975417)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.297961,-0.0236989) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.215784,-0.002815) , 
3, 0.345686, 1, 0, 0.264026,-0.0613257) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.806998,0.0250465) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436642,-0.0131445) , 
2, 0.0328633, 1, 0, 0.704089,0.0368151) , 
0, 867.27, 1, 0, 0.49008,-0.0109122)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.818207,0.0369541) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.465157,-0.009722) , 
2, 0.0313715, 1, 0, 0.700397,0.0570669) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.444993,-0.0430466) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.348579,-0.00668093) , 
3, 0.21258, 1, 0, 0.368059,-0.0505835) , 
3, 0.160589, 1, 0, 0.492583,-0.0102477)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.559788,-0.101633) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.613255,-0.00897179) , 
3, 0.0495312, 1, 0, 0.604816,-0.0629164) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.228159,-0.00807984) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.728381,0.0185491) , 
1, 3.44002, 1, 0, 0.454759,0.014793) , 
2, 0.0111009, 1, 0, 0.508861,-0.0132248)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.379348,-0.0148793) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.849158,0.019224) , 
1, 4.70232, 1, 0, 0.437904,-0.0422454) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.782389,-0.114341) , 
1, 5.7648, 1, 0, 0.456575,-0.0475968)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.281665,-0.00149793) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.499248,-0.0272169) , 
1, 3.66163, 1, 0, 0.338475,-0.0338496) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.856642,0.0586295) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.866318,0.0128422) , 
1, 4.07077, 1, 0, 0.864223,0.0666868) , 
0, 1315.19, 1, 0, 0.484091,-0.00600417)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.180385,-0.0154874) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.387727,0.00548818) , 
0, 848.899, 1, 0, 0.231681,-0.0318462) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.647364,0.067852) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.732207,0.0149339) , 
1, 3.27848, 1, 0, 0.725888,0.0636518) , 
1, 3.10352, 1, 0, 0.509007,0.021743)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.107623,-0.0164325) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.555984,0.125103) , 
1, 1.83077, 1, 0, 0.33622,0.201622) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430813,-0.0038531) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.939333,0.0394429) , 
1, 4.68299, 1, 0, 0.526196,0.00353496) , 
0, 571.808, 1, 0, 0.514005,0.0162466)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.227371,-0.00853016) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.303293,-0.0374062) , 
1, 3.17959, 1, 0, 0.257693,-0.0819524) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.764225,-0.0118934) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.720446,0.0841663) , 
3, 0.295902, 1, 0, 0.756498,0.0367775) , 
0, 940.707, 1, 0, 0.483701,-0.028156)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.410983,-0.0102595) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.918752,0.028505) , 
1, 4.88723, 1, 0, 0.467265,-0.0264308) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.779787,-0.130518) , 
1, 5.99376, 1, 0, 0.481317,-0.0322065)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.239661,-0.0419358) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.172999,-0.00883535) , 
2, 0.00947429, 1, 0, 0.190386,-0.0670272) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.699022,0.00717738) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.125205,-0.0384987) , 
3, 0.579619, 1, 0, 0.645028,0.00841114) , 
1, 2.9382, 1, 0, 0.484759,-0.0181822)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0550103,-0.0440942) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.560241,0.00557431) , 
1, 1.56258, 1, 0, 0.52153,0.00914593) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.699838,-0.20153) , 
1, 5.97259, 1, 0, 0.5296,-0.00194355)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594296,-0.00947375) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.651569,0.0495599) , 
2, 0.0777062, 1, 0, 0.597588,-0.0189786) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.64766,0.0809197) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.247047,-0.00584195) , 
3, 0.374489, 1, 0, 0.320321,0.0449993) , 
3, 0.296251, 1, 0, 0.504394,0.00252534)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58395,-0.0315839) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.01895,0.0773094) , 
1, 4.8054, 1, 0, 0.677432,-0.0668756) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.653467,0.0225032) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420645,7.13269e-06) , 
2, 0.0144614, 1, 0, 0.494375,0.0229984) , 
2, 0.00555045, 1, 0, 0.522107,0.00938318)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.11431,-0.0446782) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.282423,-0.00699365) , 
0, 549.911, 1, 0, 0.250765,-0.0483536) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.796609,0.0108167) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.848924,0.0925385) , 
3, 0.388241, 1, 0, 0.800938,0.0603905) , 
1, 3.38178, 1, 0, 0.511087,0.0031003)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.33444,0.00805978) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.540288,-0.020052) , 
0, 917.488, 1, 0, 0.424923,-0.0173188) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.01508,0.0772305) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.902385,0.00150149) , 
0, 2101.67, 1, 0, 0.94006,0.0663031) , 
0, 1707.86, 1, 0, 0.515593,-0.00260047)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524627,0.00073215) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.529508,0.0623742) , 
2, 0.0748691, 1, 0, 0.524815,0.0108946) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.178133,-0.0504597) , 
2, 0.0980009, 1, 0, 0.497042,-0.0051601)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.87775,0.0866655) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.403814,-0.00571682) , 
3, 0.024848, 1, 0, 0.424508,-0.005991) , 
NN(
0, 
0, 
3, 0.138103, 1, -99, 1.04598,0.0936437) , 
1, 4.66132, 1, 0, 0.527487,0.0238411)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.885764,0.066893) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.530938,0.00604758) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.258948,-0.0272225) , 
2, 0.0738153, 1, 0, 0.50172,0.00733246) , 
3, 0.0247163, 1, 0, 0.522316,0.0174941)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.15369,0.136286) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.611857,0.00927274) , 
3, 0.0246877, 1, 0, 0.640508,0.0442039) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.328485,-0.00127212) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.465497,-0.0448686) , 
1, 4.59015, 1, 0, 0.362918,-0.045393) , 
2, 0.0296024, 1, 0, 0.537535,0.0109677)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.634144,-0.00140982) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.479375,0.0338863) , 
3, 0.288079, 1, 0, 0.598412,0.0235517) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.13877,-0.00482595) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.11975,-0.0480259) , 
1, 2.92664, 1, 0, 0.131285,-0.0813874) , 
3, 0.555578, 1, 0, 0.53096,0.00839867)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.09797,0.124169) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.673458,0.0148953) , 
2, 0.00554148, 1, 0, 0.728938,0.0748865) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.328692,-0.0187485) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.988315,0.0611113) , 
0, 2293.29, 1, 0, 0.359031,-0.0581655) , 
3, 0.135785, 1, 0, 0.479985,-0.0146595)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.668725,0.00087011) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.698568,0.0434093) , 
2, 0.0132456, 1, 0, 0.674621,0.0279641) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.30939,-0.00953211) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.635093,-0.101447) , 
1, 5.21018, 1, 0, 0.339506,-0.0507818) , 
2, 0.0185015, 1, 0, 0.501344,-0.0127529)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.152076,-0.042632) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.596986,-0.0120298) , 
0, 564.188, 1, 0, 0.548747,-0.0499575) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.44968,0.0237694) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.301516,-0.0160722) , 
2, 0.0687526, 1, 0, 0.40348,0.0381063) , 
2, 0.0259021, 1, 0, 0.496325,-0.0181785)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.373806,-0.007881) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.287488,0.0140707) , 
2, 0.0610194, 1, 0, 0.361366,-0.0188526) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.10013,0.125019) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.851934,0.00637154) , 
0, 1450.09, 1, 0, 0.885687,0.0741846) , 
0, 1268.62, 1, 0, 0.521993,0.00964974)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
3, 0.209374, 1, -99, 0.890106,0.064119) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.441017,-0.00254707) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.05874,0.101637) , 
1, 5.83841, 1, 0, 0.468592,-0.00220846) , 
2, 0.00555045, 1, 0, 0.51743,0.017879)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.129136,-0.0352093) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.515592,-0.00311349) , 
0, 551.132, 1, 0, 0.470317,-0.0225222) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.16735,0.220406) , 
1, 5.87739, 1, 0, 0.49115,-0.0151483)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.589997,0.00142067) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.444832,0.0664586) , 
3, 0.464382, 1, 0, 0.58342,0.0137399) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.122006,-0.000498137) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.126416,-0.0468523) , 
0, 779.737, 1, 0, 0.12418,-0.0858444) , 
3, 0.530163, 1, 0, 0.502691,-0.00376594)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.381369,-0.000387646) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.969902,0.0735158) , 
1, 4.12882, 1, 0, 0.417885,0.0129108) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.2582,0.570573) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.645109,-0.0697143) , 
2, 0.00554148, 1, 0, 0.720634,-0.111042) , 
1, 4.45793, 1, 0, 0.495836,-0.0190044)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.223338,-0.0188611) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.8135,0.0223748) , 
1, 2.45887, 1, 0, 0.717575,0.0415028) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.25975,0.00352615) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.524326,-0.0306884) , 
1, 3.38984, 1, 0, 0.372854,-0.0402456) , 
3, 0.160541, 1, 0, 0.502938,-0.00939708)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.223016,-0.0111699) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.733787,0.0157822) , 
1, 3.05741, 1, 0, 0.515611,0.0122437) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.737382,-0.201905) , 
1, 5.99916, 1, 0, 0.524569,0.00342841)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.771286,-0.0503045) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.656965,0.0134576) , 
2, 0.0037003, 1, 0, 0.667611,0.0305847) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.250036,-0.00304366) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.475849,-0.0616243) , 
0, 1294.22, 1, 0, 0.286917,-0.0407653) , 
3, 0.283357, 1, 0, 0.516552,0.00227304)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
2, 0.0221659, 1, -99, 0.941801,0.0840865) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.55604,-0.0461109) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.485506,0.00485133) , 
3, 0.0608468, 1, 0, 0.491885,0.00195576) , 
3, 0.0370412, 1, 0, 0.524025,0.0182768)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491931,0.0092745) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.153643,-0.0386254) , 
2, 0.0906046, 1, 0, 0.462294,0.0180989) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.461623,-0.137854) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.932179,-0.000324113) , 
0, 1835.33, 1, 0, 0.776275,-0.112432) , 
1, 4.98059, 1, 0, 0.504331,0.000623178)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.744322,-0.0212053) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.317591,-0.0525946) , 
2, 0.0312548, 1, 0, 0.600604,-0.102025) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.756891,0.0371635) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.373785,-0.00839941) , 
3, 0.154497, 1, 0, 0.468054,0.00613394) , 
3, 0.061857, 1, 0, 0.492598,-0.0138935)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.851348,0.0436152) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.384647,-0.00247168) , 
2, 0.0037003, 1, 0, 0.413758,0.000228059) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.796881,-0.031024) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.362312,-0.0930822) , 
3, 0.266904, 1, 0, 0.722225,-0.104336) , 
1, 4.45793, 1, 0, 0.491064,-0.0259771)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.6366,0.00700312) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59007,0.0894798) , 
2, 0.0279073, 1, 0, 0.633229,0.0407316) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.274543,-0.0327698) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.373207,0.0102822) , 
2, 0.0591189, 1, 0, 0.318346,-0.0520236) , 
2, 0.0332489, 1, 0, 0.524062,0.00857436)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545126,-0.0298663) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.311142,-0.00695972) , 
2, 0.00554723, 1, 0, 0.339132,-0.0348412) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.922208,0.0484851) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.78554,-0.0325365) , 
1, 4.96493, 1, 0, 0.85075,0.0344692) , 
1, 4.01749, 1, 0, 0.508942,-0.0118364)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.296981,-0.0205449) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.776175,-0.00565358) , 
0, 861.186, 1, 0, 0.58537,-0.0392012) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.223601,-0.000282602) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.818894,0.0531443) , 
1, 3.59996, 1, 0, 0.415703,0.0650562) , 
2, 0.0257393, 1, 0, 0.520564,0.000621145)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.454189,-0.00230817) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.656244,-0.07672) , 
1, 4.97925, 1, 0, 0.475237,-0.023556) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.09711,0.147374) , 
1, 5.75869, 1, 0, 0.501875,-0.0155552)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.869504,0.0574451) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.232352,-0.012775) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.722586,0.0147769) , 
1, 3.25275, 1, 0, 0.473978,0.000845761) , 
3, 0.0247129, 1, 0, 0.497556,0.00971176)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.8265,0.114138) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.822601,0.00744114) , 
0, 776.804, 1, 0, 0.823218,0.103321) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.377362,-0.0114653) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.09249,0.131959) , 
1, 5.40266, 1, 0, 0.413121,-0.0261312) , 
3, 0.111094, 1, 0, 0.515325,0.00613045)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.814763,0.00806999) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.346015,-0.0718406) , 
2, 0.0374508, 1, 0, 0.649371,-0.0808729) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511437,0.00300835) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.432671,0.0437821) , 
2, 0.0566559, 1, 0, 0.49991,0.0275617) , 
3, 0.0618004, 1, 0, 0.526822,0.00803689)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.813187,0.00597817) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.467559,-0.0295988) , 
2, 0.0184716, 1, 0, 0.63805,-0.0481575) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.622216,0.0341366) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.267612,-0.00227629) , 
3, 0.316411, 1, 0, 0.392608,0.0364572) , 
3, 0.197503, 1, 0, 0.510524,-0.0041936)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.133585,-0.0251463) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.397423,0.00248465) , 
0, 572.523, 1, 0, 0.341972,-0.010656) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.822017,-0.0209126) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.462708,-0.0705738) , 
2, 0.0382332, 1, 0, 0.740124,-0.0837616) , 
0, 1233.66, 1, 0, 0.475096,-0.0350992)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
3, 0.184163, 1, -99, 0.961732,0.0909425) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.815282,0.0395937) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.403584,-0.0158551) , 
3, 0.0370529, 1, 0, 0.434235,-0.0394065) , 
2, 0.00554722, 1, 0, 0.48764,-0.0145561)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.187611,-0.0151879) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.68106,0.00582215) , 
1, 2.94497, 1, 0, 0.478956,-0.00838622) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.12643,0.196568) , 
1, 5.79929, 1, 0, 0.508316,4.20322e-05)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.77762,0.0133658) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.502703,-0.0603794) , 
3, 0.0411295, 1, 0, 0.645969,-0.067179) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.385937,0.0039742) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.873738,0.0314718) , 
1, 4.19635, 1, 0, 0.508622,0.028821) , 
3, 0.0617374, 1, 0, 0.535708,0.009889)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626087,0.0543694) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.317988,0.0106909) , 
3, 0.0496666, 1, 0, 0.33816,0.0506418) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.526186,-0.0320261) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.962741,0.0225953) , 
0, 1807.56, 1, 0, 0.65365,-0.0718964) , 
1, 3.52175, 1, 0, 0.504771,-0.0140709)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.680184,-0.0356208) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380432,-0.0899128) , 
3, 0.0449846, 1, 0, 0.5748,-0.164211) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.521502,0.0105107) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.280111,-0.0191416) , 
2, 0.0527615, 1, 0, 0.469591,0.0103968) , 
3, 0.0617512, 1, 0, 0.489609,-0.022825)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.620041,-0.00617043) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.699188,-0.168175) , 
1, 5.09863, 1, 0, 0.641325,-0.0733818) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.381908,-0.00322586) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.974564,0.0636698) , 
1, 4.6647, 1, 0, 0.474984,0.0087692) , 
3, 0.0863109, 1, 0, 0.516953,-0.0119583)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.616927,0.0315197) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.255691,-0.00858145) , 
2, 0.00721625, 1, 0, 0.300797,-0.0076568) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.704084,-0.0315011) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.601978,0.0179832) , 
2, 0.0479791, 1, 0, 0.690953,-0.0586386) , 
0, 983.186, 1, 0, 0.477428,-0.0307372)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.284271,-0.055637) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.868457,-0.0385865) , 
1, 2.93617, 1, 0, 0.637971,-0.124536) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.263024,0.00437977) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.615506,-0.0201153) , 
1, 3.44767, 1, 0, 0.44268,-0.027372) , 
2, 0.00555045, 1, 0, 0.469257,-0.0405953)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.400061,0.00617866) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.0196,0.0983871) , 
1, 4.59943, 1, 0, 0.43775,0.0449616) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.892826,-0.0209435) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.567756,-0.0981346) , 
3, 0.258456, 1, 0, 0.824171,-0.0704225) , 
0, 1707.84, 1, 0, 0.517493,0.0211506)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.426396,0.0066713) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.656325,-0.0410036) , 
1, 4.43521, 1, 0, 0.47906,-0.00764769) , 
NN(
0, 
0, 
2, 0.0106228, 1, -99, 1.05627,0.121956) , 
0, 2449.34, 1, 0, 0.517531,0.00188137)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.360368,0.00093473) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.687321,-0.0220716) , 
1, 3.99263, 1, 0, 0.466541,-0.0183998) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.13103,0.314765) , 
1, 5.87335, 1, 0, 0.489273,-0.0123356)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.341937,0.0141712) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.477772,-0.0247616) , 
1, 3.66163, 1, 0, 0.386901,-0.0015839) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.931725,0.0805478) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.905987,0.0257436) , 
0, 1529.85, 1, 0, 0.910393,0.0819046) , 
0, 1315.22, 1, 0, 0.538009,0.0225153)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.264024,-0.00229551) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.679341,0.0354298) , 
1, 3.23815, 1, 0, 0.327723,0.0140357) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.784239,-0.0117162) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.406178,-0.0323443) , 
3, 0.259097, 1, 0, 0.680067,-0.055331) , 
1, 3.59171, 1, 0, 0.489466,-0.0178069)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.400613,-0.00750055) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.282817,0.0200567) , 
3, 0.283821, 1, 0, 0.340866,0.016305) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.804761,-0.00386284) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.417494,-0.0427668) , 
3, 0.22424, 1, 0, 0.667517,-0.0631204) , 
1, 3.67846, 1, 0, 0.48646,-0.0190963)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.225499,-0.00970407) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.749765,0.0189519) , 
1, 3.09277, 1, 0, 0.510143,0.0181912) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.779619,-0.2824) , 
1, 6.09316, 1, 0, 0.520974,0.0100254)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.405184,-0.016266) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.265423,0.0112687) , 
3, 0.345715, 1, 0, 0.363159,-0.0332842) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.21857,0.535601) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.839048,0.0146649) , 
2, 0.00553606, 1, 0, 0.902376,0.0700306) , 
1, 4.23214, 1, 0, 0.499868,-0.00709059)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.353828,-0.00993924) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.830292,0.0181228) , 
1, 4.20411, 1, 0, 0.457207,-0.0171545) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.77359,-0.174256) , 
1, 5.76272, 1, 0, 0.479307,-0.0277253)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.308523,-0.00532406) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.837221,0.0338459) , 
1, 3.61117, 1, 0, 0.500563,0.024251) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.678612,-0.153221) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.997571,0.0532773) , 
0, 2822.13, 1, 0, 0.790675,-0.130161) , 
1, 5.4075, 1, 0, 0.529821,0.00867888)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.155893,-0.0228266) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.218081,-0.0491967) , 
1, 3.05942, 1, 0, 0.176498,-0.113733) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.780583,0.0214929) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.250406,-0.0151826) , 
3, 0.370364, 1, 0, 0.646838,0.0313823) , 
0, 715.058, 1, 0, 0.475241,-0.0215609)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626208,-0.0446203) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.682921,0.020462) , 
3, 0.0289435, 1, 0, 0.674932,0.0359563) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.227667,-0.00378681) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.387415,-0.0461456) , 
1, 3.73691, 1, 0, 0.268582,-0.053537) , 
3, 0.259359, 1, 0, 0.500012,-0.00256759)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.489038,-0.0471327) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.926958,-0.0487232) , 
0, 1547.03, 1, 0, 0.633685,-0.115477) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.688629,0.0143364) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.329095,-0.00983842) , 
3, 0.136044, 1, 0, 0.443231,-0.00805587) , 
2, 0.00740059, 1, 0, 0.482073,-0.0299642)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.304333,-0.00143401) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421305,-0.0350128) , 
0, 960.849, 1, 0, 0.339116,-0.0430987) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.89504,0.0109116) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.960277,0.107994) , 
3, 0.297825, 1, 0, 0.903635,0.0926396) , 
0, 1294.22, 1, 0, 0.489641,-0.00690515)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.231605,-0.00703409) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.84702,0.0347309) , 
1, 2.76303, 1, 0, 0.652785,0.059053) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.176575,0.00682158) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.391306,-0.0248809) , 
1, 3.05487, 1, 0, 0.308953,-0.0546972) , 
2, 0.0314017, 1, 0, 0.526845,0.0173885)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.549795,-0.0880588) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.893044,0.0558693) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.446299,-0.0101974) , 
2, 0.00369815, 1, 0, 0.471965,-0.0231227) , 
3, 0.012349, 1, 0, 0.475786,-0.0330423)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.416432,-0.0235) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.271019,0.00298615) , 
3, 0.209615, 1, 0, 0.333117,-0.0328839) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.656322,-0.0167698) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.00102,0.0670996) , 
1, 4.35661, 1, 0, 0.882379,0.0592665) , 
0, 1305.32, 1, 0, 0.479462,-0.00833142)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.603982,-0.0140804) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.342497,-0.0499841) , 
2, 0.0183635, 1, 0, 0.564698,-0.0549351) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.297997,-0.00423132) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.02949,0.0807394) , 
0, 1804.31, 1, 0, 0.360395,0.00255183) , 
2, 0.0222018, 1, 0, 0.478872,-0.0307854)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.233454,-0.0018445) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59951,0.0517739) , 
1, 3.04744, 1, 0, 0.28215,0.0218277) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.816938,-0.00275127) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.441433,-0.0295302) , 
3, 0.242652, 1, 0, 0.697633,-0.0394953) , 
1, 3.28813, 1, 0, 0.496426,-0.0097983)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0514086,-0.0501054) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0743268,-0.0206185) , 
3, 0.395318, 1, 0, 0.0633775,-0.0899615) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.712408,0.0236636) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.355564,-0.00985243) , 
2, 0.0332489, 1, 0, 0.590278,0.0335634) , 
1, 2.20289, 1, 0, 0.504703,0.0135015)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.767519,-0.00707472) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.366969,-0.0399076) , 
2, 0.0293649, 1, 0, 0.626821,-0.0638728) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.265165,-0.00890238) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.732998,0.0170495) , 
1, 3.60443, 1, 0, 0.435247,-0.00148747) , 
3, 0.0863932, 1, 0, 0.482015,-0.0167174)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.414999,0.0259836) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.738204,-0.000827051) , 
0, 940.808, 1, 0, 0.602495,0.0372184) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.238298,-0.00478755) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0537354,-0.0377822) , 
2, 0.0170506, 1, 0, 0.113589,-0.0598383) , 
3, 0.530282, 1, 0, 0.514091,0.0196686)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.441832,0.0226352) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0889832,-0.0204039) , 
3, 0.530861, 1, 0, 0.34982,0.0484869) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.811636,-0.00402961) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.404975,-0.0399021) , 
3, 0.271419, 1, 0, 0.695045,-0.0461236) , 
0, 1063.7, 1, 0, 0.509506,0.00472416)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.569609,-0.0829749) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573759,-0.0227814) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.370323,-0.000844289) , 
2, 0.0164316, 1, 0, 0.460591,-0.030255) , 
3, 0.0247107, 1, 0, 0.468133,-0.0426197)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.225297,-0.00834099) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.821984,0.0305228) , 
1, 2.81308, 1, 0, 0.649943,0.0555685) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.142827,-0.0433397) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.173526,-0.00413969) , 
3, 0.497204, 1, 0, 0.167241,-0.0389603) , 
3, 0.45678, 1, 0, 0.533501,0.0327654)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626671,-0.0506294) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.423395,0.000862271) , 
2, 0.00369815, 1, 0, 0.441333,-0.00877766) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.0358,0.126142) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.582232,-0.154587) , 
2, 0.0129689, 1, 0, 0.766003,-0.144814) , 
1, 5.25188, 1, 0, 0.480529,-0.0252007)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.333074,0.0200149) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.678859,-0.0138198) , 
1, 3.5079, 1, 0, 0.499854,0.014092) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.667201,-0.194425) , 
1, 5.89953, 1, 0, 0.509959,-0.00186569)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.565081,-0.0134601) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.781706,-0.163547) , 
0, 1224.85, 1, 0, 0.667561,-0.0951652) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.442567,0.000784436) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.763487,-0.138099) , 
1, 5.87335, 1, 0, 0.458148,-0.00546391) , 
2, 0.00554722, 1, 0, 0.484577,-0.0167848)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.220353,-0.0152566) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.626998,0.00353362) , 
0, 766.164, 1, 0, 0.456227,-0.0144383) , 
NN(
0, 
0, 
3, 0.120079, 1, -99, 1.12448,0.152938) , 
1, 5.38498, 1, 0, 0.506164,0.00371165)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.259002,0.0904692) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.48071,0.00398668) , 
0, 539.83, 1, 0, 0.464777,0.0288155) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.960583,-0.00824359) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.673165,-0.105856) , 
2, 0.0128471, 1, 0, 0.821708,-0.0988178) , 
0, 2110.44, 1, 0, 0.506321,0.0139597)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.683272,0.00529036) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.594347,0.0629331) , 
2, 0.0610549, 1, 0, 0.67303,0.0380373) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.261755,-0.0577982) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.236901,-0.00462839) , 
3, 0.346067, 1, 0, 0.24049,-0.0454872) , 
3, 0.320909, 1, 0, 0.523424,0.00914807)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.925632,0.0831466) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.44014,-0.00475841) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.07532,0.114459) , 
1, 5.56417, 1, 0, 0.472472,-0.00373492) , 
3, 0.0246838, 1, 0, 0.495431,0.00823344)    );
   return;
};

// Clean up
inline void ReadBDT-0.4.6_fold9::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadBDT-0.4.6_fold9::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
