// Class: ReadBDT-0.4.6_fold3
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT-0.4.6_fold3
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.32/00       [401408]
Creator        : abennett
Date           : Thu Aug 22 15:59:53 2024
Host           : Linux 6772f6b99311 6.5.0-1022-azure #23~22.04.1-Ubuntu SMP Thu May 9 17:59:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /gluster/home/abennett/BDT_training
Training events: 17871
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "125" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "3%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "80" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e-01" [Learning rate for BoostType=Grad algorithm]
UseNvars: "2" [Size of the subset of variables used with RandomisedTree option]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "sdivsqrtsplusb" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 4
mjj                           mjj                           mjj                           m_{jj}                        GeV                               'D'    [500.083496094,7102.28710938]
JetGap                        JetGap                        JetGap                        #Delta y_{jj}                                                   'D'    [0.0204434599727,8.30311965942]
PtBalance                     PtBalance                     PtBalance                     pT_{balance}                                                    'D'    [1.2169821817e-09,0.149861991405]
centrality                    centrality                    centrality                    #xi(Z)                                                          'D'    [5.42057250641e-06,0.999970436096]
NSpec 1
eventNumber                   eventNumber                   eventNumber                   I                                                               'F'    [703,684984192]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new BDT-0.4.6_fold3Node

#ifndef BDT-0.4.6_fold3Node__def
#define BDT-0.4.6_fold3Node__def

class BDT-0.4.6_fold3Node {

public:

   // constructor of an essentially "empty" node floating in space
   BDT-0.4.6_fold3Node ( BDT-0.4.6_fold3Node* left,BDT-0.4.6_fold3Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT-0.4.6_fold3Node();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT-0.4.6_fold3Node* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT-0.4.6_fold3Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT-0.4.6_fold3Node*   fLeft;     // pointer to the left daughter node
   BDT-0.4.6_fold3Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   BDT-0.4.6_fold3Node::~BDT-0.4.6_fold3Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool BDT-0.4.6_fold3Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool BDT-0.4.6_fold3Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT-0.4.6_fold3 : public IClassifierReader {

 public:

   // constructor
   ReadBDT-0.4.6_fold3( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDT-0.4.6_fold3" ),
        fNvars( 4 )
   {
      // the training input variables
      const char* inputVars[] = { "mjj", "JetGap", "PtBalance", "centrality" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'D';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT-0.4.6_fold3() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[4];
   double fVmax[4];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[4];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT-0.4.6_fold3Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT-0.4.6_fold3::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT-0.4.6_fold3Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT-0.4.6_fold3Node*)current->GetRight();
         else current=(BDT-0.4.6_fold3Node*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
}

void ReadBDT-0.4.6_fold3::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.114158,-0.0771684) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.321344,-0.0357311) , 
1, 2.21216, 1, 0, 0.248931,-0.251069) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.68376,0.036752) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.23079,0.146158) , 
0, 2578.83, 1, 0, 0.740943,0.240943) , 
1, 3.30159, 1, 0, 0.490116,-0.00988398)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.183865,-0.0578842) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.402569,-0.0212852) , 
1, 2.99819, 1, 0, 0.27301,-0.214174) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.338186,-0.0276245) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.790064,0.0532633) , 
1, 3.17202, 1, 0, 0.717607,0.200564) , 
0, 940.707, 1, 0, 0.493222,-0.0087511)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.500681,0.00446912) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.24999,-0.0442657) , 
3, 0.209649, 1, 0, 0.337987,-0.134616) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.745098,0.0410459) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.14016,0.112836) , 
0, 2564.53, 1, 0, 0.799089,0.250039) , 
1, 3.9383, 1, 0, 0.498611,-0.000621271)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.170706,-0.0523118) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.478483,-0.00353229) , 
1, 2.42497, 1, 0, 0.392158,-0.0843125) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.19717,0.132082) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.753929,0.0383554) , 
2, 0.00536526, 1, 0, 0.820262,0.255088) , 
0, 1294.22, 1, 0, 0.526649,0.0223121)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.368388,-0.0212031) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.142422,-0.0601638) , 
3, 0.395066, 1, 0, 0.286812,-0.172678) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.824909,0.0504508) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.295631,-0.0441653) , 
3, 0.394584, 1, 0, 0.764354,0.189233) , 
0, 1060.11, 1, 0, 0.480467,-0.025914)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.269719,-0.0296376) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.117331,-0.0601928) , 
2, 0.0310221, 1, 0, 0.21118,-0.198788) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.988016,0.081067) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564447,0.00167967) , 
2, 0.00912869, 1, 0, 0.675493,0.105188) , 
1, 3.09745, 1, 0, 0.48197,-0.0215075)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.541453,0.0145659) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.27719,-0.0353172) , 
2, 0.0148012, 1, 0, 0.370718,-0.0850039) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.932866,0.0647255) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.411542,-0.03153) , 
3, 0.317181, 1, 0, 0.840239,0.214744) , 
0, 1385.77, 1, 0, 0.497576,-0.00401639)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.422431,0.00401976) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.150572,-0.0484031) , 
2, 0.00730262, 1, 0, 0.195676,-0.184777) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.740475,0.0321177) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.250512,-0.0451437) , 
3, 0.405716, 1, 0, 0.657761,0.086966) , 
1, 2.96819, 1, 0, 0.49084,-0.0111968)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.337879,-0.014058) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.04833,0.086676) , 
1, 3.1331, 1, 0, 0.750491,0.185944) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.363786,-0.0223151) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.920073,0.0573236) , 
0, 2040.13, 1, 0, 0.409473,-0.0757889) , 
2, 0.00925074, 1, 0, 0.494373,-0.0106277)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.452649,0.000593422) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.220323,-0.0336954) , 
2, 0.0166417, 1, 0, 0.315749,-0.0895888) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.843904,0.0415258) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.552228,-0.00885833) , 
3, 0.22675, 1, 0, 0.75533,0.112306) , 
1, 3.77976, 1, 0, 0.492961,-0.00819686)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503015,0.012521) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.273924,-0.0265453) , 
3, 0.111234, 1, 0, 0.326053,-0.0814227) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.84872,0.0406076) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.455889,-0.0167084) , 
3, 0.308194, 1, 0, 0.776423,0.124745) , 
0, 1077.75, 1, 0, 0.505354,0.000656388)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.674753,0.046792) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.291909,-0.0252754) , 
2, 0.00555045, 1, 0, 0.32858,-0.0837234) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.873241,0.0428263) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.345372,-0.0258205) , 
3, 0.406832, 1, 0, 0.820721,0.14439) , 
0, 1216.69, 1, 0, 0.502758,-0.00298952)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.39345,-0.00345935) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.11953,0.101811) , 
1, 3.1639, 1, 0, 0.7863,0.19437) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529803,0.00226369) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.19467,-0.0359194) , 
3, 0.32093, 1, 0, 0.405753,-0.0519698) , 
2, 0.00925074, 1, 0, 0.493101,0.00457304)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0605478,-0.0567752) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.262637,-0.0167268) , 
1, 1.56357, 1, 0, 0.223986,-0.103156) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.707278,0.0113539) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.766192,0.0506107) , 
3, 0.221202, 1, 0, 0.723384,0.0963834) , 
1, 2.9965, 1, 0, 0.52404,0.0167337)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.367659,0.000155279) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.164875,-0.0340747) , 
3, 0.123602, 1, 0, 0.198642,-0.118458) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.766368,0.0293057) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436098,-0.0185987) , 
2, 0.0424438, 1, 0, 0.693834,0.0760958) , 
1, 2.8973, 1, 0, 0.506064,0.00232369)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.518354,0.0261589) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.187565,-0.0338615) , 
3, 0.11126, 1, 0, 0.234234,-0.107237) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.756475,0.0304486) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.242678,-0.0260279) , 
3, 0.492491, 1, 0, 0.685938,0.0922422) , 
0, 716.667, 1, 0, 0.53069,0.0236824)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.494507,0.0190177) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.21945,-0.0307618) , 
3, 0.0495049, 1, 0, 0.24096,-0.115445) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.806256,0.0338214) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302785,-0.0260663) , 
3, 0.442583, 1, 0, 0.737427,0.0975957) , 
0, 867.325, 1, 0, 0.49609,-0.00596498)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.30116,0.188636) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.320476,-0.014365) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.74915,0.0157297) , 
0, 1060.11, 1, 0, 0.502582,-0.0104716) , 
2, 0.00369432, 1, 0, 0.537122,0.0227562)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.50144,-0.00435672) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.239644,-0.0291073) , 
3, 0.283941, 1, 0, 0.385363,-0.0636493) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.793467,-0.00703783) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.945974,0.0541147) , 
3, 0.0495355, 1, 0, 0.907026,0.127031) , 
0, 1655.23, 1, 0, 0.490797,-0.0251108)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.1599,-0.0331902) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.719101,0.0266884) , 
1, 2.14001, 1, 0, 0.628756,0.0639604) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.298178,-0.0195693) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.861415,0.0333885) , 
0, 1570.05, 1, 0, 0.366115,-0.0582915) , 
2, 0.0277522, 1, 0, 0.524026,0.0152114)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.415869,-0.00265226) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.200366,-0.0349547) , 
2, 0.0548283, 1, 0, 0.365457,-0.0425646) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.0093,0.0799241) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.841097,0.0206657) , 
0, 1446.42, 1, 0, 0.861366,0.0921833) , 
0, 1305.25, 1, 0, 0.512609,-0.00258062)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.303439,-0.0511351) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.262667,-0.0157578) , 
2, 0.00369815, 1, 0, 0.266753,-0.0797935) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.789103,0.0162604) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.207454,-0.0503061) , 
3, 0.450684, 1, 0, 0.73409,0.0300196) , 
1, 3.44767, 1, 0, 0.490822,-0.0271426)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.649141,0.0206565) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.325373,-0.0187562) , 
2, 0.0110944, 1, 0, 0.414759,-0.0333635) , 
NN(
0, 
0, 
2, 0.0265571, 1, -99, 1.03085,0.0766958) , 
0, 1830.13, 1, 0, 0.503538,0.00202361)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.169304,-0.027496) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.532374,-0.00222703) , 
1, 2.61161, 1, 0, 0.400596,-0.0436218) , 
NN(
0, 
0, 
0, 1913.06, 1, -99, 0.985402,0.0588782) , 
1, 4.5662, 1, 0, 0.517157,-0.00130524)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
3, 0.146541, 1, -99, 0.974689,0.0960716) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.460175,-0.00519525) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.487144,-0.130315) , 
1, 5.83841, 1, 0, 0.462162,-0.044053) , 
2, 0.00555045, 1, 0, 0.513205,-0.0113427)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.629382,-8.40034e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.870309,0.0775386) , 
3, 0.269558, 1, 0, 0.643503,0.0188632) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.20164,-0.0263525) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.255622,-0.0802964) , 
1, 4.04863, 1, 0, 0.209159,-0.134864) , 
3, 0.321077, 1, 0, 0.478415,-0.0395663)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58148,0.00935278) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.280232,-0.0274694) , 
2, 0.0333027, 1, 0, 0.474212,-0.0154763) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.34816,0.213758) , 
0, 2805.91, 1, 0, 0.504559,0.00176701)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.977989,0.0813657) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.584127,0.0061793) , 
3, 0.0248477, 1, 0, 0.610719,0.0381262) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.258937,-0.0138011) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.471383,-0.0571841) , 
1, 4.3956, 1, 0, 0.308218,-0.0918596) , 
2, 0.0333027, 1, 0, 0.50448,-0.0075249)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601434,0.0167434) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.305903,-0.0167727) , 
3, 0.160475, 1, 0, 0.400626,-0.0224066) , 
NN(
0, 
0, 
3, 0.142668, 1, -99, 1.07639,0.0944907) , 
1, 4.59363, 1, 0, 0.507935,0.0207371)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.270054,-0.0124766) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.779592,0.00909099) , 
1, 3.42017, 1, 0, 0.516825,-0.0110664) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.187624,-0.0537634) , 
2, 0.0980578, 1, 0, 0.500361,-0.020894)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.22569,-0.0180524) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.752115,0.0113145) , 
1, 3.19952, 1, 0, 0.523457,-0.00777681) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.253671,-0.0458325) , 
2, 0.0906046, 1, 0, 0.507175,-0.0180163)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.250983,-0.0332176) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.1701,0.162212) , 
1, 2.46746, 1, 0, 0.868202,0.149999) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.444214,-0.000158268) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.655633,-0.0798901) , 
1, 5.79664, 1, 0, 0.457623,-0.0128369) , 
2, 0.00555045, 1, 0, 0.504734,0.00584707)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.151112,-0.0361728) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.744927,0.0170801) , 
1, 1.84899, 1, 0, 0.694613,0.0382651) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430234,-0.0137981) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.114387,-0.0376273) , 
3, 0.554537, 1, 0, 0.353913,-0.0695827) , 
3, 0.160563, 1, 0, 0.490813,-0.0262472)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.297616,-0.0366258) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.773788,-0.00676213) , 
1, 3.53276, 1, 0, 0.599759,-0.069557) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.329946,-0.0018626) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.877511,0.0374562) , 
1, 3.98164, 1, 0, 0.492214,0.0277395) , 
3, 0.0740674, 1, 0, 0.516454,0.00580885)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952753,0.0873405) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.492089,-0.00555197) , 
2, 0.0042785, 1, 0, 0.530137,0.00427757) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.158169,-0.052407) , 
2, 0.086733, 1, 0, 0.492387,-0.0162423)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.666732,0.00773794) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.31802,-0.015131) , 
3, 0.222236, 1, 0, 0.496409,-0.0140196) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.163425,-0.0442261) , 
2, 0.0925074, 1, 0, 0.472456,-0.0244597)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.444821,0.00250626) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.698332,-0.0540014) , 
1, 5.11429, 1, 0, 0.469943,-0.00557149) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.15359,0.172428) , 
0, 2835.11, 1, 0, 0.497431,0.00433512)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.50973,-0.0197136) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.06578,0.113181) , 
0, 2502.55, 1, 0, 0.549935,-0.057304) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.555948,0.0397416) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.241327,-0.00865952) , 
3, 0.400494, 1, 0, 0.331587,0.0242232) , 
3, 0.296203, 1, 0, 0.480148,-0.0312466)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.296434,0.000664276) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.461685,-0.0237245) , 
1, 3.66102, 1, 0, 0.341736,-0.0253323) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.16192,0.133929) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.914727,0.0360218) , 
0, 1474.22, 1, 0, 0.952813,0.133696) , 
0, 1288.35, 1, 0, 0.506016,0.0174203)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.600923,-0.00611518) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.468701,0.0153505) , 
3, 0.214835, 1, 0, 0.54994,0.00794426) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.148507,-0.0386327) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.104572,-0.0230557) , 
2, 0.0270238, 1, 0, 0.12771,-0.099047) , 
3, 0.580267, 1, 0, 0.491198,-0.00694075)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.137039,-0.0271057) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.566765,0.00936691) , 
0, 572.331, 1, 0, 0.504267,0.0145324) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.634391,-0.122512) , 
1, 5.84899, 1, 0, 0.512571,-0.0018889)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0922571,-0.0455826) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.121413,-0.0172795) , 
2, 0.015049, 1, 0, 0.109557,-0.0926589) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543758,0.106719) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.606407,0.00285126) , 
0, 573.641, 1, 0, 0.603521,0.0248939) , 
1, 2.1788, 1, 0, 0.519522,0.00490397)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.786683,0.00844202) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.558358,0.0497334) , 
3, 0.296061, 1, 0, 0.730829,0.0610528) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.351167,-0.00406682) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.633125,-0.0603657) , 
1, 4.8872, 1, 0, 0.396986,-0.0407677) , 
2, 0.0129177, 1, 0, 0.519372,-0.00344055)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.167285,-0.0324483) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166538,-0.00264824) , 
2, 0.0277522, 1, 0, 0.166992,-0.0766324) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.772391,-0.00577747) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.633812,0.0206963) , 
2, 0.0129175, 1, 0, 0.694477,0.0377745) , 
1, 2.79123, 1, 0, 0.517349,-0.000642983)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.862936,0.0659381) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.6365,0.000201036) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.327549,-0.0177912) , 
3, 0.216876, 1, 0, 0.472218,-0.0320299) , 
3, 0.0247606, 1, 0, 0.493817,-0.0179223)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.401017,-0.00734407) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.566746,-0.0711378) , 
1, 5.14872, 1, 0, 0.410869,-0.0380229) , 
NN(
0, 
0, 
1, 5.81278, 1, -99, 1.03557,0.0842667) , 
0, 2029.92, 1, 0, 0.483816,-0.0172711)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.143647,-0.0279) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.737445,0.023305) , 
1, 2.20623, 1, 0, 0.663687,0.0542537) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.213807,-0.00652841) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.303947,-0.0579606) , 
1, 3.9659, 1, 0, 0.228118,-0.0560542) , 
3, 0.35795, 1, 0, 0.532905,0.0211332)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
0, 1547.26, 1, -99, 0.912168,0.0688083) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.608368,0.00695098) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.268423,-0.0176898) , 
3, 0.259298, 1, 0, 0.466696,-0.0112258) , 
2, 0.00555045, 1, 0, 0.520144,0.0110707)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.173628,-0.0342062) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.570803,-0.00385115) , 
0, 657.834, 1, 0, 0.448086,-0.0465408) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.24584,0.300161) , 
0, 2629.76, 1, 0, 0.481738,-0.0317378)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.60702,-0.0207876) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.743793,0.0293471) , 
3, 0.0515683, 1, 0, 0.68585,0.0251266) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.476463,-0.0476556) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.319356,-0.00765023) , 
2, 0.00922676, 1, 0, 0.361925,-0.0598049) , 
3, 0.160509, 1, 0, 0.487452,-0.0268924)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.941429,0.0547697) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.164534,-0.0251854) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.577547,-0.00144185) , 
0, 641.517, 1, 0, 0.480435,-0.0235771) , 
2, 0.00369077, 1, 0, 0.507683,-0.015554)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.06864,0.117103) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.576359,0.00254647) , 
2, 0.00555045, 1, 0, 0.638063,0.0359296) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.178825,-0.000675093) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28241,-0.0428844) , 
1, 3.04981, 1, 0, 0.229304,-0.0824902) , 
3, 0.333441, 1, 0, 0.500822,-0.00382967)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.88959,0.101272) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.861736,0.00699998) , 
1, 3.86072, 1, 0, 0.871919,0.182723) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.582966,-0.0105851) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354809,0.0133667) , 
3, 0.286757, 1, 0, 0.501285,-0.00654858) , 
3, 0.0370529, 1, 0, 0.532722,0.00950492)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.080218,-0.0277018) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.538509,0.132013) , 
1, 2.16781, 1, 0, 0.246073,0.158615) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.701981,-0.0544528) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.515757,0.0040899) , 
2, 0.00551556, 1, 0, 0.542221,-0.00283998) , 
0, 572.278, 1, 0, 0.514507,0.012269)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.664885,-0.000821543) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.764567,0.0568805) , 
3, 0.134811, 1, 0, 0.68528,0.0381779) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.329475,-0.0101275) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.546129,-0.189009) , 
0, 2304.95, 1, 0, 0.342071,-0.0515088) , 
3, 0.185159, 1, 0, 0.492019,-0.0123247)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.518051,-0.0101808) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.472724,0.032441) , 
2, 0.045358, 1, 0, 0.511789,-0.0134681) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.191413,-0.0430619) , 
2, 0.0919129, 1, 0, 0.485911,-0.0247874)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.352856,-0.00691934) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.890561,0.0419466) , 
0, 1315.47, 1, 0, 0.439442,-0.00311187) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.387139,-0.0737203) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.874074,-0.0156246) , 
0, 1765.8, 1, 0, 0.725797,-0.0992402) , 
1, 4.90209, 1, 0, 0.490403,-0.0202191)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.915008,0.0603986) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.578119,0.00419047) , 
3, 0.0495971, 1, 0, 0.621041,0.0327643) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.250461,-0.0253806) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.00009,0.0760984) , 
1, 4.68916, 1, 0, 0.317359,-0.0634129) , 
2, 0.0332169, 1, 0, 0.515213,-0.000751722)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.81168,-0.0113353) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.873044,0.119534) , 
3, 0.295347, 1, 0, 0.822771,0.116606) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.28514,0.00623256) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.581268,-0.0262502) , 
0, 995.101, 1, 0, 0.422256,-0.0293898) , 
2, 0.00740059, 1, 0, 0.495654,-0.0026348)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.425102,-0.0203869) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.969099,0.0444749) , 
0, 1575.19, 1, 0, 0.563806,-0.0394112) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469393,0.0396486) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.205187,-0.00336673) , 
3, 0.546264, 1, 0, 0.329835,0.0574744) , 
3, 0.34477, 1, 0, 0.504025,-0.0146562)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532665,-0.0493429) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.18928,0.286202) , 
1, 5.1828, 1, 0, 0.610801,-0.0985515) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529047,-0.0245141) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.447963,0.0145904) , 
3, 0.0742032, 1, 0, 0.46532,0.0199645) , 
2, 0.00924537, 1, 0, 0.506561,-0.0136327)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.550259,0.0389485) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.791312,0.00124705) , 
0, 858.633, 1, 0, 0.720409,0.0494428) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.303433,-0.00531582) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.67252,-0.0476367) , 
0, 1381.35, 1, 0, 0.377656,-0.0395201) , 
3, 0.13548, 1, 0, 0.492656,-0.00967128)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
3, 0.220635, 1, -99, 0.909754,0.0667319) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.148215,-0.0371955) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.478341,-0.00582492) , 
0, 572.301, 1, 0, 0.429821,-0.0366625) , 
2, 0.00555045, 1, 0, 0.478398,-0.0173837)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.144324,-0.0279973) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.537904,0.00246453) , 
0, 558.502, 1, 0, 0.486164,-0.00560368) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.821032,-0.255589) , 
0, 2864.59, 1, 0, 0.502856,-0.0125033)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.926117,0.0674693) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.619871,-0.0557143) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.433102,-0.00738044) , 
2, 0.00555045, 1, 0, 0.45763,-0.0402993) , 
3, 0.0247041, 1, 0, 0.483537,-0.0268318)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.370096,-0.0142947) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.09635,0.121028) , 
1, 3.06949, 1, 0, 0.805899,0.0953427) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.357158,0.00207968) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.660832,-0.0323167) , 
1, 4.58373, 1, 0, 0.424899,-0.0163937) , 
2, 0.00925074, 1, 0, 0.519836,0.0114487)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.40629,-0.00232261) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.512415,-0.0605115) , 
1, 4.54488, 1, 0, 0.419797,-0.0343077) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.0121,0.0762248) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.732732,-0.0141803) , 
2, 0.0273094, 1, 0, 0.94074,0.0719049) , 
0, 1707.84, 1, 0, 0.512862,-0.0153332)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.345905,0.00634854) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.658036,-0.0168325) , 
0, 1038.09, 1, 0, 0.478499,-0.00895123) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.07723,0.129663) , 
1, 5.89723, 1, 0, 0.503405,-0.00151317)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.440156,0.00237789) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.24006,0.233042) , 
0, 1949.37, 1, 0, 0.469319,0.0192327) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504031,-0.108819) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.98486,0.0292646) , 
0, 2641.35, 1, 0, 0.775354,-0.112333) , 
0, 2336.03, 1, 0, 0.500763,0.00571468)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.621993,-0.00779301) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.334489,-0.0529311) , 
2, 0.0164361, 1, 0, 0.555812,-0.0597188) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.306311,-0.00164163) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.08777,0.0985777) , 
1, 4.48008, 1, 0, 0.410686,0.0332526) , 
2, 0.0221889, 1, 0, 0.498925,-0.0232755)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.365626,-0.0439403) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.774292,-0.0258521) , 
1, 3.8392, 1, 0, 0.602934,-0.110271) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.724444,-0.0321148) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.448146,0.00652895) , 
2, 0.00554722, 1, 0, 0.481007,0.0108384) , 
3, 0.0494645, 1, 0, 0.498911,-0.00694603)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499992,0.00911186) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.108428,-0.0301127) , 
3, 0.592586, 1, 0, 0.435199,0.0133454) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.549201,-0.0680735) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.97279,0.038459) , 
0, 2015.18, 1, 0, 0.725222,-0.112134) , 
1, 4.59015, 1, 0, 0.500706,-0.0149966)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.11757,0.159303) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.494929,-0.014451) , 
2, 0.00273235, 1, 0, 0.519725,-0.0323032) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.243051,0.00766343) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.16431,0.0859877) , 
1, 3.91384, 1, 0, 0.390915,0.0766318) , 
2, 0.0442892, 1, 0, 0.495091,-0.0114701)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.68734,0.00168307) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.451347,0.0345254) , 
3, 0.234581, 1, 0, 0.594998,0.0467209) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.210503,0.00651575) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.283361,-0.0499007) , 
1, 3.3804, 1, 0, 0.24927,-0.0976091) , 
2, 0.0536543, 1, 0, 0.514852,0.0132626)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.826963,0.00020035) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.391346,-0.0729801) , 
3, 0.24634, 1, 0, 0.635241,-0.107513) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.406215,-0.00187854) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.714687,-0.066819) , 
1, 5.64925, 1, 0, 0.426193,-0.0153158) , 
2, 0.00738153, 1, 0, 0.469085,-0.0342327)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.70259,0.00218404) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.501884,0.0505475) , 
3, 0.296207, 1, 0, 0.646413,0.0515952) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.221877,-0.00565073) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.512061,-0.0360276) , 
0, 1035.06, 1, 0, 0.318645,-0.0562902) , 
2, 0.0258602, 1, 0, 0.50859,0.00623044)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.515684,0.00922156) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.128269,-0.0274363) , 
3, 0.518516, 1, 0, 0.42428,0.00679309) , 
NN(
0, 
0, 
0, 2600.62, 1, -99, 0.99273,0.0759047) , 
1, 4.59363, 1, 0, 0.535742,0.0396977)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.744726,0.0201381) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.416913,-0.00751255) , 
2, 0.0333027, 1, 0, 0.635811,0.028554) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.205133,0.00269345) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.298746,-0.0456343) , 
0, 984.353, 1, 0, 0.237225,-0.0518554) , 
3, 0.35807, 1, 0, 0.519942,0.00517884)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.437146,-0.0177238) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.921868,0.0230879) , 
0, 1646.6, 1, 0, 0.551078,-0.040714) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.599317,0.0615363) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.288815,-0.0166318) , 
2, 0.050399, 1, 0, 0.414699,0.0469413) , 
2, 0.0259021, 1, 0, 0.500364,-0.00811818)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.497891,-0.0928513) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.02015,0.153054) , 
0, 1386.01, 1, 0, 0.706051,-0.124441) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533094,0.00511112) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.19532,-0.0328119) , 
2, 0.0902624, 1, 0, 0.503311,0.00557293) , 
2, 0.00369815, 1, 0, 0.519484,-0.00479853)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.281207,-0.0112338) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.806897,0.0721577) , 
1, 3.60299, 1, 0, 0.322896,-0.0148768) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533873,-0.0376395) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.985931,0.0514366) , 
0, 1883.75, 1, 0, 0.665071,-0.0816355) , 
1, 3.83498, 1, 0, 0.461742,-0.0419658)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.440221,-0.00383191) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.579036,-0.0976586) , 
1, 5.24016, 1, 0, 0.452941,-0.0338216) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.26372,0.578979) , 
0, 2665.95, 1, 0, 0.485875,-0.020556)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.574943,0.00598934) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.619283,-0.0994115) , 
0, 1175.32, 1, 0, 0.602155,-0.126642) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529297,-0.00162083) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.372782,0.0254958) , 
2, 0.0610549, 1, 0, 0.509162,0.00528798) , 
3, 0.0370716, 1, 0, 0.520924,-0.0113986)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482847,0.00598733) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.832213,-0.113136) , 
0, 2110.42, 1, 0, 0.521574,0.00722534) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.203811,-0.0450731) , 
2, 0.0980009, 1, 0, 0.501863,-0.00250546)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.703664,0.0174642) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.688383,-0.129367) , 
1, 5.94295, 1, 0, 0.702108,0.0288092) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.243802,0.0101613) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.416187,-0.0298238) , 
1, 3.02553, 1, 0, 0.341084,-0.0505835) , 
3, 0.209664, 1, 0, 0.504004,-0.0147559)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.697018,-0.0577339) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.628582,0.0273114) , 
2, 0.00349387, 1, 0, 0.637681,0.0616676) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.253788,-0.0595094) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335958,-0.00972084) , 
2, 0.0358539, 1, 0, 0.322679,-0.0635547) , 
2, 0.0314525, 1, 0, 0.522328,0.0158115)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
3, 0.02025, 1, -99, 0.8985,0.072861) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.327401,-0.0171274) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.813994,0.00474044) , 
1, 4.11065, 1, 0, 0.459874,-0.0410014) , 
3, 0.0371759, 1, 0, 0.489593,-0.0217968)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
0, 1053.12, 1, -99, 0.863217,0.0504768) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465545,-0.0186536) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.396579,0.0215419) , 
2, 0.0465304, 1, 0, 0.450187,-0.034471) , 
2, 0.00555045, 1, 0, 0.496331,-0.0189613)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.526057,0.0126288) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.779314,-0.0610721) , 
1, 5.23546, 1, 0, 0.559666,0.0239194) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.13331,-0.0456726) , 
2, 0.09985, 1, 0, 0.523857,0.00878784)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.201955,-0.013284) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.744537,0.0224481) , 
1, 2.83554, 1, 0, 0.564994,0.031532) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.142659,-0.0159896) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.292322,-0.0396834) , 
0, 838.173, 1, 0, 0.208853,-0.0973196) , 
2, 0.0698638, 1, 0, 0.518276,0.0146295)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.217061,-0.00741995) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.489556,0.0448153) , 
1, 2.80621, 1, 0, 0.266706,0.0122679) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.757236,-0.00109251) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.347454,-0.0418674) , 
3, 0.301968, 1, 0, 0.65471,-0.0411412) , 
1, 3.10958, 1, 0, 0.50031,-0.0198879)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.344559,-0.106094) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.942735,-0.0926454) , 
1, 3.64454, 1, 0, 0.609354,-0.211119) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.410002,0.0119372) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.758485,-0.0284982) , 
0, 1454.77, 1, 0, 0.504805,0.0139287) , 
2, 0.0036907, 1, 0, 0.514264,-0.00643145)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.100936,-0.0686184) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.603198,-0.0303844) , 
0, 569.312, 1, 0, 0.542874,-0.106524) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.640744,0.0249821) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.283851,-0.00684087) , 
3, 0.160832, 1, 0, 0.402936,0.0152032) , 
2, 0.0166513, 1, 0, 0.471208,-0.0441847)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.547259,-0.0300857) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.395018,0.00962526) , 
2, 0.00913805, 1, 0, 0.439061,-0.00151288) , 
NN(
0, 
0, 
3, 0.194725, 1, -99, 0.91773,0.0430166) , 
1, 4.82644, 1, 0, 0.516521,0.0141408)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.03748,0.127532) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.613721,0.00844421) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.347454,-0.0162024) , 
2, 0.0178881, 1, 0, 0.46569,-0.0187731) , 
2, 0.00364966, 1, 0, 0.496794,0.00208092)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.104718,-0.0532281) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.489155,-0.00241873) , 
0, 527.147, 1, 0, 0.462383,-0.0201384) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.2165,0.581046) , 
0, 2692.33, 1, 0, 0.495337,-0.00873415)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545912,-0.000723742) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.09415,0.194449) , 
0, 2004.95, 1, 0, 0.632682,0.0194886) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.207641,0.0225158) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.220008,-0.0434146) , 
1, 2.72, 1, 0, 0.214148,-0.0575641) , 
3, 0.370252, 1, 0, 0.507403,-0.00357541)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.582541,-0.00401673) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.319803,-0.0336179) , 
2, 0.0284715, 1, 0, 0.531314,-0.0320218) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.261416,0.00625093) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.748302,0.0480997) , 
1, 4.05765, 1, 0, 0.365726,0.0526158) , 
2, 0.0481039, 1, 0, 0.499779,-0.0159032)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.530524,0.0178307) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.641034,-0.0607337) , 
0, 968.421, 1, 0, 0.608654,-0.0869686) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.431843,0.00337055) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.834369,-0.110479) , 
0, 2219.93, 1, 0, 0.466741,0.00127075) , 
3, 0.0617512, 1, 0, 0.491184,-0.0139276)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.217999,-0.0430823) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.227647,0.000502333) , 
3, 0.0988417, 1, 0, 0.225752,-0.0338805) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.858758,0.114876) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.778862,0.0197138) , 
0, 716.462, 1, 0, 0.784912,0.0887605) , 
1, 3.10591, 1, 0, 0.530292,0.0329144)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0202224,-0.057285) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.451874,-0.000642394) , 
1, 1.52223, 1, 0, 0.408609,-0.0168626) , 
NN(
0, 
0, 
2, 0.0147061, 1, -99, 0.976716,0.0687439) , 
1, 4.52598, 1, 0, 0.513611,0.00990602)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.619333,0.0246234) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.349631,-0.00152881) , 
2, 0.0203398, 1, 0, 0.476346,0.0349333) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.985876,0.0387594) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.559636,-0.0718416) , 
2, 0.0143594, 1, 0, 0.742214,-0.0997029) , 
1, 4.7306, 1, 0, 0.537451,0.0039897)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.324478,-0.00385541) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.758829,0.0260044) , 
0, 1097.55, 1, 0, 0.442082,0.0125246) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.91011,-0.132613) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.629027,-0.146611) , 
2, 0.0147874, 1, 0, 0.79127,-0.143869) , 
0, 1968.83, 1, 0, 0.493887,-0.0106776)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.186771,-0.012914) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.218846,-0.0524931) , 
1, 3.21915, 1, 0, 0.194989,-0.0894466) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.617581,0.00817916) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.778435,-0.063496) , 
1, 5.22761, 1, 0, 0.645316,0.00440557) , 
0, 712.256, 1, 0, 0.482261,-0.0295767)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
3, 0.171589, 1, -99, 0.842143,0.0444075) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.43349,-0.0096959) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.0724,0.14) , 
1, 5.89083, 1, 0, 0.454958,-0.0262778) , 
2, 0.00553615, 1, 0, 0.498361,-0.0120332)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.0184,0.0890985) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.470579,-0.0934149) , 
3, 0.160026, 1, 0, 0.669968,-0.120726) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499625,-0.000308159) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.250447,-0.0266125) , 
2, 0.0535689, 1, 0, 0.439533,-0.0215854) , 
2, 0.00554148, 1, 0, 0.470806,-0.0350399)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.484121,-0.0183417) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.02432,0.0892244) , 
0, 1861.49, 1, 0, 0.584894,-0.0382899) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.741515,0.103611) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.260803,0.00743477) , 
2, 0.0073963, 1, 0, 0.308871,0.0680948) , 
3, 0.295827, 1, 0, 0.491992,-0.00248367)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.630011,-0.0446275) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.458607,0.000845603) , 
2, 0.00369432, 1, 0, 0.472102,-0.00652255) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.481953,-0.0996587) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.04229,0.176383) , 
0, 2452.44, 1, 0, 0.705121,-0.146096) , 
1, 5.29415, 1, 0, 0.503987,-0.0256213)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.405123,0.00414599) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.620419,-0.080269) , 
0, 1815.16, 1, 0, 0.415302,0.00438262) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519161,-0.0605751) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.9804,0.0380623) , 
0, 2000.9, 1, 0, 0.729054,-0.0956787) , 
1, 4.52598, 1, 0, 0.495093,-0.0210642)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.358247,-0.0103923) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.627974,-0.126868) , 
0, 1856.07, 1, 0, 0.368252,-0.0430093) , 
NN(
0, 
0, 
0, 2352.28, 1, -99, 0.981423,0.0836636) , 
1, 4.61988, 1, 0, 0.465691,-0.00889385)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58375,-0.0118419) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.292128,0.0202836) , 
3, 0.296306, 1, 0, 0.476604,-0.00078055) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.511801,-0.139799) , 
1, 5.87957, 1, 0, 0.479341,-0.0252888)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.634402,-0.00494408) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.300341,-0.0356873) , 
3, 0.254658, 1, 0, 0.526202,-0.0509716) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.378396,0.0607027) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.141899,-0.0198804) , 
3, 0.691799, 1, 0, 0.260886,0.0570765) , 
3, 0.469011, 1, 0, 0.479563,-0.0319781)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.198385,-0.029933) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.650215,-0.00205436) , 
0, 720.395, 1, 0, 0.513767,-0.0353931) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.308772,0.0283199) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.556064,-0.0173624) , 
1, 4.11271, 1, 0, 0.37654,0.0461306) , 
2, 0.0407033, 1, 0, 0.478929,-0.0146963)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.69811,0.00854994) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.374302,-0.0174063) , 
2, 0.0314017, 1, 0, 0.588861,-0.00574739) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.703013,0.0592092) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.27697,0.011186) , 
3, 0.38853, 1, 0, 0.397702,0.0797003) , 
3, 0.271616, 1, 0, 0.522953,0.023713)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.398741,0.00401533) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.680731,-0.0514927) , 
0, 1727.44, 1, 0, 0.415806,0.00560551) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.741176,-0.066759) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.794087,0.0428189) , 
2, 0.0251289, 1, 0, 0.752844,-0.0615351) , 
1, 4.52646, 1, 0, 0.492656,-0.00970362)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.239236,-0.00642757) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.384929,-0.0349748) , 
1, 3.18952, 1, 0, 0.274179,-0.0488537) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.917935,0.0461232) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439526,-0.015847) , 
2, 0.0498733, 1, 0, 0.817613,0.0722507) , 
1, 3.58288, 1, 0, 0.496695,0.000734014)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.454366,-0.0570508) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.300835,-0.00510725) , 
2, 0.00547696, 1, 0, 0.320807,-0.0388986) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.832908,-0.0082798) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.885297,0.0502984) , 
3, 0.0864473, 1, 0, 0.866274,0.0837749) , 
1, 3.80389, 1, 0, 0.513326,0.00439804)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.830554,-0.0207185) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.403339,-0.0946165) , 
3, 0.281921, 1, 0, 0.6878,-0.10759) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.340806,-0.00423462) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.856506,0.0220709) , 
0, 1429.77, 1, 0, 0.466286,0.00106457) , 
2, 0.00555045, 1, 0, 0.497207,-0.0141027)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.677533,0.104255) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.825147,0.0110487) , 
0, 712.344, 1, 0, 0.805063,0.0772087) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.339098,-0.00535649) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.710559,-0.082265) , 
0, 1930.4, 1, 0, 0.384963,-0.0354094) , 
2, 0.00924537, 1, 0, 0.478816,-0.0102498)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.628476,-0.0233834) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.560034,0.0119705) , 
3, 0.0411725, 1, 0, 0.569926,0.0216042) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.12023,0.00172744) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.123422,-0.0474465) , 
1, 2.88296, 1, 0, 0.121536,-0.0669064) , 
3, 0.555551, 1, 0, 0.500385,0.00787705)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.298203,0.00128911) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45281,-0.0364841) , 
1, 3.68187, 1, 0, 0.344843,-0.0418497) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.890562,0.0574189) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.87361,0.00608766) , 
0, 1657.75, 1, 0, 0.878549,0.0571014) , 
0, 1286.79, 1, 0, 0.503052,-0.0125173)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.310285,0.0025081) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.51715,-0.0366885) , 
0, 1535.55, 1, 0, 0.322398,0.000582955) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.63699,-0.030617) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.08839,1.82444) , 
0, 2788.17, 1, 0, 0.682338,-0.0711776) , 
1, 3.70335, 1, 0, 0.47817,-0.0304729)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.339559,0.214722) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.212005,-0.0107075) , 
0, 537.12, 1, 0, 0.269247,0.173326) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.445071,-0.00431823) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.979988,0.0719622) , 
0, 1701.93, 1, 0, 0.556546,0.00886646) , 
0, 571.643, 1, 0, 0.532014,0.0229093)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.25994,-0.0183822) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.748368,0.0141044) , 
0, 858.381, 1, 0, 0.528558,-0.00874374) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.43231,0.145613) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.497402,0.00917713) , 
0, 829.251, 1, 0, 0.46422,0.169549) , 
2, 0.070192, 1, 0, 0.522462,0.00814816)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.387492,-0.011391) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.15189,0.133878) , 
1, 4.58023, 1, 0, 0.420529,-0.0207417) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.676831,-0.104511) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.877334,0.0618929) , 
3, 0.211877, 1, 0, 0.711295,-0.131577) , 
1, 4.88134, 1, 0, 0.475026,-0.041515)    );
   return;
};

// Clean up
inline void ReadBDT-0.4.6_fold3::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadBDT-0.4.6_fold3::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
