// Class: ReadBDT-0.4.6_fold7
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT-0.4.6_fold7
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.32/00       [401408]
Creator        : abennett
Date           : Thu Aug 22 16:00:03 2024
Host           : Linux 6772f6b99311 6.5.0-1022-azure #23~22.04.1-Ubuntu SMP Thu May 9 17:59:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /gluster/home/abennett/BDT_training
Training events: 17885
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "125" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "3%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "80" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e-01" [Learning rate for BoostType=Grad algorithm]
UseNvars: "2" [Size of the subset of variables used with RandomisedTree option]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "sdivsqrtsplusb" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 4
mjj                           mjj                           mjj                           m_{jj}                        GeV                               'D'    [500.083496094,7102.28710938]
JetGap                        JetGap                        JetGap                        #Delta y_{jj}                                                   'D'    [0.0204434599727,8.30311965942]
PtBalance                     PtBalance                     PtBalance                     pT_{balance}                                                    'D'    [1.2169821817e-09,0.149861991405]
centrality                    centrality                    centrality                    #xi(Z)                                                          'D'    [5.42057250641e-06,0.999970436096]
NSpec 1
eventNumber                   eventNumber                   eventNumber                   I                                                               'F'    [703,684984192]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new BDT-0.4.6_fold7Node

#ifndef BDT-0.4.6_fold7Node__def
#define BDT-0.4.6_fold7Node__def

class BDT-0.4.6_fold7Node {

public:

   // constructor of an essentially "empty" node floating in space
   BDT-0.4.6_fold7Node ( BDT-0.4.6_fold7Node* left,BDT-0.4.6_fold7Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT-0.4.6_fold7Node();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT-0.4.6_fold7Node* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT-0.4.6_fold7Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT-0.4.6_fold7Node*   fLeft;     // pointer to the left daughter node
   BDT-0.4.6_fold7Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   BDT-0.4.6_fold7Node::~BDT-0.4.6_fold7Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool BDT-0.4.6_fold7Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool BDT-0.4.6_fold7Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT-0.4.6_fold7 : public IClassifierReader {

 public:

   // constructor
   ReadBDT-0.4.6_fold7( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDT-0.4.6_fold7" ),
        fNvars( 4 )
   {
      // the training input variables
      const char* inputVars[] = { "mjj", "JetGap", "PtBalance", "centrality" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'D';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT-0.4.6_fold7() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[4];
   double fVmax[4];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[4];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT-0.4.6_fold7Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT-0.4.6_fold7::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT-0.4.6_fold7Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT-0.4.6_fold7Node*)current->GetRight();
         else current=(BDT-0.4.6_fold7Node*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
}

void ReadBDT-0.4.6_fold7::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.20984,-0.0580321) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.453864,-0.00922723) , 
0, 708.574, 1, 0, 0.330405,-0.169595) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.736656,0.0473311) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.09602,0.119204) , 
0, 1906.69, 1, 0, 0.853719,0.353719) , 
1, 3.81195, 1, 0, 0.528106,0.0281063)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.2958,-0.0370846) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.16821,-0.0627183) , 
3, 0.309243, 1, 0, 0.223726,-0.257306) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.16876,0.127274) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.574927,0.0119647) , 
2, 0.00553615, 1, 0, 0.642493,0.1247) , 
1, 3.00585, 1, 0, 0.486959,-0.0171805)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.178281,-0.0557636) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.485518,-0.00280679) , 
1, 2.69636, 1, 0, 0.355316,-0.125158) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.42632,0.172032) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.855259,0.0628275) , 
2, 0.00550591, 1, 0, 0.927177,0.375492) , 
1, 4.11065, 1, 0, 0.512297,0.0122747)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.458265,-0.00697501) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.172189,-0.0571194) , 
3, 0.456231, 1, 0, 0.384693,-0.0977602) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.862402,0.0586141) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.338908,-0.0378069) , 
3, 0.406788, 1, 0, 0.809405,0.234206) , 
0, 1315.17, 1, 0, 0.514688,0.00384753)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504762,0.0087566) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.238282,-0.0412989) , 
3, 0.0866653, 1, 0, 0.274488,-0.168828) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.685739,0.0272055) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.02998,0.0891883) , 
1, 4.56974, 1, 0, 0.824926,0.250128) , 
1, 3.50094, 1, 0, 0.521377,0.0190869)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421584,0.000188749) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.203166,-0.0432427) , 
2, 0.00736231, 1, 0, 0.242879,-0.170439) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.97054,0.0748496) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.594299,0.00661087) , 
2, 0.0110723, 1, 0, 0.727945,0.14083) , 
1, 3.18493, 1, 0, 0.510269,0.00114653)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.320282,-0.0216459) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.791852,0.0420957) , 
0, 744.661, 1, 0, 0.656059,0.109116) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.424601,-0.0047416) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.178646,-0.0536178) , 
2, 0.0129435, 1, 0, 0.245378,-0.191636) , 
3, 0.320994, 1, 0, 0.514418,0.00538865)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.376573,-0.015125) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.866496,0.0489662) , 
1, 3.49355, 1, 0, 0.672152,0.101783) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.485903,-0.00242559) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.266069,-0.0393501) , 
2, 0.0166082, 1, 0, 0.357344,-0.112852) , 
3, 0.18516, 1, 0, 0.493928,-0.0197293)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.765135,0.0375804) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336824,-0.023597) , 
3, 0.30839, 1, 0, 0.629513,0.0789934) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482156,-0.00908569) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.207775,-0.0468657) , 
3, 0.246573, 1, 0, 0.353646,-0.125128) , 
2, 0.0147926, 1, 0, 0.469418,-0.0394651)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0977144,-0.0557684) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.240483,-0.027902) , 
1, 1.53882, 1, 0, 0.204745,-0.158748) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.730746,0.0307576) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.283413,-0.0493547) , 
2, 0.0811969, 1, 0, 0.687441,0.102745) , 
1, 2.79649, 1, 0, 0.520214,0.0121525)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465451,0.00127325) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.123501,-0.0511591) , 
3, 0.591386, 1, 0, 0.403063,-0.0362651) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.20177,0.129172) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.798316,0.0346027) , 
2, 0.00550591, 1, 0, 0.867937,0.205207) , 
0, 1315.21, 1, 0, 0.538461,0.0340655)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.627308,0.0208604) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336781,-0.0242088) , 
2, 0.00924537, 1, 0, 0.400139,-0.06606) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.05561,0.088473) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.84789,0.0292269) , 
1, 5.51912, 1, 0, 0.956629,0.235447) , 
0, 1722.73, 1, 0, 0.49414,-0.0151299)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.762174,0.0288722) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.12376,0.118345) , 
2, 0.003557, 1, 0, 0.889039,0.233525) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.302055,-0.0234364) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.702637,0.0153748) , 
0, 1145.07, 1, 0, 0.436412,-0.0486722) , 
2, 0.00554148, 1, 0, 0.491142,-0.0145498)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.918903,0.0540494) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.549523,-0.00261919) , 
2, 0.00734121, 1, 0, 0.625417,0.0292998) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.257433,-0.0296012) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0920151,-0.0525656) , 
3, 0.831944, 1, 0, 0.235853,-0.141046) , 
3, 0.32088, 1, 0, 0.490502,-0.0296948)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.373018,-0.0069289) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.168774,-0.0363104) , 
3, 0.172995, 1, 0, 0.217273,-0.123934) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.733186,0.0156205) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.442375,-0.0169183) , 
2, 0.0332169, 1, 0, 0.648655,0.0222241) , 
1, 2.98585, 1, 0, 0.490433,-0.0313838)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.218852,-0.0297267) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.471075,-0.00228817) , 
0, 690.194, 1, 0, 0.354341,-0.0652106) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.01011,0.0770553) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.608681,-0.00522594) , 
2, 0.0220236, 1, 0, 0.858937,0.166729) , 
0, 1233.66, 1, 0, 0.512081,0.00729517)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.696889,0.0411994) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335636,-0.0188415) , 
3, 0.037115, 1, 0, 0.355478,-0.0681459) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.01889,0.0918426) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.8981,0.0413981) , 
0, 1530.29, 1, 0, 0.917543,0.181047) , 
0, 1315.22, 1, 0, 0.512266,0.00136624)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.216179,-0.0339585) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.774844,0.0247988) , 
1, 2.79649, 1, 0, 0.676436,0.0533124) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.399762,-0.0122862) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.13884,-0.0426964) , 
3, 0.53691, 1, 0, 0.317742,-0.0893274) , 
3, 0.234619, 1, 0, 0.507171,-0.0139981)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0782601,-0.0606368) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.111579,-0.0326182) , 
3, 0.406394, 1, 0, 0.094639,-0.18756) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.65567,0.0127029) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.253466,-0.0243723) , 
3, 0.370413, 1, 0, 0.548627,0.0113021) , 
1, 1.86104, 1, 0, 0.497138,-0.0112518)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.701821,0.0173542) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.225078,-0.024016) , 
3, 0.419338, 1, 0, 0.600131,0.0325808) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.508394,-0.00743468) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.198339,-0.0373308) , 
3, 0.160989, 1, 0, 0.294242,-0.119747) , 
2, 0.0332833, 1, 0, 0.490593,-0.0219675)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.147081,-0.0397316) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.301827,-0.00831998) , 
0, 587.082, 1, 0, 0.227426,-0.0932513) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.566777,0.0118538) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.715309,-0.0216691) , 
1, 4.45793, 1, 0, 0.623332,0.00564632) , 
0, 720.395, 1, 0, 0.502909,-0.0244356)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.775664,0.0326936) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.435523,-0.0119829) , 
2, 0.00369815, 1, 0, 0.462059,-0.0358251) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.10619,0.10098) , 
0, 2645.57, 1, 0, 0.49259,-0.0207668)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0672923,-0.0544539) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.630168,0.0145464) , 
1, 1.56637, 1, 0, 0.603336,0.0450099) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0805546,-0.0534706) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.178938,-0.0104165) , 
3, 0.739136, 1, 0, 0.115643,-0.141929) , 
3, 0.53059, 1, 0, 0.516314,0.0116531)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.224001,-0.0363789) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.183396,-0.0175278) , 
3, 0.236038, 1, 0, 0.198697,-0.0997872) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.815074,0.0247273) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.435546,-0.0162431) , 
3, 0.233564, 1, 0, 0.686379,0.035248) , 
1, 3.03554, 1, 0, 0.482519,-0.0211992)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.1385,0.140893) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.623922,0.00811088) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.20907,-0.0245) , 
3, 0.333163, 1, 0, 0.488598,-0.00852204) , 
2, 0.00369815, 1, 0, 0.525091,0.0140447)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.538513,0.0061812) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.606492,-0.0778369) , 
1, 5.99884, 1, 0, 0.542492,0.00933573) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.223148,-0.0510473) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.271422,-0.0262031) , 
2, 0.0607621, 1, 0, 0.25743,-0.140692) , 
2, 0.0536231, 1, 0, 0.480841,-0.0231114)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469384,-0.00149176) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.222111,-0.03198) , 
2, 0.0475178, 1, 0, 0.409929,-0.0354976) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.05346,0.08249) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.793559,7.40292e-05) , 
3, 0.148098, 1, 0, 0.948583,0.128631) , 
0, 1885.79, 1, 0, 0.487487,-0.0118655)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.06618,0.0898222) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.584742,0.00186931) , 
3, 0.0247154, 1, 0, 0.615701,0.0206864) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.32722,-0.0273028) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336524,-0.00849348) , 
2, 0.0395266, 1, 0, 0.331472,-0.0760582) , 
2, 0.0184716, 1, 0, 0.473949,-0.0275624)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507159,0.0255982) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.202161,-0.0236346) , 
3, 0.110978, 1, 0, 0.24891,-0.0578155) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.225027,-0.019675) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.759183,0.020987) , 
1, 2.59266, 1, 0, 0.679937,0.0536596) , 
0, 744.61, 1, 0, 0.524074,0.0133493)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.496346,-0.00175895) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.634497,-0.0715697) , 
1, 5.97259, 1, 0, 0.504099,-0.0171895) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.153804,-0.0504138) , 
2, 0.0974416, 1, 0, 0.477738,-0.0308829)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
1, 4.88925, 1, -99, 0.938638,0.0776659) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.562541,0.00368033) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.14948,-0.0307169) , 
3, 0.381769, 1, 0, 0.438058,-0.020785) , 
2, 0.0073963, 1, 0, 0.522343,0.023152)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.05274,0.10025) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.585415,0.000252433) , 
2, 0.00553615, 1, 0, 0.641523,0.0265388) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.220485,-0.00942378) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.340954,-0.0457693) , 
1, 3.88934, 1, 0, 0.249322,-0.0703607) , 
3, 0.283976, 1, 0, 0.480035,-0.0133594)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.581994,-0.0303079) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.442696,0.000666529) , 
3, 0.0864977, 1, 0, 0.476693,-0.0244655) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.07194,0.0919534) , 
0, 2717.03, 1, 0, 0.503317,-0.0137854)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.539111,-0.00581889) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.03539,0.0776718) , 
0, 1760.42, 1, 0, 0.653512,0.0231147) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.328556,-0.0125498) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.536844,-0.0876863) , 
0, 2316.65, 1, 0, 0.341304,-0.0604067) , 
3, 0.172894, 1, 0, 0.466663,-0.0268708)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.754439,0.0310452) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.60971,-0.0895282) , 
1, 5.75381, 1, 0, 0.734005,0.0639423) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.311019,-0.0160571) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.955536,0.055554) , 
1, 4.98054, 1, 0, 0.360492,-0.0430529) , 
3, 0.148192, 1, 0, 0.488566,-0.00636513)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0571862,-0.0624293) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0771716,-0.0340996) , 
3, 0.347809, 1, 0, 0.0701623,-0.145345) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.845347,0.0338098) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.455733,-0.00592225) , 
2, 0.00738864, 1, 0, 0.528068,-0.00115491) , 
1, 1.65663, 1, 0, 0.48362,-0.0151511)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.865224,0.0450322) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.508274,0.00127116) , 
2, 0.00657216, 1, 0, 0.586273,0.0321027) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.333232,-0.0360954) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.276304,-0.00915504) , 
3, 0.0990818, 1, 0, 0.292123,-0.0665489) , 
2, 0.0332833, 1, 0, 0.490975,0.000141636)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.148806,-0.0279916) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.532051,-0.00353783) , 
1, 2.21076, 1, 0, 0.471359,-0.0255685) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.02685,0.0765725) , 
1, 5.93705, 1, 0, 0.492214,-0.0160803)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.229497,-0.0145109) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.717895,0.0138616) , 
1, 3.0881, 1, 0, 0.52251,0.00905719) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.217367,-0.0396965) , 
2, 0.0905108, 1, 0, 0.501609,-0.00186085)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58092,0.00982033) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.10285,0.116049) , 
0, 2409.47, 1, 0, 0.626066,0.0539944) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.157684,-0.0440876) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.154667,-0.0109746) , 
2, 0.0111403, 1, 0, 0.155635,-0.0783227) , 
3, 0.432119, 1, 0, 0.52081,0.0243895)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.473111,0.000119601) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.60959,-0.0693227) , 
1, 5.27811, 1, 0, 0.484194,-0.0158974) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.08528,0.112354) , 
0, 2793.18, 1, 0, 0.508496,-0.00776057)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.174932,-0.0252668) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.56995,0.00243374) , 
0, 641.517, 1, 0, 0.459649,-0.0174635) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.637376,-0.0616023) , 
1, 5.86811, 1, 0, 0.47111,-0.0269747)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.23522,0.221873) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.692595,0.013751) , 
2, 0.00369077, 1, 0, 0.739659,0.0750543) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.462362,-0.0281989) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335435,0.00288271) , 
3, 0.243656, 1, 0, 0.377611,-0.0296756) , 
3, 0.160602, 1, 0, 0.511046,0.00892324)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.350268,-0.0516823) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.224874,-0.00889955) , 
2, 0.00390542, 1, 0, 0.235432,-0.0460994) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.791786,0.0179318) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354765,-0.0191194) , 
3, 0.36414, 1, 0, 0.718373,0.0358688) , 
1, 3.12873, 1, 0, 0.515405,0.00141959)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.278269,0.00385145) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.525281,-0.017764) , 
0, 771.998, 1, 0, 0.437337,-0.0379802) , 
NN(
0, 
0, 
1, 5.81278, 1, -99, 1.01502,0.0726453) , 
0, 2502.48, 1, 0, 0.474576,-0.0283435)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.315038,-0.00774499) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.396514,-0.0544633) , 
1, 4.32749, 1, 0, 0.321746,-0.0451515) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.887274,-0.0158633) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.808787,0.0252608) , 
2, 0.00728481, 1, 0, 0.832012,0.0528978) , 
0, 1233.68, 1, 0, 0.482059,-0.0143467)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.197664,-0.031809) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137064,-0.00794036) , 
3, 0.37031, 1, 0, 0.164403,-0.0669839) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.568486,0.018258) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.752276,-0.034398) , 
1, 5.08153, 1, 0, 0.601248,0.0407073) , 
1, 2.37241, 1, 0, 0.511012,0.0184622)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.137394,-0.0107546) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.541567,0.107065) , 
1, 1.83077, 1, 0, 0.348763,0.212162) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.675799,0.0133821) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.208744,-0.0111536) , 
3, 0.370373, 1, 0, 0.542448,0.023634) , 
0, 571.643, 1, 0, 0.529669,0.0360725)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.244065,-0.014427) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.356799,-0.0475872) , 
1, 3.7238, 1, 0, 0.260191,-0.0740387) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.758206,-0.00359201) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.587646,0.060692) , 
3, 0.295902, 1, 0, 0.727325,0.0401626) , 
0, 940.707, 1, 0, 0.483871,-0.0193552)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0853325,-0.0600169) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.46907,-0.00864956) , 
0, 525.782, 1, 0, 0.45057,-0.0397996) , 
NN(
0, 
0, 
3, 0.120975, 1, -99, 1.01036,0.0674539) , 
0, 2578.22, 1, 0, 0.484533,-0.0310827)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.486209,-0.0581872) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.899396,-0.0910828) , 
1, 3.73525, 1, 0, 0.702477,-0.131629) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.559071,0.00931573) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.134946,-0.0201171) , 
3, 0.580188, 1, 0, 0.500126,0.0209441) , 
2, 0.00367652, 1, 0, 0.515234,0.00955289)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.123374,-0.0375531) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.542862,0.00337536) , 
0, 552.254, 1, 0, 0.495151,-0.00445221) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.61069,-0.0809336) , 
1, 5.87339, 1, 0, 0.501424,-0.0157245)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.772922,0.0221654) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.581414,-0.0153624) , 
3, 0.0347452, 1, 0, 0.610878,-0.035074) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.306042,0.00134122) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.01565,0.104831) , 
1, 4.47961, 1, 0, 0.356679,0.0364877) , 
3, 0.234533, 1, 0, 0.502324,-0.00451413)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.121054,-0.0440172) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.146163,-0.00471758) , 
3, 0.197774, 1, 0, 0.140233,-0.0467356) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.616493,0.0068406) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.316723,-0.0165119) , 
2, 0.0868165, 1, 0, 0.592579,0.0168599) , 
1, 2.25012, 1, 0, 0.512296,0.00557289)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.260869,-0.035016) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.186317,-0.00711146) , 
3, 0.148244, 1, 0, 0.205157,-0.0533741) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.715102,-2.69431e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.562373,0.0547344) , 
3, 0.386392, 1, 0, 0.699777,0.0203197) , 
1, 3.09745, 1, 0, 0.495142,-0.010169)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.445477,0.0036712) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.693382,-0.0288953) , 
1, 4.62154, 1, 0, 0.49474,-0.00571986) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.0176,0.0726943) , 
1, 5.93702, 1, 0, 0.514539,0.000289869)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.614901,-0.0242951) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.517419,0.011944) , 
3, 0.0618682, 1, 0, 0.536501,0.0186648) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.212197,-0.0356375) , 
2, 0.0943028, 1, 0, 0.510378,0.00619534)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
0, 1675.45, 1, -99, 0.999759,0.0972834) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.578672,-0.0214741) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.434566,0.0043915) , 
3, 0.0865882, 1, 0, 0.470982,-0.00783891) , 
2, 0.00553615, 1, 0, 0.524387,0.0190264)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.735534,0.0162676) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.888236,0.0657992) , 
3, 0.0174452, 1, 0, 0.810092,0.137151) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504415,0.00180269) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.205325,-0.0284917) , 
2, 0.0738153, 1, 0, 0.467528,-0.00687303) , 
3, 0.0370733, 1, 0, 0.497204,0.00560342)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.36341,0.00825096) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.463491,-0.0191831) , 
0, 952.771, 1, 0, 0.396057,-0.00528493) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.791103,-0.0192143) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.893765,0.0407519) , 
3, 0.0610281, 1, 0, 0.863292,0.0655371) , 
0, 1315.27, 1, 0, 0.531715,0.0152777)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.431812,-0.00830309) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.95552,0.0432758) , 
1, 4.5629, 1, 0, 0.541453,-0.00429134) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.577479,0.0658921) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.309667,0.00148275) , 
2, 0.0873474, 1, 0, 0.442883,0.113281) , 
2, 0.0610194, 1, 0, 0.527035,0.0129059)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.728311,0.0162063) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.900938,0.0888586) , 
3, 0.115647, 1, 0, 0.747248,0.0807624) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.473192,-0.0573088) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.367564,-0.00367585) , 
2, 0.00548283, 1, 0, 0.38109,-0.036093) , 
3, 0.135785, 1, 0, 0.504702,0.00335635)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.641911,-0.00575438) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.45543,0.769562) , 
1, 4.1176, 1, 0, 0.86628,0.120672) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.555013,-0.0323023) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.395175,-0.006481) , 
3, 0.0741667, 1, 0, 0.42852,-0.0411112) , 
2, 0.00554722, 1, 0, 0.478525,-0.0226309)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.60715,-0.0286092) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.424758,0.00169728) , 
2, 0.00924537, 1, 0, 0.474393,-0.0177532) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.685749,-0.0760321) , 
1, 5.87335, 1, 0, 0.485733,-0.0259446)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.413392,-0.0486711) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302759,0.00445807) , 
2, 0.00554723, 1, 0, 0.318052,-0.0125952) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.909702,0.0428864) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.428309,-0.0119583) , 
3, 0.306176, 1, 0, 0.810247,0.0900499) , 
1, 3.61006, 1, 0, 0.536219,0.0329026)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.612342,0.013653) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.27659,0.278601) , 
1, 4.55379, 1, 0, 0.776639,0.121288) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.34929,0.00177583) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.640693,-0.0262716) , 
1, 4.31516, 1, 0, 0.428805,-0.0189315) , 
2, 0.00922692, 1, 0, 0.512632,0.0148609)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.18418,-0.0154343) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.182385,-0.0524376) , 
1, 3.34335, 1, 0, 0.183784,-0.0918432) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.501347,0.0135065) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.65772,-0.0186624) , 
0, 1003.27, 1, 0, 0.610191,-0.0228706) , 
0, 720.395, 1, 0, 0.4668,-0.0460645)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.247371,-0.0019713) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.853281,0.0635693) , 
1, 3.43822, 1, 0, 0.345374,0.0388699) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.793112,0.00503245) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.213289,-0.0464422) , 
3, 0.357649, 1, 0, 0.648916,-0.0362255) , 
0, 989.248, 1, 0, 0.498279,0.00104186)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.772816,-0.020548) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.04833,0.133689) , 
2, 0.003557, 1, 0, 0.865888,0.0831032) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.36412,-0.00289241) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.682905,-0.0360783) , 
1, 4.45793, 1, 0, 0.439425,-0.0320186) , 
2, 0.00554722, 1, 0, 0.490313,-0.0182816)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.721785,0.0573123) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.895622,0.0221571) , 
1, 3.86642, 1, 0, 0.827493,0.122228) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.549155,-0.0124099) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.39644,0.00968712) , 
2, 0.0221889, 1, 0, 0.482132,-0.00760119) , 
3, 0.0371153, 1, 0, 0.513997,0.00437773)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.104574,-0.0318245) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.674264,0.0162395) , 
1, 1.83307, 1, 0, 0.600464,0.0333957) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.382518,-0.0224702) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.247389,0.0213373) , 
3, 0.270716, 1, 0, 0.335414,-0.0379998) , 
2, 0.0369815, 1, 0, 0.520015,0.0117256)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.072399,-0.0591206) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.490031,0.00284332) , 
0, 522.219, 1, 0, 0.470381,0.000654164) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.958418,0.0171384) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.529397,-0.10971) , 
3, 0.194992, 1, 0, 0.79428,-0.0985195) , 
0, 2293.27, 1, 0, 0.504158,-0.00968812)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
3, 0.0205234, 1, -99, 0.982086,0.0913572) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.474729,0.00121109) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.655878,-0.0813956) , 
1, 5.77415, 1, 0, 0.486943,-0.00892115) , 
3, 0.0369984, 1, 0, 0.525699,0.013641)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.389626,0.00592138) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.07196,0.101169) , 
0, 1241.11, 1, 0, 0.424948,0.0393202) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.815869,-0.0130654) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.342849,-0.0584662) , 
3, 0.321044, 1, 0, 0.750403,-0.0564688) , 
0, 1396.77, 1, 0, 0.524196,0.0101091)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.750843,-0.0179778) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.295221,-0.0584718) , 
2, 0.0312548, 1, 0, 0.593987,-0.114843) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.816979,0.0420948) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37249,-0.00708731) , 
3, 0.154481, 1, 0, 0.471431,0.00968917) , 
3, 0.0618473, 1, 0, 0.493847,-0.0130887)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.429534,0.00587447) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.631472,-0.0440608) , 
0, 1635.86, 1, 0, 0.445169,0.00938533) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499522,-0.0709245) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.888508,0.00659996) , 
0, 1722.23, 1, 0, 0.72746,-0.092062) , 
1, 4.55654, 1, 0, 0.516292,-0.0161743)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.439938,-0.00384063) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.608951,-0.0796399) , 
1, 4.86953, 1, 0, 0.45223,-0.0277665) , 
NN(
0, 
0, 
1, 5.89626, 1, -99, 1.0834,0.109993) , 
1, 5.18714, 1, 0, 0.513516,-0.000624379)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.809309,0.0333728) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.281426,-0.0188754) , 
3, 0.320159, 1, 0, 0.622698,0.0406967) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.303456,-0.0550457) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.315665,-0.00715495) , 
3, 0.0496994, 1, 0, 0.313721,-0.0583976) , 
2, 0.0332833, 1, 0, 0.517018,0.00680341)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.584762,0.0488293) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.805505,0.0022884) , 
0, 759.719, 1, 0, 0.75853,0.0497222) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535389,-0.0352623) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.402811,0.000654706) , 
3, 0.165801, 1, 0, 0.427889,-0.0207822) , 
3, 0.110933, 1, 0, 0.517977,-0.00157236)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.336283,-0.00339779) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.407611,-0.0241672) , 
0, 947.726, 1, 0, 0.360703,-0.0403627) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.08775,0.180517) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.752592,-0.00443855) , 
2, 0.00728481, 1, 0, 0.836682,0.0300506) , 
0, 1288.43, 1, 0, 0.49925,-0.019867)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.900694,0.073147) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.235389,-0.012641) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.713024,0.0124392) , 
1, 3.25275, 1, 0, 0.47928,0.000380275) , 
3, 0.0247727, 1, 0, 0.501321,0.0117358)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.11727,0.167761) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.460352,0.000951854) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.672722,-0.0706146) , 
1, 5.3082, 1, 0, 0.49007,-0.0204181) , 
2, 0.0036907, 1, 0, 0.524697,0.00280613)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436969,-0.00270779) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.986346,0.0672628) , 
1, 4.85772, 1, 0, 0.497507,0.00617227) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.646161,-0.0959983) , 
1, 6.05047, 1, 0, 0.50441,-0.00384948)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.00419,0.0740719) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.502166,-0.0398237) , 
2, 0.00738864, 1, 0, 0.620094,-0.0899964) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.393703,-0.00349581) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.952778,0.055462) , 
1, 4.58379, 1, 0, 0.489439,0.0139204) , 
3, 0.0617233, 1, 0, 0.514456,-0.00597653)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.918422,0.0760167) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.426989,-0.00583347) , 
3, 0.0371282, 1, 0, 0.459393,-0.00269245) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.05157,0.1237) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.505503,-0.0881603) , 
2, 0.014565, 1, 0, 0.708169,-0.136546) , 
1, 5.23546, 1, 0, 0.489367,-0.01882)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
1, 3.51878, 1, -99, 1.02923,0.121471) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.402899,-0.0130052) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.00574,0.0733096) , 
0, 2530.12, 1, 0, 0.430339,-0.0389385) , 
2, 0.00554722, 1, 0, 0.486084,-0.0147195)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.468886,-0.03342) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.01841,0.0830742) , 
1, 4.34669, 1, 0, 0.629589,-0.0570258) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.385046,0.0101849) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.656648,-0.0504258) , 
1, 5.13321, 1, 0, 0.419107,0.0128497) , 
2, 0.0110721, 1, 0, 0.488972,-0.0103438)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.668423,-0.0380181) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.444297,0.00724343) , 
2, 0.0073963, 1, 0, 0.49028,0.00117153) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.518138,-0.084983) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.930279,0.0140945) , 
0, 2459.08, 1, 0, 0.666418,-0.160059) , 
1, 5.13889, 1, 0, 0.517256,-0.0235214)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.1259,0.130563) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.622618,0.00569943) , 
3, 0.0246926, 1, 0, 0.648184,0.0317001) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.221076,0.000581358) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.364142,-0.0286351) , 
1, 3.40367, 1, 0, 0.2969,-0.0642287) , 
2, 0.0332833, 1, 0, 0.522296,-0.00267748)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.377584,-0.0729984) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.821755,-0.0086499) , 
0, 1130.47, 1, 0, 0.557824,-0.15845) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.643158,-0.0429015) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.455056,0.0105944) , 
2, 0.00553606, 1, 0, 0.482299,0.0151035) , 
3, 0.0618114, 1, 0, 0.496453,-0.0174225)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.391606,-0.00304713) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.888359,0.0284383) , 
1, 4.34822, 1, 0, 0.499273,0.00545069) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.609104,-0.0677414) , 
1, 5.85578, 1, 0, 0.506917,-0.00734183)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.376776,-0.0109574) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.510453,-0.0697348) , 
1, 4.40329, 1, 0, 0.387601,-0.0520345) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.76961,-0.0337329) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.02129,0.0808399) , 
3, 0.0554183, 1, 0, 0.938047,0.0931774) , 
1, 4.63192, 1, 0, 0.486935,-0.0258295)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49353,-0.0562685) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.947179,-0.170358) , 
1, 3.99766, 1, 0, 0.660192,-0.132516) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.243273,0.0105858) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.581442,-0.0111496) , 
1, 3.0881, 1, 0, 0.452817,-0.0135069) , 
2, 0.00554722, 1, 0, 0.482272,-0.0304107)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.362951,2.47582e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.927917,0.0560099) , 
1, 4.09817, 1, 0, 0.481043,0.0338003) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.710741,-0.110407) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.992516,0.0625613) , 
1, 5.9223, 1, 0, 0.790255,-0.0986723) , 
0, 2176.9, 1, 0, 0.514074,0.0196492)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.441909,0.00798827) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.630638,-0.048708) , 
1, 4.51579, 1, 0, 0.481583,-0.00732437) , 
NN(
0, 
0, 
3, 0.109917, 1, -99, 1.09953,0.143576) , 
0, 2460.09, 1, 0, 0.521268,0.0043892)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0746641,-0.0371298) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.341729,0.00680782) , 
1, 1.60636, 1, 0, 0.299878,0.00641619) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522958,-0.0290844) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.90485,0.0183772) , 
0, 1638.05, 1, 0, 0.655865,-0.0596206) , 
1, 3.49251, 1, 0, 0.469674,-0.0250815)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4582,-0.0847867) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.895325,-0.0880005) , 
0, 1195.21, 1, 0, 0.684337,-0.152889) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.426602,-0.00172085) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.989429,0.0623297) , 
0, 1885.82, 1, 0, 0.507711,0.00819017) , 
2, 0.00367704, 1, 0, 0.523284,-0.00601213)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.205956,-0.00619361) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.545408,0.0230317) , 
1, 2.78425, 1, 0, 0.352054,0.0280371) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.305941,-0.0597099) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.722133,-0.016371) , 
0, 836.867, 1, 0, 0.663897,-0.0730909) , 
1, 3.69091, 1, 0, 0.49131,-0.0171225)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.291817,-0.0223236) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.885373,0.0377367) , 
1, 2.85745, 1, 0, 0.750327,0.0603611) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.274426,0.00460382) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.527369,-0.0281253) , 
1, 3.71327, 1, 0, 0.365366,-0.0250575) , 
3, 0.148145, 1, 0, 0.494689,0.00363773)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.932408,0.0675917) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.592315,-0.011463) , 
3, 0.0219489, 1, 0, 0.61585,-0.023346) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.276199,0.0301781) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.494727,-0.0469569) , 
0, 1403.24, 1, 0, 0.30961,0.0495304) , 
3, 0.296251, 1, 0, 0.514624,0.000742745)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.455624,-0.012397) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.275864,0.0192469) , 
3, 0.345715, 1, 0, 0.399753,-0.0149391) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.00577,0.0807161) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.836318,-0.0190594) , 
1, 5.21523, 1, 0, 0.915444,0.0716848) , 
1, 4.35926, 1, 0, 0.518712,0.0050432)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.360608,-0.00585911) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.01987,0.0887798) , 
0, 1304.99, 1, 0, 0.387575,-0.00822266) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.699932,-0.0659539) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.733277,0.0304801) , 
2, 0.0455157, 1, 0, 0.70396,-0.107052) , 
0, 1431.7, 1, 0, 0.475188,-0.0355903)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.299169,0.000322323) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.933946,0.0729184) , 
1, 3.75448, 1, 0, 0.353301,0.0264378) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.822177,0.00126284) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.510217,-0.0260786) , 
3, 0.184524, 1, 0, 0.677048,-0.0406315) , 
0, 1014.14, 1, 0, 0.51382,-0.00681634)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.177595,-0.033641) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.495372,-0.00316883) , 
0, 708.574, 1, 0, 0.346504,-0.0605618) , 
NN(
0, 
0, 
2, 0.0369432, 1, -99, 0.95816,0.0607896) , 
1, 4.32231, 1, 0, 0.486108,-0.0167181)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.650642,-0.0268465) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.736343,0.0332076) , 
3, 0.0412379, 1, 0, 0.715126,0.0555356) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.238029,-0.00360743) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439367,-0.0437966) , 
1, 3.63966, 1, 0, 0.304148,-0.0595754) , 
3, 0.222087, 1, 0, 0.506163,-0.00299305)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.735532,-0.0560032) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.523369,-0.0988026) , 
2, 0.00457292, 1, 0, 0.684272,-0.13228) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503595,0.00677215) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.190657,-0.0387249) , 
2, 0.0944836, 1, 0, 0.475968,0.00853038) , 
2, 0.00554148, 1, 0, 0.505539,-0.0114589)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.452926,-0.0277092) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.92886,0.0355418) , 
1, 4.66132, 1, 0, 0.567425,-0.0609032) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.794672,0.119157) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.229212,-0.0098451) , 
3, 0.327621, 1, 0, 0.279123,0.0270582) , 
3, 0.283454, 1, 0, 0.46144,-0.028567)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.328863,0.0482012) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.535599,0.000591268) , 
0, 559.859, 1, 0, 0.517354,0.0132221) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.08322,0.13458) , 
1, 5.79932, 1, 0, 0.542758,0.0217867)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.04222,0.139366) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.592493,-0.0242355) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.346918,0.000244333) , 
3, 0.185159, 1, 0, 0.466106,-0.0350269) , 
2, 0.00369815, 1, 0, 0.497062,-0.0168288)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.748333,0.00335155) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.362851,-0.103011) , 
3, 0.0377313, 1, 0, 0.606018,-0.106867) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.316235,-0.00421619) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.78151,0.0217298) , 
0, 1073.4, 1, 0, 0.485305,0.0121477) , 
3, 0.0493215, 1, 0, 0.503163,-0.00545892)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.371343,-0.00566006) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.532107,-0.0602561) , 
1, 4.46156, 1, 0, 0.394723,-0.0434653) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.89158,-0.0100537) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.08384,0.11222) , 
2, 0.0223119, 1, 0, 0.927681,0.0442873) , 
0, 1804.27, 1, 0, 0.478289,-0.029706)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.390203,0.00254806) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.724218,-0.0242056) , 
1, 4.20638, 1, 0, 0.478564,-0.0103146) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.39835,0.618034) , 
0, 2805.71, 1, 0, 0.507335,0.00381551)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.409787,-0.0389307) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.259552,-0.00417145) , 
2, 0.00747117, 1, 0, 0.28293,-0.0343162) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.894133,0.0487407) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.469509,-0.0183963) , 
2, 0.0258349, 1, 0, 0.734768,0.0390388) , 
0, 940.707, 1, 0, 0.496794,0.000404181)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.329617,-0.00728045) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.774154,0.0173889) , 
1, 3.87308, 1, 0, 0.437098,-0.00601773) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.01653,0.0867394) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.532376,-0.0694592) , 
2, 0.0146824, 1, 0, 0.745479,-0.0918079) , 
1, 4.89038, 1, 0, 0.489142,-0.0204962)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.908401,0.120697) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.290619,0.00740938) , 
2, 0.00581197, 1, 0, 0.342091,0.0730346) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.621373,-0.0202907) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.05851,0.202971) , 
1, 6.08857, 1, 0, 0.64697,-0.0519237) , 
0, 940.757, 1, 0, 0.509587,0.00438422)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.665554,0.0135903) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.237467,-0.0132235) , 
3, 0.321027, 1, 0, 0.494821,0.0100691) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.675016,-0.1269) , 
1, 5.95763, 1, 0, 0.504263,-0.00101713)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.409897,-0.0106351) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.09584,0.12153) , 
1, 4.92273, 1, 0, 0.434573,-0.0270707) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.59074,-0.0832267) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.945041,-0.0746536) , 
0, 2455.91, 1, 0, 0.754125,-0.129833) , 
1, 5.24675, 1, 0, 0.469194,-0.0382041)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.201755,-0.0424911) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.199128,-0.00152767) , 
3, 0.0991413, 1, 0, 0.199639,-0.0322758) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503332,0.0754774) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.718156,0.00870093) , 
0, 664.066, 1, 0, 0.700205,0.0524173) , 
1, 2.8973, 1, 0, 0.523613,0.0225389)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.303778,-0.00917658) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.855043,0.0330783) , 
1, 3.77646, 1, 0, 0.440732,0.000489385) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.06223,0.181974) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.467939,-0.0795244) , 
2, 0.0128471, 1, 0, 0.664259,-0.135693) , 
1, 4.92345, 1, 0, 0.48092,-0.0239945)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.160023,-0.0155602) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.612068,0.0166637) , 
1, 2.46736, 1, 0, 0.488827,0.0286087) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.570858,-0.117351) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.911485,-0.36626) , 
0, 2787.47, 1, 0, 0.743667,-0.16387) , 
0, 2374.78, 1, 0, 0.513977,0.00961303)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57822,-0.0580482) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540441,-0.0105056) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.261526,0.0187031) , 
3, 0.386012, 1, 0, 0.473846,-0.013577) , 
3, 0.024848, 1, 0, 0.481015,-0.0236434)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.415864,0.00599993) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.698515,-0.0440236) , 
1, 4.32921, 1, 0, 0.475122,-0.00528883) , 
NN(
0, 
0, 
1, 5.78223, 1, -99, 1.05106,0.124762) , 
1, 5.38498, 1, 0, 0.52405,0.0089217)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.307945,-0.0076709) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.878011,0.0436151) , 
1, 2.89857, 1, 0, 0.72266,0.0805551) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.238037,0.000714567) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.465889,-0.0208054) , 
1, 3.51023, 1, 0, 0.32115,-0.0277822) , 
3, 0.222254, 1, 0, 0.511614,0.0236098)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.887061,0.0427663) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.55157,-0.0157306) , 
3, 0.0492839, 1, 0, 0.596764,-0.0277133) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.634773,0.0452752) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.181177,-0.00323265) , 
3, 0.319892, 1, 0, 0.442387,0.0891931) , 
2, 0.0239896, 1, 0, 0.5363,0.0180745)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.872459,0.0590938) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.446526,-0.00394252) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.726602,-0.101127) , 
0, 2374.8, 1, 0, 0.472252,-0.0247998) , 
3, 0.0248153, 1, 0, 0.495415,-0.0141525)    );
   return;
};

// Clean up
inline void ReadBDT-0.4.6_fold7::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadBDT-0.4.6_fold7::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
