// Class: ReadBDT-0.4.6_fold6
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT-0.4.6_fold6
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.32/00       [401408]
Creator        : abennett
Date           : Thu Aug 22 16:00:00 2024
Host           : Linux 6772f6b99311 6.5.0-1022-azure #23~22.04.1-Ubuntu SMP Thu May 9 17:59:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /gluster/home/abennett/BDT_training
Training events: 19633
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "125" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "3%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "80" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e-01" [Learning rate for BoostType=Grad algorithm]
UseNvars: "2" [Size of the subset of variables used with RandomisedTree option]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "sdivsqrtsplusb" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 4
mjj                           mjj                           mjj                           m_{jj}                        GeV                               'D'    [500.083496094,7102.28710938]
JetGap                        JetGap                        JetGap                        #Delta y_{jj}                                                   'D'    [0.0204434599727,8.30311965942]
PtBalance                     PtBalance                     PtBalance                     pT_{balance}                                                    'D'    [1.2169821817e-09,0.149861991405]
centrality                    centrality                    centrality                    #xi(Z)                                                          'D'    [5.42057250641e-06,0.999970436096]
NSpec 1
eventNumber                   eventNumber                   eventNumber                   I                                                               'F'    [703,684984192]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new BDT-0.4.6_fold6Node

#ifndef BDT-0.4.6_fold6Node__def
#define BDT-0.4.6_fold6Node__def

class BDT-0.4.6_fold6Node {

public:

   // constructor of an essentially "empty" node floating in space
   BDT-0.4.6_fold6Node ( BDT-0.4.6_fold6Node* left,BDT-0.4.6_fold6Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT-0.4.6_fold6Node();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT-0.4.6_fold6Node* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT-0.4.6_fold6Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT-0.4.6_fold6Node*   fLeft;     // pointer to the left daughter node
   BDT-0.4.6_fold6Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   BDT-0.4.6_fold6Node::~BDT-0.4.6_fold6Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool BDT-0.4.6_fold6Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool BDT-0.4.6_fold6Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT-0.4.6_fold6 : public IClassifierReader {

 public:

   // constructor
   ReadBDT-0.4.6_fold6( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDT-0.4.6_fold6" ),
        fNvars( 4 )
   {
      // the training input variables
      const char* inputVars[] = { "mjj", "JetGap", "PtBalance", "centrality" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'D';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT-0.4.6_fold6() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[4];
   double fVmax[4];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[4];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT-0.4.6_fold6Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT-0.4.6_fold6::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT-0.4.6_fold6Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT-0.4.6_fold6Node*)current->GetRight();
         else current=(BDT-0.4.6_fold6Node*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
}

void ReadBDT-0.4.6_fold6::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536838,0.00736753) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.231558,-0.0536885) , 
3, 0.111259, 1, 0, 0.286512,-0.213488) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.272338,-0.0455324) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.809872,0.0619745) , 
1, 2.55491, 1, 0, 0.758198,0.258198) , 
0, 907.648, 1, 0, 0.51544,0.0154402)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.23291,-0.050064) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.493254,-0.00105931) , 
1, 3.05178, 1, 0, 0.328255,-0.16019) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.87629,0.0699346) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.464711,-0.0126732) , 
3, 0.313045, 1, 0, 0.813542,0.285652) , 
1, 3.91402, 1, 0, 0.497127,-0.00504381)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.38637,-0.0134829) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.149166,-0.0619281) , 
2, 0.00565009, 1, 0, 0.181434,-0.274276) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.835464,0.0610396) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.520401,-0.00054542) , 
2, 0.0184535, 1, 0, 0.671201,0.143154) , 
1, 2.86089, 1, 0, 0.500727,-0.00214151)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.470562,-0.00498083) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.159368,-0.0613937) , 
3, 0.456831, 1, 0, 0.391742,-0.0948273) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.874541,0.0622955) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.40191,-0.0231753) , 
3, 0.419155, 1, 0, 0.816202,0.251861) , 
0, 1315.17, 1, 0, 0.517779,0.00811593)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525698,0.00636672) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.235478,-0.0440126) , 
3, 0.210067, 1, 0, 0.350064,-0.117582) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.445,0.17688) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.823232,0.0470777) , 
2, 0.00550591, 1, 0, 0.892684,0.294642) , 
1, 4.14026, 1, 0, 0.50173,-0.0023627)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.367649,-0.0121365) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.182063,-0.047757) , 
2, 0.0108529, 1, 0, 0.236904,-0.179408) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.00842,0.0832992) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.645853,0.0177566) , 
2, 0.00922692, 1, 0, 0.753093,0.174163) , 
1, 3.06595, 1, 0, 0.536351,0.0257026)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.572488,0.0246165) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.25685,-0.0347963) , 
2, 0.00554723, 1, 0, 0.287162,-0.139705) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.828809,0.0463037) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.353096,-0.0312193) , 
3, 0.321102, 1, 0, 0.724083,0.134352) , 
0, 907.627, 1, 0, 0.507567,-0.00145708)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.486305,-0.00426808) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.175001,-0.0473454) , 
3, 0.419799, 1, 0, 0.394072,-0.0802522) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.00147,0.0746976) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.675128,0.0176565) , 
3, 0.258456, 1, 0, 0.929964,0.268613) , 
0, 1707.84, 1, 0, 0.488121,-0.0190263)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.375517,-0.01284) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.162374,-0.0466149) , 
3, 0.209865, 1, 0, 0.22867,-0.168506) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.747026,0.03257) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.47729,-0.0133207) , 
2, 0.0147926, 1, 0, 0.603523,0.0348123) , 
0, 720.518, 1, 0, 0.467786,-0.0388107)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.12235,-0.0512517) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.32784,-0.0142295) , 
1, 2.22574, 1, 0, 0.235874,-0.140291) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.807576,0.0408234) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.504697,-0.010013) , 
2, 0.0350623, 1, 0, 0.721272,0.116401) , 
1, 3.09148, 1, 0, 0.513311,0.0064255)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.866138,0.0549584) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.527587,7.50737e-05) , 
2, 0.00554148, 1, 0, 0.57521,0.0324307) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.12387,-0.0559463) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.157604,-0.0353236) , 
2, 0.029119, 1, 0, 0.134827,-0.219101) , 
3, 0.518516, 1, 0, 0.494684,-0.0135631)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.123436,-0.047176) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.480394,-0.00386691) , 
1, 2.56198, 1, 0, 0.35585,-0.0833607) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.95362,0.0621175) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.452565,-0.0146942) , 
3, 0.332254, 1, 0, 0.873695,0.2023) , 
0, 1315.19, 1, 0, 0.503012,-0.00218127)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.384233,-0.00780126) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.993576,0.0679813) , 
1, 3.20696, 1, 0, 0.708501,0.11652) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.550163,-0.000414821) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.233552,-0.0353497) , 
3, 0.247016, 1, 0, 0.397847,-0.0765401) , 
2, 0.00925074, 1, 0, 0.47487,-0.0286731)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.331279,-0.0130474) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.159752,-0.0411724) , 
2, 0.0425534, 1, 0, 0.280179,-0.094374) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.0748,0.106488) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.72391,0.0130601) , 
1, 3.67021, 1, 0, 0.746645,0.0820726) , 
1, 3.44767, 1, 0, 0.50677,-0.00866314)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.808291,0.0318624) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.462865,-0.00870799) , 
3, 0.185048, 1, 0, 0.629128,0.0399386) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.778718,0.0543519) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.355089,-0.025308) , 
2, 0.0164597, 1, 0, 0.378434,-0.0919487) , 
2, 0.0147926, 1, 0, 0.485901,-0.0354114)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.211666,-0.0311537) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.450799,-0.00575497) , 
0, 708.3, 1, 0, 0.337017,-0.0780134) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.995951,0.0709038) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.675247,0.00699913) , 
2, 0.0128471, 1, 0, 0.816667,0.124047) , 
0, 1233.66, 1, 0, 0.486428,-0.0150718)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.397559,-0.0110745) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.210463,-0.0352446) , 
2, 0.0333027, 1, 0, 0.328434,-0.0875587) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.998703,0.0855623) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.874578,0.0378285) , 
0, 1458.85, 1, 0, 0.889479,0.16073) , 
0, 1315.22, 1, 0, 0.486312,-0.0176906)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.288006,-0.012608) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.733729,0.0198663) , 
1, 3.0865, 1, 0, 0.5855,0.0360953) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0991211,-0.0394559) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.185338,-0.0536831) , 
1, 3.1834, 1, 0, 0.128653,-0.178691) , 
3, 0.530777, 1, 0, 0.513708,0.00234247)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.530699,-0.000460818) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.286532,-0.024528) , 
3, 0.160606, 1, 0, 0.368244,-0.0691034) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.775976,-0.00565437) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.950037,0.0589343) , 
3, 0.0742344, 1, 0, 0.887841,0.128117) , 
0, 1655.29, 1, 0, 0.466268,-0.031897)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.355681,-0.00572703) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.142532,-0.0368041) , 
3, 0.21006, 1, 0, 0.209197,-0.107462) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.711995,0.0125735) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28765,-0.0254416) , 
3, 0.370325, 1, 0, 0.613504,0.0124384) , 
0, 744.632, 1, 0, 0.469975,-0.0301262)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.881619,0.0568619) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.632821,0.00920032) , 
2, 0.00397145, 1, 0, 0.690897,0.0698695) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611142,0.0101916) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.317756,-0.0181837) , 
3, 0.135803, 1, 0, 0.409633,-0.0368456) , 
2, 0.0111009, 1, 0, 0.503141,-0.00136752)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499615,0.00572812) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.20944,0.153013) , 
1, 3.30324, 1, 0, 0.885347,0.197915) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.372102,-0.015114) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.847107,0.0223476) , 
0, 1715.91, 1, 0, 0.455166,-0.0385007) , 
2, 0.0037003, 1, 0, 0.486125,-0.0214861)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.13528,0.138073) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.682275,0.021852) , 
2, 0.00555045, 1, 0, 0.742292,0.123929) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.389958,-0.00685517) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.154447,-0.0361607) , 
2, 0.049925, 1, 0, 0.327198,-0.057119) , 
3, 0.209875, 1, 0, 0.509715,0.022488)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448754,-0.0030119) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.588519,-0.0631577) , 
1, 5.347, 1, 0, 0.460632,-0.0278342) , 
NN(
0, 
0, 
3, 0.118743, 1, -99, 1.07374,0.092847) , 
0, 2449.35, 1, 0, 0.50062,-0.00989827)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.2248,0.159444) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.676932,0.0170774) , 
3, 0.0863096, 1, 0, 0.809592,0.140203) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.474041,-0.00259523) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.243324,-0.0449875) , 
2, 0.0864969, 1, 0, 0.45129,-0.0276708) , 
2, 0.0073963, 1, 0, 0.5199,0.00447456)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.120067,-0.0370172) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.594868,0.00807964) , 
1, 1.79503, 1, 0, 0.547964,0.0148027) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.230615,-0.00508857) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.320769,-0.0342601) , 
1, 3.34742, 1, 0, 0.288379,-0.106301) , 
2, 0.0536231, 1, 0, 0.493901,-0.0104192)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.307287,-0.00591672) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.861104,0.0429227) , 
1, 2.9022, 1, 0, 0.671694,0.0844616) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.484518,-0.00234502) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.149069,-0.0320943) , 
3, 0.321007, 1, 0, 0.340342,-0.0561542) , 
2, 0.0182761, 1, 0, 0.494694,0.00934849)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.391052,-0.00705511) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.433768,-0.0782496) , 
1, 4.48243, 1, 0, 0.394527,-0.0486438) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.686544,-0.0474361) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.03084,0.0832289) , 
3, 0.0645017, 1, 0, 0.891685,0.0924691) , 
1, 4.65515, 1, 0, 0.473122,-0.0263354)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.229142,-0.0307489) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.188042,-0.00648773) , 
3, 0.271659, 1, 0, 0.206819,-0.0714433) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.762528,0.0240321) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354878,-0.0131017) , 
3, 0.368782, 1, 0, 0.69112,0.0628108) , 
1, 2.89482, 1, 0, 0.520229,0.0154377)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0601728,-0.0482161) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.589943,0.00594425) , 
1, 1.49969, 1, 0, 0.551686,0.00936772) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.229706,0.0139552) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.243585,-0.0377182) , 
1, 2.4978, 1, 0, 0.24078,-0.120036) , 
2, 0.0536543, 1, 0, 0.482863,-0.0192773)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
2, 0.00356114, 1, -99, 1.03822,0.125422) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.407643,-0.0125211) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.977315,0.059569) , 
0, 2521.55, 1, 0, 0.438085,-0.0380615) , 
2, 0.00554722, 1, 0, 0.501692,0.00252607)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.00522052,-0.0660629) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.15624,-0.0253795) , 
1, 0.988352, 1, 0, 0.129463,-0.107768) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.69166,0.0143483) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.308784,-0.0128951) , 
3, 0.320528, 1, 0, 0.573843,0.0205843) , 
1, 2.19829, 1, 0, 0.499619,-0.000854332)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520481,0.00400934) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.190287,-0.0416511) , 
2, 0.0899298, 1, 0, 0.493125,0.00023369) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.49204,0.274238) , 
0, 2674.06, 1, 0, 0.526597,0.0212772)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48094,0.00159795) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.722819,-0.0532287) , 
1, 5.16237, 1, 0, 0.516723,-0.0135851) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.190937,-0.0452193) , 
2, 0.0917652, 1, 0, 0.494926,-0.0245546)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.732181,0.0321828) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.717485,-0.043752) , 
1, 5.12052, 1, 0, 0.728383,0.0610492) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.317949,-0.0164431) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.947498,0.0419496) , 
1, 5.03032, 1, 0, 0.371528,-0.0483958) , 
3, 0.135776, 1, 0, 0.489334,-0.0122656)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.745579,0.0510445) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.301318,-0.0148322) , 
3, 0.0371297, 1, 0, 0.323018,-0.042342) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.649835,0.000193392) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.977421,0.0547771) , 
0, 1609.76, 1, 0, 0.809962,0.0617309) , 
1, 3.90621, 1, 0, 0.483878,-0.0079619)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.486787,-0.0370246) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.942759,0.0347715) , 
0, 2038.42, 1, 0, 0.564317,-0.105177) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.359621,-0.00467954) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.00607,0.0787046) , 
1, 4.52646, 1, 0, 0.4594,0.01724) , 
3, 0.0864412, 1, 0, 0.488053,-0.0161927)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0600281,-0.0523119) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.117341,-0.0118128) , 
2, 0.0257866, 1, 0, 0.0815215,-0.11935) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.648216,-0.01161) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.511607,0.00522941) , 
3, 0.0742191, 1, 0, 0.542946,0.00550304) , 
1, 1.69691, 1, 0, 0.503002,-0.00530517)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.160224,-0.0129573) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.174803,-0.039111) , 
0, 984.373, 1, 0, 0.162713,-0.0576897) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587567,0.0141725) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.806493,-0.0196564) , 
1, 5.30127, 1, 0, 0.621943,0.0384853) , 
1, 2.37231, 1, 0, 0.527177,0.0186389)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.590426,0.00473743) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.529837,0.0845592) , 
3, 0.383348, 1, 0, 0.587235,0.0300268) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.15355,-0.00241666) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.181155,-0.0392453) , 
1, 2.61594, 1, 0, 0.167638,-0.0803845) , 
3, 0.456864, 1, 0, 0.507517,0.00905017)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.205136,-0.032581) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.192597,-0.00257068) , 
3, 0.222612, 1, 0, 0.197091,-0.0536112) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.773568,0.0151265) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.451171,-0.0120796) , 
3, 0.221271, 1, 0, 0.636151,0.00863552) , 
1, 2.76222, 1, 0, 0.509142,-0.00937093)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.393196,-3.61369e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.56581,-0.0547693) , 
1, 4.61346, 1, 0, 0.414266,-0.0226013) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.01709,0.0734928) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.876702,-0.0149575) , 
0, 2378.04, 1, 0, 0.942913,0.0723145) , 
0, 1868.87, 1, 0, 0.497154,-0.00771925)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.486106,-0.0020698) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.205292,-0.0414178) , 
2, 0.0980579, 1, 0, 0.466878,-0.0179338) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.12543,0.149177) , 
0, 2782.33, 1, 0, 0.496474,-0.0080678)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.182449,-0.0395178) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.168904,-0.0144715) , 
3, 0.0995476, 1, 0, 0.170832,-0.0626227) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.657307,-0.0193362) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.642128,0.00943159) , 
3, 0.0493194, 1, 0, 0.644778,0.0157732) , 
1, 2.69586, 1, 0, 0.510199,-0.00648754)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.629736,-0.00966123) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.872101,0.0731806) , 
3, 0.151553, 1, 0, 0.650033,-0.00911388) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.223742,-0.00298471) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.475168,-0.032692) , 
1, 3.32299, 1, 0, 0.341078,-0.0619819) , 
3, 0.172918, 1, 0, 0.469208,-0.0400565)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.723462,0.0318734) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.378402,-0.00786421) , 
3, 0.0370613, 1, 0, 0.408412,-0.015229) , 
NN(
0, 
0, 
0, 2530.05, 1, -99, 1.13695,0.13417) , 
0, 1885.75, 1, 0, 0.494673,0.0169835)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.221107,-0.0110296) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.66688,0.0104668) , 
1, 3.01549, 1, 0, 0.477453,0.00523518) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.687014,-0.12031) , 
1, 5.7978, 1, 0, 0.490803,-0.00843256)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.127824,-0.0156924) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.574974,0.0984002) , 
1, 2.00202, 1, 0, 0.334301,0.171708) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.62684,-0.0172714) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.486365,0.00155205) , 
3, 0.0864977, 1, 0, 0.524955,-0.0121799) , 
0, 571.656, 1, 0, 0.511235,0.00105261)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.316939,-0.0267833) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.17773,0.164921) , 
1, 3.06949, 1, 0, 0.791324,0.109532) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.234622,-0.0166182) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.665309,0.00567868) , 
0, 929.167, 1, 0, 0.435829,-0.0227172) , 
2, 0.00738153, 1, 0, 0.504373,0.00278215)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.404095,-0.00686396) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.923017,0.0451269) , 
1, 4.75025, 1, 0, 0.453302,-0.0108549) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.895167,-0.0149986) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.592117,-0.134137) , 
3, 0.209535, 1, 0, 0.800393,-0.0984089) , 
0, 2291.59, 1, 0, 0.488271,-0.0196758)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.210118,-0.0399374) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.172241,-0.0109368) , 
2, 0.0187419, 1, 0, 0.188019,-0.0857038) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.53405,0.00388915) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.776168,-0.0769702) , 
1, 6.03563, 1, 0, 0.546583,0.00621815) , 
0, 581.592, 1, 0, 0.49765,-0.00632634)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.445727,-0.00437483) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.03825,0.0862426) , 
0, 2006.22, 1, 0, 0.477464,-0.00721838) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.612022,-0.109006) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.90491,-0.0410288) , 
0, 2769.41, 1, 0, 0.7672,-0.134412) , 
0, 2377.22, 1, 0, 0.505766,-0.0196428)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.610703,-0.000674644) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.487866,0.0306843) , 
3, 0.287994, 1, 0, 0.587406,0.0207032) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.156551,-0.00787754) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.187172,-0.0482499) , 
0, 1085.46, 1, 0, 0.163176,-0.0578192) , 
3, 0.43203, 1, 0, 0.489385,0.00256016)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.458503,0.0321053) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.701572,-0.022431) , 
0, 643.43, 1, 0, 0.664128,-0.0278693) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.643569,0.0391) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.412429,0.00102696) , 
2, 0.0161947, 1, 0, 0.466563,0.0339609) , 
2, 0.00925074, 1, 0, 0.521899,0.016643)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47916,-0.0190551) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.332422,0.00407436) , 
2, 0.0184538, 1, 0, 0.404532,-0.0249818) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.997998,0.0729231) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.929591,0.0116643) , 
0, 2067.56, 1, 0, 0.960066,0.103343) , 
1, 4.62853, 1, 0, 0.505444,-0.00167162)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0680177,-0.036346) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.488375,0.00297948) , 
1, 1.65611, 1, 0, 0.443278,-1.08308e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5914,-0.0649858) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.04515,0.0962654) , 
0, 2412.23, 1, 0, 0.746177,-0.0835207) , 
1, 4.9287, 1, 0, 0.49708,-0.0148442)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.476939,0.00104898) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.208329,-0.0402124) , 
2, 0.0943028, 1, 0, 0.457015,-0.00802248) , 
NN(
0, 
0, 
0, 1980.04, 1, -99, 1.01618,0.0755454) , 
1, 5.0832, 1, 0, 0.519331,0.0108758)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
2, 0.00280833, 1, -99, 0.888824,0.0637681) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.359434,0.00481369) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.656292,-0.0258037) , 
1, 4.10229, 1, 0, 0.461906,-0.0163104) , 
2, 0.00555045, 1, 0, 0.515134,0.00422758)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.771587,0.0970068) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.831063,0.0178115) , 
0, 913.162, 1, 0, 0.813915,0.17943) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.402245,0.00316029) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.69122,-0.0402406) , 
1, 4.52598, 1, 0, 0.469463,-0.0154959) , 
3, 0.0493974, 1, 0, 0.511631,0.00836665)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.851374,0.0523817) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.168313,-0.0265066) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.542974,0.00214352) , 
0, 581.7, 1, 0, 0.49073,-0.00643307) , 
3, 0.0246959, 1, 0, 0.511081,0.00446798)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.605244,0.023341) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289336,-0.0105661) , 
3, 0.0370956, 1, 0, 0.311446,-0.0282921) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.852234,0.0145401) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.786671,0.0530078) , 
3, 0.196786, 1, 0, 0.830537,0.0834107) , 
0, 1070.86, 1, 0, 0.516704,0.0158772)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.951873,0.0801939) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435688,0.00179759) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.675519,-0.0767054) , 
1, 5.13889, 1, 0, 0.47003,-0.0196076) , 
2, 0.0037003, 1, 0, 0.496033,-0.00728434)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.950065,0.0677385) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.575295,-0.00472546) , 
2, 0.00555045, 1, 0, 0.621182,0.00425609) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.198113,-0.0133811) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.33862,-0.0497315) , 
1, 3.97091, 1, 0, 0.222974,-0.0682521) , 
3, 0.320923, 1, 0, 0.481126,-0.0212462)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.350596,-0.0279109) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.279463,7.91262e-05) , 
3, 0.172952, 1, 0, 0.303455,-0.0380574) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.778851,-0.00622027) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.725428,0.0369242) , 
2, 0.0258354, 1, 0, 0.763853,0.0301533) , 
1, 3.59938, 1, 0, 0.503333,-0.00844437)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.678763,-0.0638068) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.466384,0.00397842) , 
2, 0.0037003, 1, 0, 0.482725,0.00267498) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.2049,0.288064) , 
0, 2835.08, 1, 0, 0.512657,0.0129759)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.810381,0.00115097) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.696465,0.0795506) , 
3, 0.246297, 1, 0, 0.775302,0.0835965) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.61678,0.00945136) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.267048,-0.0121265) , 
3, 0.222236, 1, 0, 0.436371,-0.00391796) , 
2, 0.00922692, 1, 0, 0.518441,0.0172732)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.381076,-0.00656134) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.542838,-0.0550423) , 
1, 4.61678, 1, 0, 0.396267,-0.0396541) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.705039,-0.0352475) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.00999,0.0680269) , 
1, 4.31858, 1, 0, 0.945525,0.0567813) , 
0, 1707.84, 1, 0, 0.492393,-0.022777)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.591115,-0.0200173) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392989,0.00807425) , 
2, 0.00922692, 1, 0, 0.44328,0.00651981) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509729,-0.0784026) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943135,0.00668849) , 
0, 2009.73, 1, 0, 0.762225,-0.101343) , 
1, 5.11366, 1, 0, 0.492118,-0.00999668)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.375662,-0.00410826) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.953089,0.0635916) , 
1, 4.16748, 1, 0, 0.422903,0.00231205) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.40879,-0.067703) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.82913,-0.0449315) , 
0, 1640.01, 1, 0, 0.69177,-0.133691) , 
1, 4.62199, 1, 0, 0.487607,-0.0304178)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.385845,-0.00508388) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.91731,0.0329628) , 
1, 4.32231, 1, 0, 0.517034,0.00404717) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.166472,0.00222594) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28686,-0.0458277) , 
1, 3.07001, 1, 0, 0.237026,-0.106914) , 
2, 0.0777062, 1, 0, 0.490102,-0.00662559)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0670389,-0.0387034) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.553313,0.00830634) , 
1, 1.67163, 1, 0, 0.501981,0.0153084) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.18734,0.28295) , 
0, 2619.34, 1, 0, 0.532033,0.0250493)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0731324,-0.0636514) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.226806,-0.000211826) , 
0, 522.201, 1, 0, 0.177469,-0.0617434) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.400773,0.0123283) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.699115,-0.00359393) , 
0, 984.108, 1, 0, 0.576721,0.0126874) , 
0, 581.592, 1, 0, 0.522315,0.00254463)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
3, 0.0196535, 1, -99, 0.919924,0.0651209) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448334,0.00266432) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.774973,-0.0976356) , 
0, 2110.42, 1, 0, 0.490997,-0.00964809) , 
3, 0.0370328, 1, 0, 0.523719,0.0083771)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.906175,0.0171006) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.922498,0.102812) , 
3, 0.246139, 1, 0, 0.910482,0.119415) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.410261,0.00104716) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.696162,-0.0518054) , 
1, 4.95097, 1, 0, 0.452133,-0.0147087) , 
2, 0.00554722, 1, 0, 0.507248,0.00141921)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.418691,-0.00900108) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.1901,0.15372) , 
1, 4.98262, 1, 0, 0.445549,-0.0172628) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.0073,0.0756444) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.575179,-0.0709189) , 
2, 0.0121523, 1, 0, 0.733614,-0.106013) , 
1, 5.3096, 1, 0, 0.478716,-0.0274813)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.401556,0.00325291) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.627442,-0.067904) , 
0, 1755.41, 1, 0, 0.412131,0.00273937) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528433,-0.0722079) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.776056,-0.0222308) , 
1, 4.67766, 1, 0, 0.726015,-0.0869424) , 
1, 4.45793, 1, 0, 0.492841,-0.0203208)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.7571,0.0201829) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.434957,-0.00297108) , 
3, 0.0740794, 1, 0, 0.495166,0.00501776) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.09221,0.136212) , 
1, 5.85578, 1, 0, 0.520927,0.0134662)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.518653,-0.0370725) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.32413,-0.00440269) , 
2, 0.00555045, 1, 0, 0.348909,-0.0298406) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.31411,0.72815) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.760382,-0.00166618) , 
2, 0.00553606, 1, 0, 0.830005,0.0385955) , 
1, 4.02639, 1, 0, 0.507101,-0.00733768)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.831153,0.0249444) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454966,-0.0189558) , 
3, 0.111075, 1, 0, 0.564215,-0.024584) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.20224,-0.00914989) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.776746,0.054875) , 
1, 3.44854, 1, 0, 0.410837,0.0600612) , 
2, 0.0296024, 1, 0, 0.514964,0.00259629)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.334429,0.00063411) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.446743,-0.0426347) , 
1, 4.00509, 1, 0, 0.352328,-0.0252189) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.955943,0.0523571) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.630923,-0.0148342) , 
2, 0.0309604, 1, 0, 0.858735,0.053738) , 
0, 1288.38, 1, 0, 0.499402,-0.00228764)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.25601,0.198243) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.607694,0.0130606) , 
3, 0.0247858, 1, 0, 0.643094,0.0602612) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.32696,-0.0257847) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.328151,0.00807893) , 
2, 0.0575407, 1, 0, 0.327421,-0.0481211) , 
2, 0.0275778, 1, 0, 0.511794,0.015181)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.852757,0.102546) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.777781,-0.000897716) , 
0, 742.014, 1, 0, 0.7869,0.0704292) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.248863,0.00135973) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.582855,-0.0214335) , 
1, 3.29269, 1, 0, 0.408725,-0.0306174) , 
3, 0.111131, 1, 0, 0.507482,-0.00423)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.823157,0.00898308) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.338809,-0.0516456) , 
2, 0.0371216, 1, 0, 0.656411,-0.0604271) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.595072,0.022271) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.16514,-0.014237) , 
3, 0.51342, 1, 0, 0.507751,0.050469) , 
3, 0.0617428, 1, 0, 0.536014,0.0293858)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.087144,-0.0143612) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0242951,-0.0576603) , 
0, 613.743, 1, 0, 0.0557099,-0.085208) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503092,0.00195372) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.860114,-0.0555654) , 
0, 2130.27, 1, 0, 0.547737,-0.00215539) , 
1, 1.50733, 1, 0, 0.510233,-0.008486)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.703774,0.0180163) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.33448,-0.0118591) , 
3, 0.135803, 1, 0, 0.443024,-0.00997405) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534005,-0.139767) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.94258,0.0418091) , 
3, 0.0801532, 1, 0, 0.740601,-0.122258) , 
1, 5.11366, 1, 0, 0.482733,-0.0249574)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
1, 3.47479, 1, -99, 0.932585,0.0799633) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.286254,-0.0149906) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.757557,0.00206778) , 
0, 1200.14, 1, 0, 0.429825,-0.0355137) , 
2, 0.00555045, 1, 0, 0.480597,-0.0155804)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557884,-0.076377) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.19994,6.05277) , 
1, 4.5583, 1, 0, 0.700797,-0.106449) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.199406,-0.0153491) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.625562,0.00852679) , 
0, 716.719, 1, 0, 0.476254,0.000714024) , 
2, 0.00547696, 1, 0, 0.507567,-0.0142301)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.83421,0.037041) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.551257,-0.0555431) , 
3, 0.0335886, 1, 0, 0.681585,-0.0358865) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.720781,-0.0396975) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.478208,0.0104121) , 
2, 0.0037003, 1, 0, 0.498205,0.0250785) , 
3, 0.0618213, 1, 0, 0.532043,0.0138291)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587289,-0.0908489) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.414848,-0.00748902) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.971083,0.0491811) , 
0, 1804.22, 1, 0, 0.509217,-0.0101161) , 
3, 0.012349, 1, 0, 0.512627,-0.0193029)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.37788,-0.0654675) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.82897,-0.0156395) , 
0, 1270.66, 1, 0, 0.546707,-0.166661) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527,0.00594002) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277752,-0.014926) , 
2, 0.0511183, 1, 0, 0.470825,0.00234077) , 
3, 0.0617372, 1, 0, 0.485496,-0.0303337)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.452663,-0.000226902) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.607594,-0.0758601) , 
1, 5.16424, 1, 0, 0.466911,-0.0186185) , 
NN(
0, 
0, 
1, 5.70817, 1, -99, 1.12219,0.259962) , 
0, 2456.29, 1, 0, 0.513834,-0.00556742)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.359509,-0.0108674) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.660216,-0.0994519) , 
0, 1830.49, 1, 0, 0.374322,-0.0460119) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.714852,-0.0403754) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.03665,0.0924343) , 
3, 0.0554183, 1, 0, 0.931694,0.0896571) , 
1, 4.60425, 1, 0, 0.478395,-0.0206797)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.401912,-0.0334528) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.258785,0.0108613) , 
2, 0.00554722, 1, 0, 0.282179,0.00574701) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.784468,0.00315753) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.413232,-0.0282435) , 
3, 0.217344, 1, 0, 0.622872,-0.0403932) , 
1, 3.19036, 1, 0, 0.483165,-0.0214726)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.384964,0.00267648) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.04294,0.105807) , 
1, 4.5846, 1, 0, 0.41774,0.0317888) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.855288,-0.0318718) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.547108,-0.0955878) , 
3, 0.258456, 1, 0, 0.789357,-0.0859941) , 
0, 1627.32, 1, 0, 0.501713,0.00517386)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.964743,0.0940567) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58265,-0.0298993) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.460234,0.00685941) , 
2, 0.00911476, 1, 0, 0.488576,-0.00220548) , 
2, 0.0037003, 1, 0, 0.51586,0.0119462)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.818738,0.0305644) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.429597,-0.0108563) , 
3, 0.0370529, 1, 0, 0.458177,-0.0266054) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.21823,1.1912) , 
0, 2835.11, 1, 0, 0.481698,-0.0187199)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.802848,-0.0139692) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.669017,0.0504563) , 
3, 0.135976, 1, 0, 0.72845,0.0727495) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.410363,-0.0453125) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.389142,0.00312713) , 
2, 0.0197138, 1, 0, 0.394851,-0.0323711) , 
2, 0.012951, 1, 0, 0.512892,0.00482493)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502083,-0.00596899) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437157,0.0417804) , 
2, 0.0592047, 1, 0, 0.493873,0.000372828) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.645445,-0.111935) , 
1, 5.84899, 1, 0, 0.504295,-0.0143108)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.578442,-0.000342507) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.565075,0.0307284) , 
2, 0.0230166, 1, 0, 0.575835,0.020631) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.232873,0.0101243) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.413526,-0.0299971) , 
1, 3.64435, 1, 0, 0.3132,-0.0358505) , 
2, 0.0388531, 1, 0, 0.49779,0.00384684)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.297886,-0.0585998) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.210264,-0.00541435) , 
2, 0.00395883, 1, 0, 0.218376,-0.0380912) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.670888,0.0723508) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.737185,-0.00124753) , 
0, 742.588, 1, 0, 0.729909,0.0312982) , 
1, 3.07742, 1, 0, 0.522174,0.00311906)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.662528,-0.12978) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.538848,0.00311174) , 
2, 0.0022609, 1, 0, 0.544446,0.000290267) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.417302,-0.000574161) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.422034,0.0861134) , 
3, 0.233582, 1, 0, 0.419542,0.105719) , 
2, 0.0610549, 1, 0, 0.528354,0.0138735)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.409597,-0.0335402) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.803173,-0.00288897) , 
0, 1191.64, 1, 0, 0.598802,-0.0720446) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.834618,0.0452721) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.406487,-0.00723276) , 
3, 0.108402, 1, 0, 0.442838,-0.00971892) , 
3, 0.0740668, 1, 0, 0.477675,-0.0236403)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.705278,0.0234339) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.38703,-0.0015993) , 
3, 0.13579, 1, 0, 0.483647,0.0211365) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.940535,-0.0471765) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.567244,-0.208864) , 
3, 0.195201, 1, 0, 0.821017,-0.117773) , 
0, 2351.98, 1, 0, 0.518951,0.00660043)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.179849,-0.0168338) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.244129,-0.0481326) , 
1, 3.09284, 1, 0, 0.203368,-0.108739) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.752458,-0.0140073) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.650071,0.0228496) , 
3, 0.086556, 1, 0, 0.680518,0.040284) , 
0, 780.106, 1, 0, 0.480845,-0.0220777)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.373872,-0.0133429) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.909176,0.0329039) , 
1, 3.49264, 1, 0, 0.702433,0.024661) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.22275,-0.000891223) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438369,-0.0455045) , 
1, 3.50097, 1, 0, 0.300288,-0.0594257) , 
3, 0.222072, 1, 0, 0.500315,-0.0176009)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.406991,-0.048426) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.897267,-0.035167) , 
0, 1144.46, 1, 0, 0.640727,-0.104067) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.484432,0.00500995) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.237694,-0.0297438) , 
2, 0.0653349, 1, 0, 0.44145,-0.0050995) , 
2, 0.00738864, 1, 0, 0.481816,-0.0251465)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
0, 1883.48, 1, -99, 0.860458,0.067488) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557498,-0.0385474) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.453874,0.00120513) , 
3, 0.0371725, 1, 0, 0.464781,-0.0101129) , 
2, 0.00555045, 1, 0, 0.505635,0.00712863)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524941,-0.00997901) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34301,0.0238977) , 
3, 0.271663, 1, 0, 0.44942,0.00998829) , 
NN(
0, 
0, 
0, 2785.38, 1, -99, 1.00956,0.0843732) , 
0, 1804.22, 1, 0, 0.540363,0.0283923)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.789162,0.0222549) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57292,-0.0216231) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.358961,-0.00200619) , 
3, 0.205278, 1, 0, 0.462529,-0.0360439) , 
3, 0.0246926, 1, 0, 0.481312,-0.0301539)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.948019,0.081703) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.503673,-0.000753643) , 
2, 0.00250981, 1, 0, 0.521258,0.00445713) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.179309,-0.0388646) , 
2, 0.101699, 1, 0, 0.497232,-0.00482338)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.36427,-0.00705928) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.573079,-0.0421386) , 
1, 4.46156, 1, 0, 0.395636,-0.0411337) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.10019,0.116103) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.921102,-0.00244069) , 
0, 2208.15, 1, 0, 0.966821,0.0556404) , 
0, 1885.77, 1, 0, 0.470058,-0.0285245)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.729878,0.0160621) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.433859,-0.0118092) , 
2, 0.00943344, 1, 0, 0.526695,-0.0154392) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583869,0.0351228) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.147634,-0.0147469) , 
3, 0.319795, 1, 0, 0.362495,0.0435408) , 
2, 0.0478015, 1, 0, 0.495238,-0.00414008)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.308493,-0.00866378) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.867284,0.0401316) , 
1, 3.25268, 1, 0, 0.615765,0.0394795) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.239563,-0.00941692) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.515355,-0.0578577) , 
0, 1408.47, 1, 0, 0.296624,-0.0637877) , 
2, 0.0314525, 1, 0, 0.502438,0.00280926)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.387722,-0.00695035) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.549572,-0.0499905) , 
1, 4.8955, 1, 0, 0.401335,-0.0344683) , 
NN(
0, 
0, 
0, 2429.97, 1, -99, 1.02571,0.099551) , 
0, 2004.92, 1, 0, 0.474569,-0.0164678)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.180301,-0.0407653) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.121065,-0.0095586) , 
2, 0.0075334, 1, 0, 0.134249,-0.0526904) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.318928,0.052205) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.614253,0.000967295) , 
0, 573.683, 1, 0, 0.596562,0.0163013) , 
1, 2.38871, 1, 0, 0.497034,0.00144852)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.08848,0.131437) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.340001,0.00276053) , 
2, 0.00554148, 1, 0, 0.385346,0.0433763) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.884682,0.0120118) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.58576,-0.0542992) , 
3, 0.148164, 1, 0, 0.721791,-0.0705537) , 
0, 1216.67, 1, 0, 0.510844,0.00087922)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.400823,-0.0107118) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.96781,0.0475786) , 
0, 1874.93, 1, 0, 0.455227,-0.0281189) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.703024,-0.0812568) , 
1, 5.7398, 1, 0, 0.46991,-0.0351983)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679927,0.00815961) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.720058,0.059404) , 
3, 0.20161, 1, 0, 0.688405,0.0607683) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.368577,-0.0680418) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.231354,-0.00819275) , 
2, 0.00553606, 1, 0, 0.249427,-0.0506225) , 
3, 0.308595, 1, 0, 0.529698,0.0204964)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.396872,5.57735e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.96547,0.067676) , 
1, 4.34051, 1, 0, 0.471539,0.0213006) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.02276,0.101494) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.601965,-0.0612087) , 
2, 0.0128471, 1, 0, 0.774819,-0.0764933) , 
1, 5.24096, 1, 0, 0.509055,0.00920347)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.266025,0.00385721) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.0475,0.165646) , 
1, 3.10273, 1, 0, 0.324233,0.0587672) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.642402,-0.0133497) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.661965,-0.0901681) , 
1, 5.98313, 1, 0, 0.644413,-0.0537933) , 
1, 3.30475, 1, 0, 0.506111,-0.00517276)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.8615,-0.0277913) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.497475,-0.0865947) , 
3, 0.159393, 1, 0, 0.652595,-0.1426) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478572,-0.000694142) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.161419,-0.0354931) , 
2, 0.0945793, 1, 0, 0.451429,-0.0121039) , 
2, 0.00554722, 1, 0, 0.47854,-0.0296902)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.497924,-0.00709169) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.399798,0.0261296) , 
2, 0.0590512, 1, 0, 0.483558,-0.0068242) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.97245,0.0807404) , 
1, 5.60871, 1, 0, 0.515912,0.00170978)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
3, 0.197071, 1, -99, 0.94394,0.0769017) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.433364,0.000315827) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.812813,-0.119847) , 
0, 2363.23, 1, 0, 0.463497,-0.00804126) , 
2, 0.0037003, 1, 0, 0.492617,0.00238311)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.335663,-0.00619205) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.855299,0.0253856) , 
1, 3.90683, 1, 0, 0.4941,0.00437582) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.636319,-0.0839089) , 
1, 5.74678, 1, 0, 0.504444,-0.0091431)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.00618,0.104098) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.590508,-0.0120049) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.313646,0.00888503) , 
3, 0.234606, 1, 0, 0.466996,-0.00896026) , 
2, 0.00369432, 1, 0, 0.497231,0.00281708)    );
   return;
};

// Clean up
inline void ReadBDT-0.4.6_fold6::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadBDT-0.4.6_fold6::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
